src/Data/DataSource.php
- This adds filters to the $node and $type in the `get_node_definitions` method, allowing externally defined "node" types to hook in so they can properly resolve for node queries
Resolves #93
=> Filter Node Definitions

src/Type/PostObject/PostObjectQuery.php, src/Type/TermObject/TermObjectQuery.php
Fixes a bug where the rootObject queries for postObjects and termObjects were resolving to the same type for all post_types and taxonomies
fixes: #102
=> Bug: RootQueryIssue

tests/test-post-object-queries.php
Closes #66. This covers the basic needs present for testing the
PostObjectType.
=> Add tests for post object queries.

tests/test-comment-object-queries.php
Closes #62. This covers the inital base levels for testing the comments
query.  Brings 100% coverage for `CommentType`
=> Add initial CommentType Object queries tests.

tests/test-post-type-object-queries.php
Fixes #67.  Adds basic PostTypeType object query tests.
=> Add basic PostTypeType object query tests.

tests/test-taxonomy-object-queries.php
Closes #69.  Adds the basic tests for taxonomy object type queries.
=> Adds the basic tests for taxonomy object type queries.

tests/test-post-object-queries.php, tests/test-post-type-object-queries.php, tests/test-taxonomy-object-queries.php, wp-graphql.php
**NOTE**: This is a breaking change.
Since tags can be connected to anything, not just posts, having the GraphQL Scheme use `postTags` as the naming just didn't make sense.
This PR changes the naming for the "post_tag" taxonomy to use "tag" and "tags". 
If you already have consumers consuming tags via the `postTag` naming convention, this change will break their queries, but you can use the action below to bring back the postTag naming convention for your system. 
```
add_action( 'graphql_generate_schema', function() {
global $wp_taxonomies;
if ( isset( $wp_taxonomies['post_tag'] ) ) {
$wp_taxonomies['post_tag']->graphql_single_name = 'postTag';
$wp_taxonomies['post_tag']->graphql_plural_name = 'postTags';
}
} );
```
=> #147 - Change postTags to tags

src/Type/Avatar/AvatarType.php, src/Type/Comment/CommentType.php, src/Type/Comment/Connection/CommentConnectionResolver.php, src/Type/MediaItem/MediaItemType.php, src/Type/Plugin/PluginType.php, src/Type/PostObject/Connection/PostObjectConnectionResolver.php, src/Type/PostObject/Mutation/PostObjectCreate.php, src/Type/PostObject/Mutation/PostObjectDelete.php, src/Type/PostObject/Mutation/PostObjectMutation.php, src/Type/PostObject/Mutation/PostObjectUpdate.php, src/Type/PostObject/PostObjectType.php, src/Type/PostType/PostTypeType.php, src/Type/Taxonomy/TaxonomyType.php, src/Type/TermObject/TermObjectType.php, src/Type/Theme/ThemeType.php, src/Type/User/UserType.php, src/WPSchema.php, wp-graphql.php
This adjusts instances of translated strings to use `__()` instead of `esc_html__()` and adds a `sanitize_schema` method that runs just before the Schema is sent to the Executor, which does the escaping on the description, name and deprecationReason as late as possible.
=> #152-translations-late-escaping

src/Router.php
Not sure how to write a test case for this since the router don't have any tests yet.
=> Add support for $_GET request, fixes #145

src/Type/TermObject/Mutation/TermObjectMutation.php, src/Type/TermObject/TermObjectType.php, tests/test-term-object-mutations.php
This fixes a mistake in the termObjectMutation where absint() was getting too many params passed.
That means parent's were never able to actually be set. . .so I fixed this. . .and added a test to make sure that a parent term could actually be set when doing a mutation.
While in there, I also added a "parent" field for hierarchical taxonomies.
So, this pr addresses #183 and #133
=> Term mutation, absint() error

src/Type/Comment/Connection/CommentConnectionResolver.php
Comment Parent Query Arg gets improperly set as “comment_parent” instead of “parent”
=> #186 - Fix default "parent" arg for comment connection resolver

src/Router.php, tests/test-json-responses.php, tests/test-router.php
This assures that if the user hits the namespace with no query they are
presented with a friendly well-formatted error. Noted in ticket #200
=> Return a user friendly error on an empty query

src/Type/PostObject/Connection/PostObjectConnectionResolver.php, src/Type/PostObject/PostObjectType.php, tests/test-post-connection-queries.php
This adds a child{PluralName} to hierarchical post_types.
For example:
```
{
pages {
edges {
node {
id
title
childPages {
edges {
node {
id
title
date
}
}
}
}
}
}
}
```
The field is intentionally _not_ labeled as “children”, as children of a post _can_ be of any type (posts can have parents of different post_types), so we’ll have to think through how to add a generic "children" field a bit more as it will need to be a union of some sort. . .
=> #209 children connection for post objects.

src/Data/DataSource.php, src/Type/PostObject/PostObjectQuery.php, src/Type/PostObject/PostObjectType.php, src/Type/RootQueryType.php, tests/test-post-object-queries.php
This exposes a new “uri” field on the postObjectType, which resolves to `get_page_uri()`
Then, this adds a new `postBy, pageBy, mediaItemBy` field that allows single postObjects to be queried `by` one of 3 fields, ID, GlobalID or URI.
To resolve based on the URI, a cached version of `get_page_by_path` was added to the DataSource (borrowed and modified from VIP’s mu plugins)
This includes unit tests to ensure these queries work and that the nodes returned match each time.
=> #207 - Get Post Objects by Global ID, Database ID, or URI.

src/Data/DataSource.php, src/Type/Enum/PostObjectFieldFilterEnumType.php, src/Type/Enum/PostObjectFieldFormatEnumType.php, src/Type/PostObject/Connection/PostObjectConnectionResolver.php, src/Type/PostObject/PostObjectType.php, src/Types.php, tests/test-media-item-mutations.php, tests/test-post-object-mutations.php, tests/test-post-object-queries.php, vendor/composer/autoload_classmap.php, wp-graphql.php
_Edited to reflect discussion and changes:_
This provides a method to request `RAW` or `RENDERED` format of post object fields:
```
query {
post(id: "...") {
content(format: RAW)
}
}
```
The `format` arg is available on `content`, `title`, and `excerpt`. If the `format` arg is omitted, then the default behavior will be `RENDERED` (which is simply to apply these filters: `the_content` on `content`, `the_title` on `title`, and `get_the_excerpt` and `the_excerpt` on `excerpt`).
It introduces a new enum type, `PostObjectFieldFormatEnumType`.
Perhaps more significantly, it sets up and resets post data during post object field resolution, so that any custom resolution undertaken by the user will have that done for them.
=> Add post object field format arg

.gitignore, src/Data/ConnectionResolver.php, src/Type/Comment/Connection/CommentConnectionDefinition.php, src/Type/Comment/Connection/CommentConnectionResolver.php, src/Type/Plugin/Connection/PluginConnectionDefinition.php, src/Type/Plugin/Connection/PluginConnectionResolver.php, src/Type/PostObject/Connection/PostObjectConnectionDefinition.php, src/Type/PostObject/Connection/PostObjectConnectionResolver.php, src/Type/TermObject/Connection/TermObjectConnectionDefinition.php, src/Type/TermObject/Connection/TermObjectConnectionResolver.php, src/Type/Theme/Connection/ThemeConnectionDefinition.php, src/Type/Theme/Connection/ThemeConnectionResolver.php, src/Type/User/Connection/UserConnectionDefinition.php, tests/test-comment-connection-queries.php, tests/test-plugin-queries.php, tests/test-post-connection-queries.php, tests/test-term-object-connection-queries.php, tests/test-theme-connection-queries.php
Addresses #247 
This adds "nodes" field to connections so that queries can query for the nodes directly without edge data. FYI, this is also how Github does it.
Ex:
```
{
plugins {
edges {
node {
id
}
}
nodes {
id
name
}
}
users {
nodes {
id
}
edges {
node {
id
}
}
}
themes {
nodes {
id
version
}
edges {
node {
id
}
}
}
comments {
edges {
node {
id
}
}
nodes {
id
}
}
posts {
pageInfo {
startCursor
endCursor
}
nodes {
id
title
comments {
nodes {
id
content
}
}
}
}
tags {
nodes {
name
id
}
}
}
```
=> #247 - Add nodes to connections

src/Type/PostObject/Connection/PostObjectConnectionResolver.php, tests/test-post-connection-queries.php
Testing every single parameter of sanitize_input_fields, also testing get_query_args.
=> CI-4215 - Adding tests for sanitize_input_fields and get_query_args in PostObject Connection

composer.json, src/Data/DataSource.php, src/Data/Loader.php, src/Type/PostObject/PostObjectType.php, tests/test-user-object-queries.php, wp-graphql.php
Addresses #55 (at least initially, more to come, should probably become their own issues...)
This adds initial support for Deferred resolvers (DataLoader concept). 
This initially adds a User loader to prove concept and pattern. 
But the benefits are immediately clear. For example, this exact same query before and after this PR goes from `28` SQL queries to `8` with a `28%` increase in overall execution time!
=> Initial Implementation of DataLoader (deferred resolvers) 

src/Type/PostObject/Connection/PostObjectConnectionArgs.php
A few WP plugins (ex: [SCPOrder](https://en-gb.wordpress.org/plugins/simple-custom-post-order/)) allow users to re-arrange the sort order of the posts, and then assigns a value to the `menu_order` field in the database.
This PR would allow the GraphQL endpoint to return the posts in that specified order
```graphql
posts(where: { 
categoryName: "projects"
orderby: { field: MENU_ORDER, order: ASC }
}) {
menuOrder
title
link
} 
```
=> Ability to sort by menu_order

src/Type/TermObject/Connection/TermObjectConnectionArgs.php
When writing a WPGraphQL plugin for CoAuthors Plus, the only way to return the authors in the correct order (as added by the editor) was to order by `term_order`. This is seldom-used but I think perfectly valid `ORDERBY` value. It is documented in `wp_get_object_terms`:
https://codex.wordpress.org/Function_Reference/wp_get_object_terms
=> Add TERM_ORDER as TermsOrderby enum.

src/Type/MediaItem/MediaItemType.php, tests/wpunit/MediaItemQueriesTest.php
The get_the_excerpt filter calls wp_trim_excerpt which, if the caption / excerpt is empty, uses global $post->post_content (a.k.a., the parent post) as the seed for crafting the excerpt.
This means that if you leave the caption field blank for a featured image, WPGraphQL currently populates the caption field with the excerpt of the parent post (or possibly even a different post).
I think it's safe to assume this isn't going against user's expectations, since you would need to setup post data *for the attachment* to use get_the_excerpt for image captions.
=> Remove get_the_excerpt filter for image caption.

src/Router.php
This addresses #346 and #349.
This sets the `$http_status_code` to `200` by default.
Additionally, this refactors the headers that are sent in the response to be a filterable array, allowing for headers to more easily be adjusted.
=> #349 - Allow response headers to be filterable

src/Type/PostObject/Connection/PostObjectConnectionArgs.php, src/Type/PostObject/Mutation/PostObjectMutation.php, src/Type/PostObject/PostObjectType.php, src/Types.php, tests/wpunit/MediaItemMutationsTest.php, tests/wpunit/PostObjectMutationsTest.php, tests/wpunit/PostObjectQueriesTest.php
Addresses https://github.com/wp-graphql/wp-graphql/issues/364
=> Fix: remove double quote from description

src/Router.php, src/Type/PostObject/Mutation/PostObjectCreate.php, src/Type/PostObject/Mutation/PostObjectMutation.php, src/Type/PostObject/Mutation/PostObjectUpdate.php, src/Type/WPInputObjectType.php, tests/wpunit/PostObjectNestedMutationsTest.php
This adds support to set term connections via nested input in PostObjectMutations.
For example: 
```
mutation CreatePostWithNewCategoryAndTag {
createPost(
input: {
title: "New Post", 
status: PUBLISH, 
tags: {
append: true, 
nodes: [
{
name: "My New Tag", 
description: "New Tag Description"
}
]
}, 
categories: {
append: true, 
nodes: [
{
name: "My New Category", 
description: "New Category Description"
}
]
}, 
clientMutationId: "uniqueId"
}) {
post {
id
title
tags {
edges {
node {
id
name
slug
description
}
}
}
categories {
edges {
node {
id
name
slug
description
}
}
}
}
}
}
```
Outputs: 
```
{
"data": {
"createPost": {
"post": {
"id": "cG9zdDo2NTE3",
"title": "New Post",
"tags": {
"edges": [
{
"node": {
"id": "cG9zdF90YWc6Mzc3",
"name": "My New Tag",
"slug": "my-new-tag",
"description": …
```
=> #333 - Set term connections as nested input in PostObjectMutations

src/Router.php, src/Type/MediaItem/Mutation/MediaItemMutation.php, tests/wpunit/MediaItemMutationsTest.php, tests/wpunit/PostObjectConnectionQueriesTest.php, wp-graphql.php
This adds Query Batching support for remote HTTP GraphQL requests.
Apollo Query batching (https://dev-blog.apollodata.com/query-batching-in-apollo-63acfd859862) will now work with this. 
Now you can send an array of Queries in the HTTP request and get an array of responses back. Here's an example in Postman:
closes #360 
Any relevant logs, error output, GraphiQL …
=> #360 - Query Batching

src/Type/PostObject/Mutation/PostObjectCreate.php, src/Type/PostObject/Mutation/PostObjectMutation.php, src/Type/PostObject/Mutation/PostObjectUpdate.php, tests/wpunit/PostObjectMutationsTest.php
During PostObjectMutations, any post_status input will be cached, and the post will be created with the default status (draft, but filterable to accompany plugins like Edit Flow, etc).
Then the side-effects will be triggered via `PostObjectMutation::update_additional_post_object_data()`. 
Then, if `$should_set_intended_status` is true (filterable), the post_status that was input with the mutation (if different than the default) will be set as the status of the post.
This allows for side effects that may take a long time (sideloading images, etc) to happen in a deferred process (like a WPCron or a WP Queue Task - https://github.com/dfmedia/wp-queue-tasks) and those side effects can come …
=> Set post status for Post Object Create mutations late, to allow for side-effects before final status is set

src/Data/Config.php, tests/wpunit/DataConfigTest.php
This is an attempt to address #406 (see for details).
This adjusts the where clause generated by WP_Query pagination logic to use only `post_date` and not post `ID` to accommodate out-of-order post publishing.
I've added some tests that will produce failures in the current codebase but pass with these changes. They simulate publishing posts out-of-order, such that post ID `12` is not guaranteed to be published after post ID `11` (as an example).
One side-effect of this change is that posts could get duplicated across pagination boundaries _if_ the cursor post shares the exact same publish date (to the second) with another post. In that instance, there is no way to determine which side of the boundary the post belongs to (without, say, storing query results in a state store). However, this …
=> Fix adjustments to WP_Query pagination to use only post_date.

src/Type/Comment/Connection/CommentConnectionArgs.php, src/Type/PostObject/Connection/PostObjectConnectionArgs.php, src/Type/TermObject/Connection/TermObjectConnectionArgs.php
Update Connection Args to have more context for filters to take advantage of (WPGraphQL Tax Query and WPGraphQL Meta Query should work now!)
closes #416
=> #416 - pass more context to filters for input args

src/Router.php
This makes it easier to filter the list of "access control allowed headers"
usage: 
```
add_filter( 'graphql_access_control_allow_headers', function( $headers ) {
$headers[] = "YourNewHeader";
return $headers;
} );
```
closes #425
=> #425 - filter access control headers

src/Type/PostObject/Connection/PostObjectConnectionArgs.php, src/Type/PostObject/Connection/PostObjectConnectionResolver.php, tests/functional/PostListWithDifferentStatusCept.php, tests/wpunit/PostObjectConnectionQueriesTest.php
Added query parameter `stati` as listOf enums for post_status
```
{
posts( where: { stati: [ PUBLISH, DRAFT ] } ) {
...
}
}
```
#332 
https://drive.google.com/file/d/1WcQesulilsDYzdp_PBLzYSaqMDZ_er02/view
Testing was done using Docker.
WordPress: 4.9.4
PHP: 7.2
Apache
=> [#332] Added support for stati parameter as list of enums

src/Type/PostObject/Connection/PostObjectConnectionResolver.php
This fixes the orderby mapping of post__in, post_name__in and post_parent__in so that the order value is not included as that is not respected by WP_Query. See: https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters
addresses #436
Here's screenshots of before/after showing the order not properly working, then working with the fix in place.
=> #436 - fix orderby mapping of post__in, post_name__in and post_parent__in

src/Router.php
- This adjusts the `wp_send_json` to happen _after_ the try/catch in the router, allowing for exceptions to properly be returned in the JSON response
This moves the `wp_send_json()` to happen after the try/catch so that exceptions, even those outside of the `do_graphql_request` execution are returned properly in the JSON response.
This addresses #442. Thanks for reporting @dlh01!
Below is a screenshot showing that a misconfigured post type returns the exception on why the post_type isn't showing in the …
=> No JSON Response when exceptions occur outside of do_graphql_request

src/Type/PostObject/Mutation/PostObjectMutation.php
This fixes a bug when setting a parentId for postObjectMutations. 
The global ID isn't always cast as an integer, sometimes it's a string. This makes sure to respect integers and integers cast as strings.
=> fix bug with setting the parentId for postObjects

wp-graphql.php
This PR prevents a fatal error due to duplicate declaration of the `graphql_init` method in `wp-graphql.php`. This error is a possibility in the case that multiple themes or plugins include `wp-graphql` as a composer repository or the code is otherwise used in multiple locations in a single WP instance. 
**Operating System:** MacOS 10.13.4
**WordPress Version:** 4.9.6
=> Check for duplicate declaration of graphql_init

docker-compose.dev.yml
Provides a separate, isolated local environment for user testing in the browser, accessible by default at http://wpgraphql.example. Environment can be started with:
```
docker-compose -f docker-compose.dev.yml up -d
```
Docker on OS X
=> Add docker-compose file for local / user testing.

composer.json, src/Type/Enum/MenuLocationEnumType.php, src/Type/Menu/Connection/MenuConnectionDefinition.php, src/Type/Menu/Connection/MenuConnectionResolver.php, src/Type/Menu/MenuQuery.php, src/Type/Menu/MenuType.php, src/Type/MenuItem/Connection/MenuItemConnectionDefinition.php, src/Type/MenuItem/Connection/MenuItemConnectionResolver.php, src/Type/MenuItem/MenuItemQuery.php, src/Type/MenuItem/MenuItemType.php, src/Type/PostObject/Connection/PostObjectConnectionResolver.php, src/Type/RootQueryType.php, src/Type/Union/MenuItemObjectUnionType.php, src/Types.php, tests/functional/MenuWithMenuItemsCept.php, tests/wpunit/MenuConnectionQueriesTest.php, tests/wpunit/MenuItemConnectionQueriesTest.php, tests/wpunit/MenuItemQueriesTest.php, tests/wpunit/MenuQueriesTest.php, wp-graphql.php
Implements navigation menu support with two new types: `Menu` and `MenuItem`. Each have singular and plural root queries. `MenuItems` are connected to both `Menus` and to themselves—this allows for the implementation of `childItems` (hierarchical nav menu queries):
```
{
menus( location: MY_MENU ) {
edges {
node {
id
menuItems {
edges {
node {
id
childItems {
edges {
node {
id
connectedObject {
... on Post {
id
title
content
}
}
}
}
}
connectedObject {
... on Post {
id
title
content
}
}
}
}
}
}
}
}
}
```
MenuItems can also be queried directly with an `id` or `location`:
```
{
menuItems( location: MY_MENU ) {
edges {
node {
id
connectedObject {
... on Post {
id
title
content
}
}
}
}
}
} …
```
=> Nav Menu support

src/Type/Union/CommentAuthorUnionType.php, src/Type/Union/PostObjectUnionType.php, src/Type/Union/TermObjectUnionType.php, src/Type/WPUnionType.php
Adds WPUnionType. Much like WPObjectType and WPEnumType, etc., which allows for filters and other helpers to be centralized in one spot.
Fixes #432.
If approved, can be added to NavMenu PR.
=> Add WPUnionType.

src/Type/WPObjectType.php
When creating WPUnionType, I noticed a pointless filter (unused result). Also moved the name change above the filter so that it could be changed in filter if needed.
The PR diff is a bit obtuse, take a look at individual commits for simple version.
=> Clean up WPObjectType constructor

src/Type/Union/MenuItemObjectUnionType.php
Use WPUnionType for MenuItemObjectUnionType now that #456 is merged.
=> Use WPUnionType for MenuItemObjectUnionType

src/Router.php
In the `WPGraphQL\Router` class currently the `after_execute` function receives an empty `$request` parameter for POST requests. GET requests are fine. Now the variable will contain the original request data. This will be useful for filters such as `graphql_request_results`
No
Currently, if you add this filter: 
```
function filter_result( $result, $schema, $operation, $request, $variables ) {
error_log( print_r( [ 'request' => $request, 'result' => $result ], true ) );
return true;
}
add_filter( …
```
=> Populate $request variable for POST requests

src/Type/TermObject/Connection/TermObjectConnectionResolver.php
When querying categories children it throws an error as $GLOBALS['post'] is null.
Query example:
categories {
nodes {
slug
children {
nodes {
slug
}
}
}
}
…
… …
=> Bug when querying categories children

cli/wp-cli.php, wp-graphql.php
This re-arranges the setting up of the post_types and taxonomies to `show_in_graphql` to happen later in the WordPress setup cycle to make sure post_types like `attachments` have properly been setup already.
@rasmustaarnby: With this change in place, `wp graphql generate-static-schema` can be run without errors.
closes #475  …
=> #475: Re-arrange setup of Types (post_types, taxonomies, etc) that are registered to show_in_graphql

README.md, tests/wpunit/PostObjectConnectionQueriesTest.php
Improves the speed of `PostObjectConnectionQueriesTest` by reducing the number of posts that are created in `setUp`. Creating a large number of posts is quite slow (or maybe it's the tear down?). We only need a large number of posts for one test, so this reduces the default number created and creates more inside that one test.
Shaves about 60s off test runs on my computer—more on coverage runs.
It also adds a clarifying note to the README concerning code coverage in PHP 7.2.
```
✔ PostObjectConnectionQueriesTest: First post (4.63s)
✔ PostObjectConnectionQueriesTest: Last post (4.15s)
✔ …
```
=> Improve speed of PostObjectConnectionQueriesTest

wp-graphql.php
Recent changes in hooks caused Settings to not be added to the Schema properly.
=> bug: settings not loaded in Schema properly

src/Data/DataSource.php, tests/wpunit/PostObjectQueriesTest.php
Fixes a grammatical error in an error message that has been bugging me for a long time. 😂
It's worth noting that this is actually a breaking change for us! This error corresponds to a 404 response for us on the client. But because this is a error and not an empty response, we have to catch all errors and inspect them in order to determine whether we should 404. The only way to do this is to regex the string, making it a bit fragile.
Have we considered implementing error codes (either on the error object or leading the message)?
Added test, which would at least catch future changes to the message.
=> Fix error message for non-existent post

src/Type/PostObject/Connection/PostObjectConnectionResolver.php
Correct get_connection function to return corect value for &has_previous_page and &has_next_page even if we query all pages
Correct get_connection function to return corect value for &has_previous_page and &has_next_page even if we query all pages
#533
(If it’s long, please …
=> Correct issue #533

src/Type/PostObject/Connection/PostObjectConnectionResolver.php
Not sure if this is bug but I noticed that the implementation does not match with the doc block of the `graphql_map_input_fields_to_wp_query`.
It states that the post type is passed as the third argument
https://github.com/wp-graphql/wp-graphql/blob/aa69a640b6877292a84a710c7270ac7403680b95/src/Type/PostObject/Connection/PostObjectConnectionResolver.php#L360
but the actual third argument is the `$source`.
=> Fix $post_type in graphql_map_input_fields_to_wp_query

tests/wpunit/NodesTest.php, tests/wpunit/PluginObjectQueriesTest.php
Adds a message in case of test failure to the asserts suggesting that an error may occur if hello dolly is not present as a plugin in the WordPress installation
**Relates to issue #543 **
Example for wpunit/PluginObjectQueriesTest:
```
Codeception PHP Testing Framework v2.4.5
Powered by PHPUnit 7.3.5 by Sebastian Bergmann and contributors.
Wpunit Tests (2) -----------------------------------------------------------------------------------------------------------------------------
✖ PluginObjectQueriesTest: …
```
=> Fixes #543.

README.md
- Adds to the README instructions on how to run specific tests.
- Removes the `unit`group of tests since it doesn't exist. It is not listed in the Docker section either.
Issue #545 
…
…
**Operating System:** Mac OS X
**WordPress Version:** 4.9.8
=> Fixes #545

src/Type/Object/PostObject.php
fix bug with the v0.1.0 release missing a `use` statement. 
Good catch @mngi-arogers
=> fix bug with missing use statement

docker-tasks/run-local-app/docker-compose.yml, docker-tasks/run-local-app/uploads.txt
- Moves docker `local-app` proxy port to `8000`
- Raises upload file max-size to 64MB
…
… …
=> local-app file upload limit size pushed to 64MB

src/Connection/TermObjects.php
This adds the `children` field to TermObjects of hierarchical Taxonomies. The field was left commented out during the refactor to v0.1.0 🤦‍♂️ 
#573
This query works with this fix in place.
```
{
categories {
nodes {
id
name
children { …
```
=> #573 - adding the "children" connection to TermObjects

.env, Dockerfile, README.md, docker-entrypoints/run-codeception.sh, docker-tasks/bin/run-docker-compose-up.sh, docker-tasks/common/env-files/env.sh, docker-tasks/run-local-app/docker-compose.yml, docker-tasks/run-test-environment/docker-compose.yml, docker-tasks/run-tests/docker-compose.yml, run-docker-local-app.sh, run-docker-shell.sh, run-docker-test-environment.sh, run-docker-tests.sh
- [ x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x ] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!
- Use of the test shell no longer changes files on the host OS so the `chown` workaround is no longer needed
- run-docker-shell no longer uses `sudo` itself
- Ensuring all …
=> CI-5884 | Docker test shell no longer changes files on host OS; misc Docker cleanup

src/Mutation/SendPasswordResetEmail.php, src/TypeRegistry.php, tests/wpunit/UserObjectMutationsTest.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_framework_classmap.php, vendor/composer/autoload_static.php
- Original work by @kellenmace, this just updates it to fit with the v0.1.0 refactored architecture
This adds a `sendPasswordResetEmail` mutation
closes #491 
see: https://github.com/wp-graphql/wp-graphql/pull/494
The bulk of the work …
=> #491 - Send Password Reset Mutation

src/Type/WPInputObjectType.php, src/Type/WPObjectType.php, src/TypeRegistry.php
I'm not sure how I missed this in reviewing the Type registry changes or if this snuck in after I reviewed them, but the `graphql_input_fields` filter (what we use to implement custom `where` args) is now fairly broken.
The issue is that the `fields` definition for every object type is now wrapped in a closure (see [TypeRegistry#L366](https://github.com/wp-graphql/wp-graphql/blob/develop/src/TypeRegistry.php#L366)), which delegates to `WPObjectType::prepare_fields` to apply various filters. Then `WPInputObjectType` attempts to apply its own filters by calling `self::prepare_fields` in its constructor, but `fields` is now a closure (not an array) and the method call is skipped. As a …
=> Restore graphql_input_fields filter

src/Data/PostObjectConnectionResolver.php, src/Data/TermObjectConnectionResolver.php
- This adjusts the PostObjectConnectionResolver and the TermObjectConnectionResolver to ensure that search queries include terms that don't have the parent set to 0.
=> #598 - searching for terms doesn't include children in results

src/TypeRegistry.php
- this allows all core types (connections, unions, mutations included) to be registered prior to custom Types being registered.
closes #612 
Currently, the hook `graphql_register_types` is fired before connections, unions, and mutations are registered. 
This moves the hook later, so all Types, (including connections, mutations, and unions) have been registered by this time. 
Now, when hooking into `graphql_register_types`, all core types registered by the plugin exist already, so filtering the types, etc can happen now when also hooking into said hook.
=> #612 - move `graphql_register_types` to the end of TypeRegistry::init()

tests/wpunit/PostObjectConnectionQueriesTest.php
Adds a test to make sure the global post object is set correctly
#576
…
OSX …
=> fixes #576 test for global post object being set correctly

src/Router.php, src/Type/Enum/PostTypeEnum.php, src/Type/Enum/TaxonomyEnum.php, src/Type/Object/PostObject.php, src/TypeRegistry.php, tests/wpunit/TypesTest.php
- Router.php add the $debug flag to FormattedError::createFromException() so errors are returned with a valuable message other than just "internal server error" when GRAPHQL_DEBUG is true (can't believe how long this has been broken. . .)
- Add some more helpful InvariantViolation exceptions in TypeRegistry.php when fields/types aren't registered properly
- Fix a bug with how the fields were being registered to MediaItems numerous times
- Add some tests to make sure the Exceptions are being thrown as expected when fields are registered poorly
-----
Closes #619
=> #619 - Throw Better Exceptions in TypeRegistry

src/Data/MenuItemConnectionResolver.php, tests/wpunit/MenuItemConnectionQueriesTest.php
Ordering by menu item is unnecessary; we already have the order we want in `post__in`, so we should use that order.
I originally thought I had an edge case that would produce results in the wrong order, but I can't reproduce in tests. This change is now just a minor optimization.
=> Order menu items by post__in instead of menu_order.

src/Request.php
If we don't pass them, the Server attempts to reparse them from the request body. This means that HTTP request data could not be filtered with `graphql_request_data`.
=> Pass the operation params to the executeRequest call (fixes #643).

src/Request.php, src/Server/WPHelper.php
This new action makes it possible to adjust the `ServerConfig` before the request is executed. So, for example, if I wanted to add some custom validation rules, I could call a method on the ServerConfig instance via this action, e.g.:
```
add_action( 'graphql_server_config', function( $config ) use ( $rules ) {
$config->setValidationRules( $rules );
}, 10, 1 );
```
I don't strictly need this to implement persisted queries, but it is one avenue for implementation.
This also clean up some comments in the Request/WPHelper classes.
=> Provide graphql_server_config action to allow customization of ServerConfig.

src/Server/WPHelper.php
This isset check exists to make sure we don't clobber an existing `queryId`. A typo was preventing it from checking properly.
=> Typo in isset check for existing queryId.

src/Mutation/CommentCreate.php, src/Mutation/CommentDelete.php, src/Mutation/CommentRestore.php, src/Mutation/CommentUpdate.php, src/Mutation/MediaItemCreate.php, src/Mutation/MediaItemDelete.php, src/Mutation/MediaItemUpdate.php, src/Mutation/PostObjectCreate.php, src/Mutation/PostObjectDelete.php, src/Mutation/PostObjectUpdate.php, src/Mutation/ResetUserPassword.php, src/Mutation/TermObjectCreate.php, src/Mutation/TermObjectDelete.php, src/Mutation/TermObjectUpdate.php, src/Mutation/UpdateSettings.php, src/Mutation/UserCreate.php, src/Mutation/UserDelete.php, src/Mutation/UserRegister.php, src/Mutation/UserUpdate.php
Creates public functions for each mutation class's configuration of input, output and mutation. I wanted to mutate a CPT with custom fields while retaining all the base fields from `PostTypeCreate`. I went through and refactored all mutations (except password recovery email, seemed superfluous) to be consistent.
#611 
Any relevant logs, error output, GraphiQL screenshots, …
=> #611 update mutation config

src/Request.php
This fixes a bug with `after_execute_actions` throwing PHP warnings that was causing problems when WP_DEBUG_DISPLAY is turned on.
Closes #657
=> 🐛 FIX: Fixes PHP warnings in the Request class

src/Connection/Comments.php, src/Connection/MenuItems.php, src/Connection/Menus.php, src/Connection/Plugins.php, src/Connection/PostObjects.php, src/Connection/TermObjects.php, src/Connection/Themes.php, src/Connection/UserRoles.php, src/Connection/Users.php
This makes connection methods public for easier re-use when extending and creating custom connections
closes #668 
Now, when registering custom connections, one could do somethign like: 
```
register_graphql_connection([
'fromType' => 'RootQuery',
'toType' => 'AudioUnion',
'fromFieldName' => 'audio',
'connectionArgs' => \WPGraphQL\Connection\PostObjects::get_connection_args(),
'resolve' => function( $root, $args, $context, $info ) {
return \WPGraphQL\Data\DataSource::resolve_post_objects_connection( $root, $args, $context, $info, null );
}
]);
```
Note the use of …
=> 👌 IMPROVE: make connection methods public

src/Server/WPHelper.php, tests/functional/BasicPostListCept.php
Adding variables to a `GET` request results in an error from `graphql-php`, e.g.:
```
GraphQL Request parameter "variables" must be object or JSON string parse
d to object, but got "{\\"foo\\":\\"bar \\"}"
```
This is because WordPress adds slashes to superglobals for safety reasons (`wp_magic_quotes`):
https://github.com/WordPress/WordPress/blob/92c3c46abe9f3b9e27764cbd483204530e8c1c2a/wp-includes/load.php#L761-L763
I had accounted for this and was stripping slashes on the `extensions` parameter, but didn't realize the same issue existed for `variables` and all other `GET` parameters. This PR applies `wp_unslash` to all `GET` query variables.
Even though WordPress also escapes …
=>  Apply wp_unslash to query (GET) variables to undo wp_magic_quotes

src/Router.php
Adds a `Access-Control-Max-Age` header so that preflight (`OPTIONS`) responses can be cached by the browser. Currently, when the GraphQL server is on a different hostname, the browser must send a preflight request and wait for a response before every single request:
While a user could implement this herself by filtering `graphql_response_headers_to_send`, this seems like a reasonable default (that the user can still override if they want).
The value of `600` was chosen since it is the maximum value that Chromium supports (anything higher is rounded down):
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age
=> Add Access-Control-Max-Age header to cache preflight responses.

src/Type/Object/RootQuery.php
Fixes https://github.com/wp-graphql/wp-graphql/issues/691
The case in which `graphql_single_name` and `graphql_plural_name` are spelt is now consistent between the check in the `RootQuery` and the created field in the `TypeRegistry`'s `prepare_field` function
https://github.com/wp-graphql/wp-graphql/issues/691
Nothing more than what I posted in the issue
Awesome project, thank you for all the work you put into it! …
=> apply lcfirst when generating custom post type id field

.travis.yml, Dockerfile.test-base, Dockerfile.xdebug, README.md, docker/docker-compose.local-app.yml, docker/docker-compose.tests.yml
- [x ] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [ x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!
- Adding support for WP 5.0.3 + PHP 7.3  tests.
- Updating PHP Composer version
Please note: Use of PHP 7.3 requires use of `xdebug-2.7.0RC2` which seems to work for code …
=> Issue 624, CI-6146 | Running tests with WP 5.0.3 + PHP 7.3; Updating PHP composer

src/Server/WPHelper.php, tests/wpunit/WPHelperTest.php
Fixes #707
Avoids executing `graphql_request_data` filter twice on GET requests.
graphql-php uses only the query params on GET requets so executing the filter only for the query params on GET requests should be ok:
https://github.com/webonyx/graphql-php/blob/616fc10837c73f0a333c38f8aefa285cf70c5717/src/Server/Helper.php#L123
Added a second param to the filter so the users can access the query params on POST requests too if needed.
https://github.com/wp-graphql/wp-graphql/issues/707
Ubuntu Bionci, the Docker test env …
=> Do not execute graphql_request_data twice for GET requests

src/Data/DataSource.php, src/Type/Enum/MenuLocationEnum.php
Makes menu locations without assigned menus visible to `MenuLocationEnum`. Relies on `$_wp_registered_nav_menus` global, instead of `get_nav_menu_locations()`.
No …
=> MenuLocationEnum fix

src/Data/DataSource.php, src/Request.php, src/Utils/InstrumentSchema.php, tests/wpunit/PostObjectConnectionQueriesTest.php, tests/wpunit/PostObjectQueriesTest.php
We noticed that the "Excerpt is always of the first post" (#503) issue has regressed and it was not caught by tests because the test added in #625 does not properly test the usage of the global post.
It does not use it because the `get_the_excerpt` filter uses the `wp_trim_excerpt` function by default and if a pre-existing excerpt is passed it just returns it:
https://github.com/WordPress/WordPress/blob/cddee8b72e59c9968b1c786c01992dae6f71ee13/wp-includes/formatting.php#L3685-L3686
Setting the `post_excerpt` string to an empty string causes `wp_trim_excerpt` to call `get_the_content( '' );` and thus the test fails.
I don't know how this should be really fixed but adding this to the `excerpt` resolver makes it pass again:
https://github.com/epeli/wp-graphql/commit/d174a6c41f82dbdbee4fcaaa81 …
=> Setup postdata on field levels

src/Data/MenuItemConnectionResolver.php
Adds two filters for menu items connection resolvers
A `graphql_menu_item_connection_args` which can be used to filter the args passed to the `menuItems` query before the `$query_args` is generated.
A `graphql_menu_item_connection_query_args` which can be used to modify the `$query_args` once the wpgraphql logic is executed.
In the [wp-graphql-polylang](https://github.com/valu-digital/wp-graphql-polylang) were aiming to add a `language` where arg to all translatable items and with menus I was not able to find any way to modify the menu query based on the input args.
Eg. we want to be able to write
```graphql
{
menuItems(where: {language: EN, location: TOP_MENU}) {
nodes {
label
}
}
}
```
Polylang handles menu translations by dynamically generating translated versions of the menu …
=> Add arg filters for menu items

src/Type/Enum/TimezoneEnum.php, src/TypeRegistry.php
This adds the Type definition, but doesn't define any field to use it yet. . .this is to support the Settings Patch and get the settings all in "proper" order
Closes #675
=> ✨ Add TimezoneEnum Type

src/Data/PostObjectConnectionResolver.php
fixes #732 
for now the implementation is so that if the `graphql_cursor_offset` is not 0, the query_var `ignore_sticky_posts` is set. This should be pretty similar to what WordPress core does where the value of `page` is checked and if it is any different from 1, sticky posts are ignored. I thought that calculating the page and then injecting that into the query_vars could lead to strange pagination side effects.
**Operating System:** Windows 10, Docker
**WordPress Version:** 5.1.1
=> Fix for Sticky posts being repeated on every page

src/Data/Connection/UserConnectionResolver.php, src/Data/Loader/PostObjectLoader.php, tests/wpunit/ModelUserTest.php, tests/wpunit/UserObjectQueriesTest.php
- This PR tightens access to users by limiting the UserConnectionResolver to querying for users where `"has_published_posts" => true` if the request is not authenticated.
closes #734
=> #734 - Tightening User Access

src/Mutation/UserRegister.php
This removes roles from allowed input in the registerUser mutation, and also unsets role when the mutation calls wp_update_user, so even plugins that filter in a role input can't save a role during this particular mutation.
=> 🐛 FIX ISSUE WITH ROLE BEING SET DURING REGISTER USER MUTATIONS

src/Data/CommentMutation.php, src/Mutation/CommentCreate.php, tests/wpunit/CommentMutationsTest.php
…
#740 
I also changed the `postId` input to `commentOn` as was discussed in the issue.
**Operating …
=> Bug/740 - don't allow non-logged in users to comment if flag is set

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Type/Object/Avatar.php, src/Type/Object/Comment.php, src/Type/Object/CommentAuthor.php, src/Type/Object/Menu.php, src/Type/Object/MenuItem.php, src/Type/Object/Plugin.php, src/Type/Object/PostType.php, src/Type/Object/Taxonomy.php, src/Type/Object/TermObject.php, src/Type/Object/Theme.php, src/Type/Object/User.php, src/Type/Object/UserRole.php, tests/wpunit/UserObjectQueriesTest.php
- This adds `isRestricted: Boolean` fields to the various ObjectTypes that have an associated model. This allows for queries to know whether a node isRestricted or not. This gives client some insight into whether there is actually no data for a particular field, or whether there's no data returned because it's restricted.
I think there's room to expand this further down the road so the client can have even more info on what fields are public/restricted, etc. Could help build UIs properly if the consumer knows that x field is null because it's listed as a restricted field, vs it's null because there is simply no underlying data.
- This also fixes a bug with the …
=> #375 - Return visibility (isRestricted) on nodes

src/TypeRegistry.php
=> #797 - TypeRegistry::get_type() returns php warning if Type doesn't exist

wp-graphql.php
This configures post_types and taxonomies to "show_in_graphql" so that even outside of GraphQL Requests that knowledge can be used.
For example, a plugin author may want to do something like: 
```
get_post_types([ 'show_in_graphql' => true ]);
```
Currently that would be null, because we only register types at init_graphql_request, and _most_ plugins will be executing code outside the context of a GraphQL request. 
This allows plugins and themes to get a list of Post Types and Taxonomies that are configured to Show in GraphQL, even outside the context of a GraphQL request
closes #799
=> #799 - hook "setup_types" to init

src/Connection/Menus.php, tests/wpunit/MenuItemConnectionQueriesTest.php
🐛  BUGFIX: 
#805 - Fix {menuItems{ nodes { ... } } queries and include a test to reduce future regressions
----
In v0.3.0 some changes were made to connections causing resolution of nodes to happen a bit differently. The `menuItems` connection wasn't appropriately adjusted to compensate for said changes. 
This updates the menuItem connections and includes a test to reduce risk of future regressions. 
---
Closes #805
=> 🐛 #805 - BUGFIX for `menuItems{ nodes { ... } }` breaking

src/Connection/Menus.php, src/TypeRegistry.php, tests/wpunit/MenuItemConnectionQueriesTest.php, wp-graphql.php
- #799 WPGraphQL sets core Post Types and Taxonomies to `show_in_graphql` during `init` instead of `init_graphql_request` now. This allows for `get_post_types( [ 'show_in_graphql' => true ])` to work even outside the context of a GraphQL request. This is especially helpful for tools that want to know what Post Types and Taxonomies are set to `show_in_graphql`.
- #806 resolved. Querying "nodes" on `menuItems` was introduced as a regression during the v0.3.0 release. Thanks, @JosephCarrington for reporting and working through to confirm it's resolution.
- #797 resolved. The TypeRegistry was throwing some PHP warnings if `TypeRegistry::get_type()` was used for a not-yet registered Type.
- #803 Fixes a bug introduced by #799 🤦‍♂️. Thanks @benallfree for working through this with me to get it …
=> 🚀 Release/v0.3.2

src/TypeRegistry.php
Previously this expected the value of the `list_of` and `non_null` fields to be a string of the name of the Type, like `non_null => ID` or `non_null => String` or whatever.
If an array was passed as the value, things got weird.
This now allows for a String of a Type name to be passed through _or_ an array, which will then circle back to setup non_null / list_of again.
----
closes #849
=> #849 - This ensures that list_of and non_null can be used with each other

src/TypeRegistry.php, wp-graphql.php
Reverts wp-graphql/wp-graphql#847
There seems to be some further underlying changes needed to make this work as intended.
I'm reverting this so we can continue addressing outside of `develop`
=> Revert "Adds clear_schema"

src/TypeRegistry.php
Closes #802 
If a field is configured with a `list_of` or `non_null` and the Type being wrapped is invalid, this will now throw an exception to better communicate why the Schema is not valid
For example:
```
add_action( 'graphql_register_types', function() {
register_graphql_field( 'RootQuery', 'testField', [
'type' => [ 'list_of' => 'NonExistentType' ]
] );
} );
```
Will now return:
```
{
"errors": [
{
"debugMessage": "The list_of type NonExistentType is an invalid or non-existent type",
"message": "Internal server error",
"category": "internal"
}
]
}
```
=> #802 - Throw exception for invalid list_of / non_null Types

src/Model/Post.php, src/Type/Object/PostObject.php, tests/wpunit/MediaItemQueriesTest.php
Closes #796  
This adds the ability to query `srcSet` on media items. 
For example, on my local environment I can run this query:
```
{
mediaItem(id: "YXR0YWNobWVudDoxNTI4") {
id
title
srcSet
}
}
```
and get this response: 
```
{
"data": {
"mediaItem": {
"id": "YXR0YWNobWVudDoxNTI4",
"title": "download",
"srcSet": "https://dashboardwpgraphql.local/wp-content/uploads/2019/04/download-239x300.jpeg 239w, https://dashboardwpgraphql.local/wp-content/uploads/2019/04/download.jpeg 430w"
}
}
}
```
=> #796 - Add srcSet field to media items

.travis.yml, Dockerfile.test-base, README.md, docker/docker-compose.local-app-xdebug.yml, docker/docker-compose.local-app.yml, docker/docker-compose.tests.yml, list-mysql-containers.sh
- [x ] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [ x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!
* This change ensures the Docker build installs PHP libraries according to `composer.lock`. This will fix https://github.com/wp-graphql/wp-graphql/issues/859
* Travis runs …
=> Issue-859/CI-6320 | Fixing Docker tests; Updating Docker software versions

src/Data/Cursor/PostObjectCursor.php, tests/wpunit/PostObjectCursorTest.php
The docker test environment is broken for me so I'm sending this as a PR now to see how the tests execute.
I have following posts
and I execute this query for the second page
```graphql
{
posts(first: 5, after: "YXJyYXljb25uZWN0aW9uOjI4", where: {orderby: {field: TITLE, order: ASC}}) {
pageInfo {
endCursor
}
edges {
node {
title
content
}
}
}
}
```
Before this PR it returns this
which is wrong. The generated SQL query is 
```sql
SELECT wp_posts.ID
FROM wp_posts
WHERE 1 = 1
AND wp_posts.post_parent = 0
AND wp_posts.post_type = 'post'
AND ((wp_posts.post_status = 'publish'))
AND CAST(wp_posts.post_date AS DATETIME) <= CAST('2019-05-23 06:04:47' AS DATETIME)
AND (
CAST(wp_posts.post_date …
```
=> Fix orderby with post object cursors

src/WPSchema.php
_PHPStorm complains that the $schema->config[] variable is private at https://github.com/wp-graphql/wp-graphql/blob/develop/src/Utils/InstrumentSchema.php#L53_
_The warning is caused by the IDE assuming a connection to the webonyx/Type/Schema->config[] rather than the explicitly defined \WPGraphQL\WPSchema object_. 
_The misconnection was due to the config variable not being created in WPSchema._ 
_I added the definition and the constructor's instantiation …
=> Create WPSchema config variable

.travis.yml, Dockerfile.test-base, README.md, docker/docker-compose.local-app-xdebug.yml, docker/docker-compose.local-app.yml, docker/docker-compose.tests.yml
* Updating Travis and Docker to run with WP 5.2.2 + MariaDB 10.2.25
* Updating PHP COmposer version used in Docker
N/A
N/A
N/A
**Operating System:** 
OS X Mojave
5.2.2
=> CI-6718 | updating software used by Docker

src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Cursor/PostObjectCursor.php, tests/wpunit/PostObjectConnectionQueriesTest.php, tests/wpunit/PostObjectSearchTest.php
WP_Query applies default ordering by title when the "s" arg is passed to it, which was causing funky issues with WPGraphQL Cursor Pagination.
This sets the `search_orderby_title` to false, and defaults to orderby date. Custom orderby options can be passed to the connection as well.
#897 
To test, I created 4 posts with the word "floof" as the content. 
In the admin, you can see a search for "floof" shows posts: `Four, Three, Two, One"
Here, I query for the `last: 2` items, and as expected, we get Posts …
=> #897 - Cursor pagination does not preserve order with the "search" where arg

src/Data/Connection/UserConnectionResolver.php, tests/wpunit/UserObjectQueriesTest.php
Public requests shouldn't be able to filter users by role. This ensures that if the users connection is filtered 
Before this, an unauthenticated user could make a request like the following:
```
query getUsers{
users(where:{role:ADMINISTRATOR}){
edges{
node{
userId
name
}
}
}
}
```
Get a response like: 
```
{
"data": {
"users": {
"edges": [
{
"node": {
"userId": 1,
"name": "root"
}
}
]
}
}
}
```
And the requestor would be able to determine which users are admins.
With this fix, the same request could be sent and the following response would be provided:
```
{
"errors": [
{
"message": "Sorry, you are not allowed to filter users by role.",
"category": "user",
"locations": [
{
"line": 2, …
```
=> #890 - Prevent filtering users by role if requestor doesn't have "list_users" capability

Dockerfile.test-base
mysql-client has been renamed to mariadb-client
Fix the `run-docker-test-environment.sh` script error with
```
Package mysql-client is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```
=> Fix docker test env

src/Connection/Users.php
It appears that the descriptions for users include and exclude were copied from comments.  This updates them to be more clear as to what these arguments do.
=> Correct users include/exclude descriptions

src/Connection/Comments.php
I was writing unit tests for CommentsQueryConnection and noticed an incorrect enum for contentType field in Comments Connection schema. This PR fixes it.
No issue opened …
=> Fix incorrect enum for contentType field in Comments Connection schema

Dockerfile.test-base, docker/docker-compose.local-app.yml, docker/docker-compose.tests.yml
- updating PHP composer version used in Docker image
- updating MariaDB version used by Docker Compose
N/A
N/A
N/A
**Operating System:** OS X Mojave
**WordPress Version:** 5.2.2
=> CI-6732 | updating php composer and mariadb Docker versions

src/Request.php
This adds a check for authentication errors prior to execution of the request. 
If there are no authentication errors, execution proceeds as normal. If there are authentication errors, a 403 is returned and execution is prevented.
fixes #935 
also related: https://github.com/wp-graphql/wp-graphql-jwt-authentication/issues/38
=> #935 - Check for authentication errors prior to execution.

.travis.yml, Dockerfile.test-base, docker/docker-compose.local-app-xdebug.yml, docker/docker-compose.local-app.yml, docker/docker-compose.tests.yml
Updates Wordpress, MySQL, and PHP Composer versions used by Docker configuration
No
N/A
N/A
OS X Mojave 10.14.6
5.2.3
=> CI-6875 | updating Wordpress, MySQL, and PHP Composer Docker versions

.travis.yml, Dockerfile.test-base, docker/docker-compose.local-app-xdebug.yml, docker/docker-compose.local-app.yml, docker/docker-compose.tests.yml
Reverts wp-graphql/wp-graphql#963
Travis builds are failing. Seems like it _could_ be related to this?
=> Revert "CI-6875 | updating Wordpress, MySQL, and PHP Composer Docker versions"

src/Data/Loader/PostObjectLoader.php
This removes the error that's thrown in the PostObjectLoader. There are valid cases for a Post to _not_ be returned from the loader when a key is provided
closes #982
=> #982 - Remove error that's thrown in the PostObjectLoader

src/Router.php
For wp-graphql-polylang I need to detect whether the current http request is a graphql request really early. Right when Polylang initializes. `GRAPHQL_HTTP_REQUEST` constant it not yet defined at this point.
Here's what I currently do
https://github.com/valu-digital/wp-graphql-polylang/blob/bfddbc2d63aaf9e89ac7a254344faa8850609dbc/wp-graphql-polylang.php#L112-L120
but that's very brittle.
`Router::is_graphql_request()` would help a lot.
=> Expose Router::is_graphql_request()

docs/src/gatsby-theme-apollo-core/components/sidebar-nav/index.js, docs/src/gatsby-theme-apollo-docs/components/section-nav.js
This adds an active style to the left and right sidebar navs in the docs.
The active color is subtle, but to me it looks differentiated enough. We can add more contrast if this isn't enough.
=> fix: shadow the sidebar-nav to change the active anchor link color

src/Data/Connection/AbstractConnectionResolver.php, tests/wpunit/PostObjectQueriesTest.php
Makes sure we don't return all terms on taxonomy connections to private posts.
closes #992 
It's definitely debatable that this short circuit code is in the …
=> Fix issue with model layer returning connected items on private posts

src/Data/Connection/AbstractConnectionResolver.php
This adjusts the logic for `should_execute` so the Abstract class can declare false and trump the extending class to centrally configure rules that should prevent execution, and expedite resolution.
---- 
Follow up to #993 by @CodeProKid and closes #992
=> #992 - follow-up. 

src/Type/InterfaceType/Node.php, src/Type/Object/Comment.php, src/Type/Object/CommentAuthor.php, src/Type/Object/Menu.php, src/Type/Object/MenuItem.php, src/Type/Object/Plugin.php, src/Type/Object/PostObject.php, src/Type/Object/PostType.php, src/Type/Object/Taxonomy.php, src/Type/Object/TermObject.php, src/Type/Object/Theme.php, src/Type/Object/User.php, src/Type/Object/UserRole.php, src/Type/WPInterfaceType.php, src/Type/WPObjectType.php, tests/wpunit/MenuItemQueriesTest.php, wp-graphql.php
- Creates a `graphql_interface_{$type_name}_fields` filter that is provided the WPInterface fields after all field registration has be completed.
- The `graphql_interface_{$type_name}_fields` filter is hooked into by any inheriting types and the WPInterface's fields are retrieved and merge with the inheriting types fields.
- The WPInterface's fields configs are overwrite by any existing field configs on the inheriting type.
- This allow the forgoing of any …
=> interface field hook implemented

src/Model/Post.php, src/Type/Object/PostObject.php
Adds the `isFrontPage` field to pages to tell if set to homepage on the site
#1028 - Adding `isFrontPage` boolean to Pages data #5
It is breaking with a query like this
```
query MyQuery {
menus {
nodes {
menuItems {
nodes {
connectedObject {
... on Page {
id
title
isFrontPage
}
}
}
}
}
}
pages {
nodes {
id
title
isFrontPage
}
}
}
```
=> Adding isFrontPage field to Pages

src/Type/WPObjectType.php
#1032 - Support backward compatible Interface registration for extensions that may have registered and used interfaces before interface inheritance was added
Closes #1032
=> (bug) Support back compat interface implementations

src/Registry/TypeRegistry.php, src/Type/WPInputObjectType.php, src/Type/WPObjectType.php, tests/wpunit/AccessFunctionsTest.php
This passes the `$type_registry` to the `graphql_input_fields` filter, allowing for extensions using that filter to have access to the Type Registry
closes #1037 
closes https://github.com/wp-graphql/wp-graphql-meta-query/issues/8
=> #1037 - Fixes conflict with WPGraphQL Tax Query

wp-graphql.php
WPGraphQL calls `WPGraphQL::get_allowed_types()` at `init`, and if a Post Type or Taxonomy registered to "show_in_graphql" doesn't contain a single or plural name, this throws an exception. 
WPGraphQL has no business throwing exceptions on the `init` hook if a Post Type or Taxonomy doesn't have a graphql single or plural name. 
------------------------------------------ 
closes: https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/issues/9
closes: https://github.com/wp-graphql/wp-graphql/issues/1043
=> #1043 - Don't call for allowed_types at the init hook

src/Data/DataSource.php, src/Model/UserRole.php, src/Type/Object/UserRole.php, tests/wpunit/UserRoleConnectionQueriesTest.php
This adds a new `displayName` field to the `UserRole` type and updates the `name` field description to say that the `name` is the registered name, and `displayName` is the UI friendly name.
closes #1050 
=> #1050 - Add display name to the User Role type and update description of the "name" field

access-functions.php, tests/wpunit/TypesTest.php, wp-graphql.php
This pull request updates the `access-functions.php` file to register types earlier in the Schema generation lifecycle, allowing for the TypeRegistry->get_types() method to properly return all registered Types
This adds tests to ensure get_types() method works properly.
closes #1052 reported by @kellenmace
=> #1053 - TypeRegistry->get_types() not available within the `graphql_register_types` action

src/Type/Object/RootQuery.php, tests/wpunit/PostObjectQueriesTest.php
This updates the `{$postType}By` entry points to return null instead of throwing an error when a Post cannot be found. 
This makes it more consistent with other singe entry points in the Schema. 
There might be future follow-up as it seems like many APIs do indeed throw errors when individual resources cannot be found. See #1059 for more context on the discussion.
closes #1059
=> #1059 - postBy entry throws error if post can't be found

src/Router.php
This PR fixes two issues with `is_graphql_http_request()`:
1. It did not work if the hostname had port in it because `esc_url_raw()` does not work with ports:
```
esc_url_raw("localhost/graphql")
"http://localhost/graphql"
esc_url_raw("localhost:8080/graphql")
""
```
`esc_url_raw()` is used for sanitization for db usage but here we only use it in PHP code to detect whether the URL ends with a given string. No need to use it here so it can be safely omitted.
2. Usage with wp-graphiql. wp-graphql sends graphql requests to `/index.php?graphql`. I guess that is so it can work without proper url permastructure setup. Anyway `is_graphql_http_request()` should support that too. The "after …
=> HTTP request detection fixes

tests/wpunit/IsGraphqlHttpRequestTest.php
You merged my PR too quickly 😂  
Anyway here's some very basic tests for `is_graphql_http_request()`. Codeception seem to automatically clear the `$_SERVER` and `$_GET` variables between the tests so it is safe to modify them like this.
=> Add simple tests for `is_graphql_http_request()`

src/Request.php
We only need to check for authentication errors for graphql http requests. We don't need to for regular internal requests using graphql() function in Page templates, etc.
-----------------------------------------
Closes #964 
Screenshots
-----------------------------------------
=> #964 - grapqhl() function breaks when used in page templates

src/Router.php
I've started to see a common trend in headless WordPress site where the `Site Address` is changed to the located of the front-end application. `home_url()` retrieve `Site Address` causing `Router::is_graphql_http_request()`  to return false incorrectly. `get_site_url()` retrieve the `WordPress Address`, the url at which the WordPress installation lives.
…
Any relevant …
=> "home_url" to "get_site_url"

docs/package.json, docs/src/components/GraphiQL/index.js, docs/yarn.lock
There's a bug with the GraphiQL component on the docs site not rendering responses properly if extensions aren't passed from the WPGraphQL server. Extensions are not always included in the response, so this PR updates how the GraphiQL component works when extensions are not returned from the server.
=> #1071 - User Pagination not working in docs

docs/src/components/GraphiQL/style.css
This updates the z-index for the GraphiQL component in the Docs to make sure it doesn't overlap the search header.
closes #1063
=> #1063 - Z-Index issue for GraphiQL in Docs

docs/source/getting-started/install-and-activate.mdx
This PR addresses #1080 to clarify the documentation with respect to site/wordpress url mismatches.
It would close #1080
=> update to docs to handle issue with site/wordpress url mismatch

src/Registry/TypeRegistry.php, src/Type/WPObjectType.php, tests/wpunit/TypesTest.php
This adds `list_of` and `non_null` methods to the TypeRegistry allowing for filters of GraphQL Type fields to be able to filter in non_null and list_of types.
Now you can do something like: 
```
add_filter( 'graphql_user_fields', function( $fields, $object, \WPGraphQL\Registry\TypeRegistry $type_registry ) {
$fields['testNonNullString'] = [
'type' => $type_registry->non_null( $type_registry->get_type( 'String' ) ),
'resolve' => function() {
return 'string';
}
];
return $fields;
}, 10, 3 );
```
Then be able to query like: 
```
query GET_USER( $id: ID! ) {
user(id:$id) {
id
testNonNullString
}
}
``` …
=> #1088 - Add list_of and non_null methods to TypeRegistry

docs/source/guides/debugging.mdx, wp-graphql.php
If WPGraphQL is active on a server running a PHP version lower than required, currently it's difficult to understand why there are errors in the GraphQL resolution. 
This adds a check at the start of GraphQL execution to make sure the PHP version of the server meets the requirements for WPGraphQL, otherwise an Exception is thrown and further execution is prevented. 
- Introduce a GRAPHQL_MIN_PHP_VERSION constant (7.0, default)
- add a check at the `do_graphql_request` hook to check the php version and throw an exception when the PHP version is lower than the required version
- update debugging docs about `Internal Server Error` messages and enabling `GRAPHQL_DEBUG`
Does this close any …
=> #1096 - Throw Exception when PHP version is lower than the required PHP version

.travis.yml, docker/docker-compose.local-app-xdebug.yml, docker/docker-compose.local-app.yml, docker/docker-compose.tests.yml, src/Data/Connection/UserRoleConnectionResolver.php, src/Model/Post.php, src/Type/Object/PostObject.php, tests/wpunit/ModelUserTest.php, tests/wpunit/PostObjectQueriesTest.php, tests/wpunit/UserObjectQueriesTest.php
This updates Travis to test on PHP 7.4 and updates the WordPress versions to the latest. 
This also addresses the issues that were surfaced by testing in PHP 7.4 and WP 5.3.2
=> #1101 - Updating Travis to test on PHP 7.4

docs/source/extending/connections.mdx
=> remove double slashes from documentation

docs/source/getting-started/custom-fields-and-meta.mdx
In a piece of documentation markdown:
"speficying" -> "specifying"
=> Fix Typo in Custom Field Docs

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/CommentConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php, src/Data/Connection/UserConnectionResolver.php, src/Data/Connection/UserRoleConnectionResolver.php, tests/wpunit/CommentConnectionQueriesTest.php, tests/wpunit/PostObjectConnectionQueriesTest.php, tests/wpunit/PostObjectSearchTest.php, tests/wpunit/TermObjectConnectionQueriesTest.php, tests/wpunit/UserObjectCursorTest.php
If you query with `after` arg, `hasPreviousPage` will always return `false`. Similarly, if you query with `before` arg, `hasNextPage` will always return false. This PR fixes this for all connections supporting pagination.
#594 
`hasNextPage`/`hasPreviousPage` will always return false if you query `userRoles` with `before`/`after` …
=> Fix for hasNextPage/hasPreviousPage not fully respecting Relay spec

src/Data/Connection/PostObjectConnectionResolver.php, src/Type/Input/PostObjectsConnectionOrderbyInput.php
When submitting a query for PostObjectConnection and using `orderby.field` input, but not `orderby.order` input, there is an undefined index warning causing issues. This sets the `order` field to be a `nonNull` input, so users _must_ submit a value. This also sets a default in the resolver should resolution somehow get to this point without an order being set. (the nonNull should prevent this in _most_ cases).
Breaking Change
This is a breaking change because it changes a previously nullable input to a nonNull input. 
closes #1120 
@drewbaker would you mind …
=> #1120 - undefined index when not setting the order field for orderby

wp-graphql.php
Adds support for [GitHub Updater](https://github.com/afragen/github-updater) by adding `GitHub Plugin URI` option. 
A lot of use GitHub Updater to update/manage plugins, I hope this would make it easier of anyone to keep the plugin up to date.
…
Ubuntu 18.04 
5.3.2
=> Adding support for GitHub Updater

package.json, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/UserConnectionResolver.php, src/Data/NodeResolver.php, src/Registry/TypeRegistry.php, src/Type/Enum/ContentNodeIdTypeEnum.php, src/Type/Enum/UserNodeIdTypeEnum.php, src/Type/InterfaceType/ContentNode.php, src/Type/InterfaceType/ContentTemplate.php, src/Type/InterfaceType/HierarchicalContentNode.php, src/Type/InterfaceType/NodeWithAuthor.php, src/Type/InterfaceType/NodeWithComments.php, src/Type/InterfaceType/NodeWithContentEditor.php, src/Type/InterfaceType/NodeWithExcerpt.php, src/Type/InterfaceType/NodeWithFeaturedImage.php, src/Type/InterfaceType/NodeWithPageAttributes.php, src/Type/InterfaceType/NodeWithRevisions.php, src/Type/InterfaceType/NodeWithTitle.php, src/Type/InterfaceType/NodeWithTrackbacks.php, src/Type/InterfaceType/UniformResourceIdentifiable.php, src/Type/Object/PostObject.php, src/Type/Object/RootQuery.php, src/Type/Object/SettingGroup.php, src/Type/Object/Settings.php, src/Type/Object/User.php, src/Type/Union/ContentTemplateUnion.php
The `menuOrder` field was missing after the v0.6.0 release. This is because the menuOrder field was moved to the `NodeWithPageAttributes` Interface and applied only to Post Types that support page attributes. However, the `NodeWithPageAttributes` Interface was never added to the TypeRegistry, so it was not getting applied. 
This adds the NodeWithPageAttributes Interface to the TypeRegistry. 
This also corrects some formatting issues missed in the v0.6.0 release
closes #1129
=> #1129 - Register the NodeWithPageAttributes Interface

src/Model/Model.php
If the Model has already processed a field, and it's a scalar, array or non-callable object, return it. Otherwise call the function to process and cache the field for next run.	
closes #1144 
**Before**
**After**
**Before**
**After**
=> #1144 - Prevent model layer from attempting to execute cached values

src/Connection/PostObjects.php
**BREAKING:** This sets a name for the core Revision connections to Post Types. Otherwise users cannot add their own connection args to unnamed connections. Any connection args fail silently.
#1148 
(If it’s long, please paste to https://ghostbin.com/ and insert the link …
=> Specify post to revision connection name to prevent clashes with unnamed user connections

src/Data/CommentMutation.php, src/Mutation/CommentDelete.php, src/Mutation/CommentUpdate.php
This adjusts the cap check for comment update & delete mutations to make sure that the requestor is authenticated, and is either the comment author, or a user with moderate_comments permissions. This also ensures non-authenticated requestors cannot delete comments with comment author ID of 0.
Closes #1186
=> #1186 - Comment Mutation cap check adjustment

src/Data/Connection/PostObjectConnectionResolver.php
This re-arranges how the order inputs are calculated. This allows for custom orderby paramaters to be input for search queries, but still sets sane defaults for search queries where no orderby input is added to the connection.
closes #1190
=> #1190 - orderby for search queries not working

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/CommentConnectionResolver.php, src/Data/Connection/MenuConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php, src/Data/Connection/UserConnectionResolver.php, src/Data/Loader/AbstractDataLoader.php
Adds a `get` function to the `AbstractDataLoader` class. This function is for the purpose of retrieving object cached by the loader, but loads the object on spot if not found in the cache.
```
public function get( $key ) {
if ( ! empty( $this->cached[ $key ] ) ) {
return $this->cached[ $key ];
} else {
return $this->load( $key );
}
}
```
`AbstractConnectionResolver::get_node_by_id()` is no longer abstract.
```
public function get_node_by_id( $id ) {
return …
```
=> AbstractDataLoader::get() added.

README.md, src/Model/Post.php, src/Model/User.php, src/Type/Object/TermObject.php, tests/wpunit/ContentNodeInterfaceTest.php, tests/wpunit/PostObjectQueriesTest.php, tests/wpunit/PostTypeObjectQueriesTest.php, tests/wpunit/UserObjectQueriesTest.php
This adds a leading slash to the uri field to make uri fields absolute paths rather than relative.
https://github.com/wp-graphql/wp-graphql/issues/1206
=> add leading slashes to uri field resolvers

docs/source/extensions/wpgraphql-insights.mdx
The link in the `wpgraphql-insights.mdx` docs had a link that was not formatted correctly thus not showing up correctly.
No
Viewed in Github
Original:
Fixed:
=> fix: url in wpgraphql-insights doc

src/Type/Object/RootQuery.php
This PR adds Object Single name and description to the documents in GraphiQL IDE for exposed data. See the screenshots.
Closes: #1204 
**Before:**
**After:**
**Operating System:** … Linux
**WordPress Version:** … 5.3.2
=> Add description for Post Types and Taxonomies added to the Schema

src/Mutation/UserDelete.php
Passing the user ID to the `current_user_can` function in the `deleteUser` mutation so that extensions and plugins can properly extend it.
More background information here: #143
=> Delete User Mutation

src/Mutation/UserDelete.php
Requires `wp-admin/includes/ms.php` file before attempting to call the `wpmu_delete_user()` function in multisite to prevent an internal server error.
Closes #1228 
n/a
n/a
**Operating System:** macOS
**WordPress Version:** March 31, 2020
=> Bug: deleteUser mutation calls undefined wpmu_delete_user() function

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/MenuConnectionResolver.php, tests/wpunit/CommentObjectQueriesTest.php, tests/wpunit/MenuItemConnectionQueriesTest.php, tests/wpunit/TermObjectQueriesTest.php, tests/wpunit/UserObjectQueriesTest.php
This PR updates methods that used to be public to be public again. The change to being protected was with the assumption that users of the methods were extending the classes, however a common user of these methods are folks filtering the plugin as well and need the methods to be public to use from within filters.
I tested this with WPGraphQL Offset Pagination. 
**Before this PR:** 
**After this PR:**
=> #1240 - Protected methods in AbstractConnectionResolver break existing plugins

src/Data/DataSource.php, src/Type/Object/RootQuery.php
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.
This cached shim is no longer needed since the core version of this function is now cached. I left the method in there since it was public and anyone could be using it. I just threw a deprecated tag on it and removed usage from within the plugin.
…
(If it’s long, please paste to …
=> Remove cached method shim for get_page_by_uri

.gitattributes
This PR seeks to 
- Remove files that are zipped into the release plugin during the release process. However, they do not affect the use of the plugin by end user. (This consequentially reduces the zip size.)
- Remove the files in .gitattributes that have been restructured in PR #1249 
**Operating System:** Windows 10 & Mac OS 10.15
**WordPress Version:** WP 5.4
=> Update & Cleanup gitattributes

access-functions.php, src/Registry/TypeRegistry.php, src/Type/WPScalar.php, tests/wpunit/TypesTest.php
This allows for custom scalars to be registered and used with WPGraphQL
Below is example of this in action:
```
add_action( 'graphql_register_types', function() {
register_graphql_scalar([
'name' => 'Email',
'description' => __( 'Email according to the email spec, yo', 'wp-graphql' ),
'serialize' => function( $value ) {
return $value;
},
'parseValue' => function( $value ) {
if (!filter_var($value, FILTER_VALIDATE_EMAIL)) {
throw new Error("Cannot represent following value as email: " . \GraphQL\Utils\Utils::printSafeJson($value));
}
return $value;
},
'parseLiteral' => function( $valueNode, array $variables = null ) {
// Note: throwing GraphQL\Error\Error vs \UnexpectedValueException to benefit from GraphQL
// error location in query:
if (!$valueNode instanceof …
```
=> #1270 - register graphql scalar

README.md, documentation/Linting.md, documentation/Overview.md, documentation/Testing.md, documentation/UsingDocker.md
This PR seeks to make the readme.md simpler to read. Feel free to leave any comments on the commits.
I personally have mild dyslexia so it is hard to read. I suggest to split up the file into smaller files.
Other suggestions not in this PR:
=> Make the Readme simpler to read.

src/Model/Post.php, src/Type/InterfaceType/HierarchicalContentNode.php, src/Type/InterfaceType/NodeWithRevisions.php, tests/wpunit/PostObjectQueriesTest.php
To match the new fields for `MenuItem` in #1261 
This was supposed to be a trivial addition but it appears that the post model used `parentId` internally as the parent database id which collided with the new resolver definition so I had to change it to `parentDatabaseId`.
For graphql api users no breaking changes but this *might* affect some plugins.
Intentionally sending the codesniff fixes in a separate commit so the actually change is more clear in its commit.
=> Add `parentId` and `parentDatabaseId` to `HierarchicalContentNode` interface

src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Loader/AbstractDataLoader.php, tests/wpunit/PostObjectConnectionQueriesTest.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_framework_classmap.php, vendor/composer/autoload_static.php
WPGraphQL needs filters to properly handle pagination. If `suppress_filters` is applied to WP_Query by theme or plugin code, WPGraphQL can behave funky. 
This throws an InvariantViolation if `suppress_filters` is applied to `WP_Query` so developers can address appropriately.
=> #1259 - Throw InvariantViolation if suppress_filters are applied to WP_Query in GraphQL

src/Router.php
Instead of checking for `$_SERVER['HTTP_HOST']`  we can check the `$_SERVER['SERVER_NAME']` variable. This way we do not rely on the client supplying the correct host but can rely on our own server configuration.
Not that I could find.
N/A
When you call `/wp/graphql` on a domain that is different than the one configured in `site_url` the router will return 404. This is an issue for me because I want to do call within a docker network (which uses the container names …
=> Replaced HTTP_HOST with SERVER_NAME

src/Type/Object/PostObject.php, src/Type/Object/RootQuery.php, src/Type/Object/TermObject.php, tests/wpunit/IntrospectionQueryTest.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_framework_classmap.php, vendor/composer/autoload_static.php
This removes use of `isDeprecated` in favor of using `deprecationReason` to ensure deprecating fields _always_ include a reason. 
closes #1297 
I believe this might help with an issue @kidunot89 was running into with WPGraphQL for WooCommerce tests
=> #1297 - use deprecationReason instead of isDeprecated

docs/source/getting-started/custom-post-types.mdx, docs/source/getting-started/custom-taxonomies.mdx
--------------------------------------------------
Ensures the Custom Taxonomy and Custom Post Type pages use camelCase throughout, code examples were using PascalCase but document instructed they be in camelCase.
=> Edit Custom Taxonomy and Custom Post Type

docs/source/extensions/wpgraphql-woocommerce.mdx
Documentation update for WooCommerce extension.
The notice states that 'using it in production is not recommended'; however, there are sites that are using it production now. Keeping this as is may discourage other devs from trying the extension out - or even use it in production.
The development warning is suffice.
No
=> 📕 Docs: remove WooCommerce production warning in notice

src/Data/Connection/PostObjectConnectionResolver.php, src/Request.php, src/Type/Object/PostObject.php, tests/functional/ErrorHandlingCept.php, tests/wpunit/RequestTest.php
This add two filters `graphql_ast` and `graphql_pre_ast` which allow AST of the GraphQL queries to be inspected, transformed and cached. There are more detailed docs in the doc blocks.
Closes #112
=> Add `graphql_ast` filters

src/Data/Loader/PostObjectLoader.php
We have a complex setup with wpgraphql + acf. In our situation `PostObjectLoader.loadKeys()` is called with post ids that no longer exists. 
In such a case the loaded `post_object` will be empty which will lead to errors when trying to dereference attributes of this object.
- did not find any
```
[Wed May 20 14:34:54.489400 2020] [php7:notice] [pid 798] [client 10.42.1.0:56692] PHP Notice:  Trying to get property 'post_type' of …
```
=> make PostObjectLoader.loadKeys robust against non-existent keys

src/Router.php
This closes #1319. 
I'm reverting from `$_SERVER['SERVER_NAME']` back to using `$_SERVER['HTTP_HOST']` as this seems to work for most common WordPress setups. 
I have introduced a filter to allow different definitions of what makes a request a GraphQL HTTP Request, should different setups have different ways to define this.
=> #1319 - Add filter to "is_graphql_http_request"

src/Data/PostObjectMutation.php
This uses the author id even if it's encoded as a string. It checks if it _can_ be encoded as an integer and uses the integer value.
closes #1326
=> #1326 - Use the ID even if it's encoded as a string

tests/wpunit/MenuItemConnectionQueriesTest.php
Found a bug where wp-graphql would crash when fetching menu items list that has draft posts connected to it. But I realized too late that I was running an old version of wp-graphql and it was already fixed in the latest one 🤦‍♂️.
But before realizing it I already managed to write tests for it. Sending them anyway because there doesn't seem to be auth tests for menus ATM.
=> Add tests for draft pages in menus

src/Type/Enum/PostObjectsConnectionOrderbyEnum.php
Currently, posts does not allow to do order by with number of comments the post (or any custom name). I added the `COMMENT_COUNT` in the `PostObjectsConnectionOrderbyEnum`.
n/a
https://ibb.co/mh7GcHZ
n/a …
=> Add COMMENT_COUNT inside PostObjectsConnectionOrderbyEnum

src/Model/Post.php, src/Type/InterfaceType/ContentNode.php, tests/wpunit/PostObjectQueriesTest.php
This exposes the uri and link fields in the Post model as allowed restricted fields so that public requests can receive a link/uri when querying for a password protected post
closes #1338
=> #1338 - Expose URI (and link) as allowed restricted field

src/Connection/PostObjects.php, tests/wpunit/TaxonomyObjectQueriesTest.php
What does this implement/fix?
When adding taxonomy parameters as query arg, it takes an array of arrays. (see: 
https://developer.wordpress.org/reference/classes/wp_query/#taxonomy-parameters )
In the connection from term to post, the tax query arg value was not wrapped in array. This PR adds the additional array. 
Without this fix, unexpected posts were returned when using this connection.
**WordPress Version:** 5.2.6
=> Fix for tax query term to post connection by wrapping it an extra array

docs/source/extending/connections.mdx
Fixes a broken link in the extending -> connections documentation page.
Repro steps:
* visit https://docs.wpgraphql.com/extending/connections/
* in the blue note component at the top of the page, click on `Read the connections guide to learn more.`
Expected result:
* connections guide page renders (https://docs.wpgraphql.com/guides/connections/)
Actual result:
* 404
Nope
=> 📕 Docs: fix broken link to connection guide page

src/Utils/InstrumentSchema.php
This updates the `graphql_after_resolve_field` hook to pass the results of the resolver through as an argument on the action. 
This will allow plugins to do things such as cache results of specific fields and skip execution for future requests.
=> #1153 - pass the result of the resolver to the after resolve hook

src/Model/Post.php, tests/wpunit/PostObjectQueriesTest.php
This fixes a bug where restricted models (including password protected posts) might return null for ID and cause errors in the connection response. 
Closes #1374
=> #1374 - Password Protected posts returning errors in queries for posts

docs/source/guides/the-graphql-query-language.mdx
Currently the docs explain how to use `pageBy`. This is deprecated, according to the GraphQL client I use, so this is updated to use the new `idType` parameter.
Not that I can find.
Nu-uh …
=> Remove deprecated pageBy documentation

docs/source/getting-started/custom-fields-and-meta.mdx
`\WPGraphQL::$allowed_post_types;` returns `null`. I think it should be `\WPGraphQL::get_allowed_post_types();`
=> Use get_allowed_post_types() in documentation.

src/Data/Connection/MenuItemConnectionResolver.php, tests/wpunit/MenuItemConnectionQueriesTest.php
closes #1396 
- This fixes some logic around how the location argument is applied to the resolver
- Adds a test to prevent future regressions
Here, we can see that the `where` argument is trying to limit menu items to the `PRIMARY` location, but items are returned from any location, including "no" location
The same query properly returns _only_ items connected to the `PRIMARY` location
=> #1396 - location argument not properly respected for menu item queries

src/Connection/PostObjects.php
- This adds the connection args back to the children connections from HierarchicalContentNodes
- closes #1405 
This shows a query for children, filtering to exclude a specific ID from the children. An error is returned because the where args are not present.
This shows a query for children, filtering to exclude a specific ID from the children. An error is not returned and the query is executed properly because the args are available on the connection.
=> #1405 - where args missing from HierarchicalContentNode.children connections

src/Model/Post.php, src/Type/Object/RootQuery.php, tests/wpunit/PreviewTest.php
This fixes a bug where previews aren't returned by WPGraphQL when revisions are disabled. 
Includes a test to guard against regressions. 
closes #1408 
Authenticated request for a preview of a post returns null
Authenticated request for a preview of a post returns the preview node
=> #1408 - Show previews even if revisions are not enabled

src/Model/Post.php
- This avoids a PHP warning by checking if  graphql_single_name is set before using it
closes #1256
=> #1256 - undefined property graphql_single_name

src/Type/Object/RootQuery.php, tests/wpunit/ViewerQueryTest.php
closes #1419 
This removes the exception from the RootQuery.viewer field and instead returns a null if the request is made by an unauthenticated user.
=> #1419 - Remove exception from RootQuery.viewer field

src/Type/Object/RootQuery.php, tests/wpunit/NodeBySlugTest.php
Fix custom post types returning null when queried with SLUG idType  
#1397 
…
**Operating System:** MacOS 10.15.6
**WordPress Version:** 5.4.2
=> Fix issue #1397 custom post types not queryable with slug

src/Data/Connection/PostObjectConnectionResolver.php
When passing an empty array to ['where']['in'], wp-graphql will return posts back in ASC order starting from the oldest. WP_Query's default behavior is returning the set in DESC order from the newest. Changing this function will use WordPress's behavior.
=> Change isset to !empty on the ordering to match WordPress's behavior.

src/Type/Object/PostObject.php, src/Type/Object/TermObject.php
Instead of applying the `UniformResourceIdentifiable` Interface to _all_ Post Types and Taxonomies, this applies the interface to only public post types and taxonomies (the ones that can be accessed by URI)
closes #1496 
This is technically a breaking change as Types that used to implement this Interface no longer will implement this interface.
=> #1496 - Only apply URI interface to public Taxonomies and Post Types

src/Model/Post.php, src/Type/Object/PostObject.php, tests/wpunit/PostObjectQueriesTest.php
This adds an `isSticky` field to Post types.
Closes #1465 
**Operating System:** MacOs Catalina 10.15.6
**WordPress Version:** 5.5.1
=> Add isSticky Boolean field to Posts

docker/Dockerfile.test-base
This fixes a number of errors and warnings output by the Docker testing setup when building the containers. These didn't necessarily cause any issues, but this cuts down on the noise. 
All tests still run successfully locally after these changes.
- Add `unzip` to the installed packages. 
```
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them
```
- Remove `--dev` argument from `composer`. Prompted by `composer` dependency installation:
```
You are using the …
```
=> Update test Dockerfile to reduce errors and warnings

src/Mutation/PostObjectCreate.php, tests/wpunit/PostObjectMutationsTest.php
According to WordPress role definitions, Contributors can write and manage their own posts, but cannot publish them. 
Currently, WPGraphQL allows contributors to publish posts. 
This PR prevents users without `publish_posts` capability from publishing. If the mutation is set to publish, future or private, the status defaults to pending instead.
closes #1493 
Mutation executed as a Contributor.
=> #1493 - CreatePostMutation should not allow contributors to publish posts

src/Data/CommentMutation.php, src/Mutation/CommentCreate.php, tests/wpunit/CommentMutationsTest.php
Currently the `createComment` mutation allows for a `userId` input. 
Inputting a valid ID of a user allows for public users to create a comment as if it were created by a site user. 
This PR removes the `userId` input from the mutation and instead sets the user of the comment from the currently logged in user. If no user is logged in (public request) the author is set from the author input. If a public request and no author input, the comment is not created and an error is returned.
**BREAKING:**
- Removes `userId` input from createComment mutation
- Removes `agent` input from createComment mutation
- Removes `authorIp` input from createComment mutation
Any client application that was …
=> #1500 - createComment mutation should not allow userId to be set as input

src/Admin/GraphiQL/GraphiQL.php, src/Mutation/PostObjectUpdate.php, tests/wpunit/PostObjectMutationsTest.php
- Adds a check for the UpdatePost mutation to ensure the requesting user has permission to update the post object
- Adds tests for updating others posts with the PostObjectMutation
- Fixes bug with GraphiQL Admin bar showing for users that don't have capabilities to use it
**Before:**
Logged in as a contributor, I can execute a GraphQL `updatePost` mutation and change the title of a post authored by another user. 
**After:**
Logged in as a contributor, I can execute a GraphQL `updatePost` mutation to change the title of a post authored by another user and get an error in response. 
closes #1505
=> Bugfix: Prevents contributors from editing other posts

src/Model/Comment.php, src/Model/Post.php, tests/wpunit/CommentObjectQueriesTest.php
Comments that are attached to private posts are publicly available. This PR checks to see if a comment is attached to a private post and if so, it marks the comment as private.
This PR also adds a test to verify that admin users can view comments attached to private posts but anonymous users can not view comments attached to private posts.
**Operating System:** macOS Catalina Version 10.15.7
**WordPress Version:** 5.5.1
=> Make comments attached to private posts private

src/Router.php
- This adds a new `graphql_pre_is_graphql_http_request` filter with a default of null. If this filter is applied, the function uses that value and returns before executing default behavior, otherwise it executes as normal and then applies `graphql_is_graphql_http_request' filter to the final results. This allows overriding default logic early, or letting it execute and overriding late.
closes #1332
=> #1332: Adjust the behavior of the filters for is_graphql_http_request()

src/Router.php
This adds initial support for the upcoming WordPress Application Passwords feature by telling WordPress core that GraphQL HTTP Requests are API requests and that application passwords should set the current user for WPGraphQL requests the same way it does for REST / XML-RPC requests. 
Here's a screenshot testing the functionality:
This is a public request asking for the viewer, and getting nothing back.
This request passes an application password in the headers of the GraphQL request and in response the viewer data is returned. 
You can verify this functionality using the Application Passwords plugin: https://wordpress.org/plugins/application-passwords/
And you can learn more about Application Passwords in this helpful guide: https://maheshwaghmare.com/doc/application-passwords/
=> WordPress Application Password Support

src/Model/Post.php, src/Request.php
What does this implement/fix?
This PR caches the `$GLOBALS['wp_the_query']` before making GraphQL request. And restores `$GLOBALS['wp_the_query']` after GraphQL request is done. The solution follows the same pattern as with `$GLOBALS['post']` -object
Also this PR fix the issue (that comes from `$GLOBALS['wp_the_query']` -fix) with _EnqueuedScriptsTest_ and _EnqueuedStylesheetsTest_ -tests as is explained here: https://github.com/wp-graphql/wp-graphql/issues/1525#issuecomment-715122880
This PR close #1525 
WP Core in version 5.5.1 with Twentytwenty theme
=> Fix do_graphql_request()

src/Mutation/TermObjectCreate.php
This adds an action to TermObjectCreate.php called `graphql_insert_term`. This is very similar to the dynamic `graphql_insert_{$taxonomy->name}` action, but includes the WP_Taxonomy object as a parameter.
=> Add graphql_insert_term action

src/Type/Enum/ContentTypeEnum.php
This will allow for post-types like `Product` and `ProductVariation`, as well as any post-type not returned in `get_allowed_post_types()` to be used as values for the **ContentTypeEnum**
… …
=> Adds externally defined post-types to ContentTypeEnum

src/Data/Cursor/CursorBuilder.php, src/Data/Cursor/PostObjectCursor.php
Adds a new filter so that consumer can handle types before the SQL query is set. There are instances where a float is being passed but the type value is set to null. This creates unexpected SQL results.
An example implementation would be something like this:
```php
/**
* Ensure meta field type is set to decimal (float)
*/
add_filter( 'wpgraphql_cursor_ordering_field', function ( $fields, $builder, $object_cursor ) {
// Bail if not a float
if ( empty( strpos( $fields['value'], '.' ) ) ) {
return $fields;
}
$fields['type'] = 'DECIMAL(10,' . wc_get_price_decimals() . ')';
return $fields;
}, 10, 3 );
``` …
=> Add new filter for meta field order

src/Model/MenuItem.php, src/Model/Model.php, src/Model/Post.php, src/Request.php, src/Type/Enum/ContentTypeEnum.php, src/Utils/Tracing.php
- Fixes menu item paths to only return the path if the domain is either the site_url() or the home_url()
- also fixes a bug with Debug Flag exposing too much info to public users on errors
Query shows full paths for menu items:
Query shows relative paths for menu items:
----
closes #1532 
closes #1565
=> #1532 - Fixes menu item paths

src/Registry/TypeRegistry.php
Adds functionality to the `TypeRegistry::get_connection_name()` that uses `$from_field_name` as a fallback for `$to_type`.
@jasonbahl This is meant to resolve the `DUPLICATE_TYPE` error that comes in to effect when making multiple connections with the same `from` and `to` types without a designated `type_name` set in the connection configurations.
…
Any relevant …
=> Fallback functionality added to "TypeRegistry::get_connection_name()"

src/Model/Comment.php, src/Type/Object/Comment.php
This adds `parentId` and `parentDatabaseId` to Comment Model and Comment Type to support hierarchical query conventions such as documented here: https://www.wpgraphql.com/docs/menus/#hierarchical-data
=> Add parentId and parentDatabaseId to comment model and comment Type

src/Type/WPObjectType.php
Objects are invalid array keys.
=> Fix invalid array keys in WPObjectType

src/Mutation/PostObjectUpdate.php, tests/wpunit/PostObjectMutationsTest.php
- Cast `$existing_post->post_author` as `Integer` (by default it's a `String`) to make sure the comparison with `get_current_user_id()` (which is `Integer`) doesn't always return true
- Add missing word in the comparisons `UserError`
Closes #1610
=> #1610 Fix Author Comparison in PostObjectUpdate Mutation

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Router.php
- pass $status_code through to the `graphql_process_http_request_response` action
- only count the ids if the ids are not empty
- remove duplicate checks for `! empty( $this->get_offset() )`
---- 
closes #1602
=> #1602 - Fix countable php warning

CHANGELOG.md, src/Type/Object/RootQuery.php, tests/wpunit/PreviewTest.php
This fixes the validation of single entry points for posts to allow previews to return if their parent is of the same post type as the single entry field is intended to return.
=> #1629 - Fix regression to previews

src/Utils/InstrumentSchema.php
This outputs null when the deprecationReason is not set for fields instead of outputting an empty string. 
Some clients translate an empty string as a populated deprecationReason.
When looking at the WPGraphQL Schema in GraphQL Voyager before:
When looking at the WPGraphQL Schema in GraphQL Voyager after:
=> #1632 - output null when deprecationReason is not set for fields

src/Model/Model.php
This query results in an error:
```graphql
query MyQuery {
pages {
nodes {
uri
isFrontPage
}
}
}
```
The error is reported as internal server error on the `isFrontPage` field. I’ve pinpointed this to the implementation of `__get` on `WPGraphQL\Model\Model`. The reason it fails is because it’s called twice for `isFrontPage`—first when resolving the `uri` field and then when resolving the actual `isFrontPage` field. The implementation checks if it’s been called before by use of `!empty()` which doesn’t work if it’s been set to `false` because the type-checking later fails when the field returns `null` instead of `false`. This PR changes this check to `isset()` instead.
I’ve tested this very briefly, but I will use this is an actual project in the next few days so I will soon know if it …
=> Handle multiple magic gets of falsey values on model fields correctly

src/Data/Connection/UserConnectionResolver.php
The way users are being filtered in case the user is unauthenticated was redundant: firstly, the WPQuery has the `has_published_posts` arg set to true: `$query_args['has_published_posts'] = true;` and after, the users are filtered by the `is_private()` method of the User class.
Removing the query arg, the query then follows the count_user_posts() function behaviour and third-party plugins that filter the count_user_posts() (like co-authors plugin) are now supported
#1653
=> Fix issue #1653: removed user query arg, as it was redundant

src/Data/NodeResolver.php, src/Model/Post.php, src/Type/Object/RootQuery.php, tests/wpunit/NodeByUriTest.php, vendor/composer/InstalledVersions.php, vendor/composer/installed.php
- Fixes a regression with querying for pages by URI. Since the homepage can be either a page or a ContentType (post archive) there were some gaps in the logic for what to return if a page queries for the homepage, but the options are set to post archive, etc. This adds a test to help prevent regressions.
---- 
closes #1641
=> #1641 - Fix regression with page by uri queries

src/Router.php
Clear global $current_user in process_http_request if there is no current user authenticated, the same way it is done for the REST API serve_request in wp-includes/rest-api/class-wp-rest-server.php.
fixes wp-graphql/wp-graphql#1689
Ubuntu 20.04.1 LTS
5.6
=> fixes wp-graphql/wp-graphql#1689

access-functions.php
Prevents `wp_list_pluck()` from blowing up during CLI requests due to `debug_backtrace()` steps without `file` values.
…
… …
=> Filter added to "debug_backtrace()" return value in "graphql_debug()"

src/Admin/Settings/SettingsRegistry.php
Replace closing '/>' by '>' for html input tags, to follow the html specification which specifies no end tag.
See [https://www.w3.org/TR/html52/sec-forms.html#the-input-element](https://www.w3.org/TR/html52/sec-forms.html#the-input-element).
This was causing the disabled tag to be ignored by Chrome 88.0.4324.96 on Mac OS 11.2 in the following:
`<input type="checkbox" ... checked="checked" disabled/>`
Ubuntu 20.04.2 LTS
5.6
** Browser:**
Chrome 88.0.4324.96 on Mac OS 11.2
=> Replace closing '/>' by '>' for html input tags

src/Registry/TypeRegistry.php, tests/wpunit/PostObjectQueriesTest.php
This fixes a bug where the `DefaultTemplate` was added to the WPGraphQL Schema only if there were also other custom templates registered. This fixes it so the `DefaultTemplate` is _always_ registered and available in the Schema. 
closes #1709 
=> #1709 - Register the DefaultTemplate Type to the Schema always

phpcs.xml
Composer and readme says minimum supported version of PHP is 7.1, so the testVersion value should match this.
Brings PHPCompatibility coding standards config into line with min PHP version.
No.
N/A
=> PHPCS: Update testVersion to match support PHP

src/Connection/TermObjects.php
This commit prevents the terms field from not being registered in custom post types.
Closes #1771
=> fix: terms field was not registered in custom post types

src/Connection/MenuItems.php
This updates the connection resolver query for menu item children to use a tax query for the same nav_menu as the parent menu item. This guards against orphaned items (from invalid imports/migrations, for example) being returned.
closes #1768
=> #1768 - Update Menu Item children connection resolver with tax_query arg

phpstan/constants.php, src/WPGraphQL.php, tests/wpunit/WPGraphQLTest.php
This defines the `WPGRAPHQL_PLUGIN_URL` constant at the init hook, as recommended by https://developer.wordpress.org/reference/functions/plugins_url/#more-information
closes #1788
=> #1788 - update WPGRAPHQL_PLUGIN_URL to be defined at the `init` hook.

src/Data/NodeResolver.php, tests/wpunit/NodeByUriTest.php
Currently when a query inputs an external uri as the input, an error is thrown. This updates the behavior to return null instead of throw an error. 
closes #1783 
=> #1783 - Don't throw errors when external uri is provided as input

src/WPGraphQL.php, tests/wpunit/NodeByUriTest.php
This PR updates WPGraphQL.php to make use of register_post_type_args and register_taxonomy_args instead of overriding global $wp_post_types and $wp_taxonomies variables when setting up support for initial WP types in the Schema. This allows for testing environments to better reset state and clear the Schema and re-generate it.
- add create_initital_taxonomies() and create_initial_post_types() calls to the clear_schema() method so that post types and taxonomies can be re-generated when the schema is cleared. This is especially useful for resetting/testing with different permalink structures.
- remove set_permalink_structure from NodeByUriTest as it's included in the WPUnit test case …
=> #1796 - Allow tests to properly set different permalink structures

src/Data/NodeResolver.php, src/Type/InterfaceType/UniformResourceIdentifiable.php, tests/wpunit/NodeByUriTest.php, tests/wpunit/TermObjectQueriesTest.php
- Update nodeResolver to use `get_category_by_path()` function instead of `get_term_by( 'slug' )` to allow for terms at any level of hierarchy to be queried by uri
- Update NodeByUriTest to flush permalinks then call show_in_graphql() again to setup the core post types and taxonomies in the Schema after permalinks have been flushed
- Add tests to TermObjectQueriesTest to test querying child terms by uri both as part of nodeByUri and directly. Also tests custom post types.
closes #1464 
closes #1796 
=> Fixes querying child terms by URI

src/Type/Enum/UserRoleEnum.php, tests/wpunit/UserRoleEnumTest.php
When name field not present for a user role, use the key value as the name string.
#1761 
…
=> Use key for user type when name not defined

src/Utils/QueryLog.php, src/Utils/Tracing.php
When the value 'any' is set in the settings of wp graphql both in the Tracing role and in the Query log role none of these are returned.
=> fix: non-logged in users could not see the tracing or query log

.github/workflows/testing-integration.yml, bin/run-docker.sh, docker-compose.yml, docker/app.Dockerfile, docker/app.entrypoint.sh, docker/testing.Dockerfile, docker/testing.entrypoint.sh
Allow building docker app and testing images with xdebub 3 installed and configured on port 9003. 
Fixes #1737 using xdebug in a docker with this repo.
Here is how I'd document this.
The `app` docker image starts a running WordPress site with the local wp-graphql directory installed and activated. Local changes to the source code is immediately reflects in the app.
1. Build the plugin. …
=> Update to xdebug 3 config and add ability to build app docker with xdebug

.github/workflows/testing-integration.yml, bin/run-docker.sh, docker-compose.yml, docker/app.Dockerfile, docker/testing.Dockerfile, docker/testing.entrypoint.sh
Follow up work to issue #1737 
Allow environment variable SUITES to pass into `composter run-test` command.
Use composer packages from dist, not source to speed up update and install commands. As this pulls package versions and caches them instead of pulling from github .git repo.
Increase php file upload limit.
Updates to documentation at https://www.wpgraphql.com/docs/testing/ to come soon.
=> Simplify use of env variable SUITES to run specific tests.

src/Data/Connection/MenuItemConnectionResolver.php, tests/wpunit/MenuItemConnectionResolverTest.php
When no location menu items set, use empty array list.
#1844 
…
=> Use empty array when no menu locations registered

docs/docs-nav-menu.yaml
Sidebar navigation in wpgraphql.com is in the WP content right now. Includes sections, labels/titles, links to docs and order for pagination.  Putting that in this yaml file to specify order of that sidebar name as well as the optional text label.
https://github.com/orgs/wp-graphql/projects/8#card-59867799
… …
=> Add docs sidebar nav menu

src/Registry/TypeRegistry.php, tests/wpunit/TypesTest.php
This fixes a regression to the `register_graphql_connection` access function which was causing some custom connections to not be shown in the Schema. 
Closes #1882
Closes #1883
=> #1882 - Fix regression to register_graphql_connection

composer.lock, src/Utils/Preview.php, tests/wpunit/PreviewTest.php
- Update `filter_post_meta_for_previews` function to allow null or string for the $meta_key param
- add test to make sure `get_post_meta()` call with a null meta_key doesn't cause errors
- update composer.lock
closes #1864
=> #1864 - Allow null as meta key when filtering for previews

access-functions.php, src/AppContext.php, src/Data/NodeResolver.php, src/Mutation/MediaItemCreate.php, src/Registry/TypeRegistry.php, src/Type/InterfaceType/ContentTemplate.php, src/Type/InterfaceType/DatabaseIdentifier.php, src/Type/InterfaceType/Node.php, src/Type/InterfaceType/UniformResourceIdentifiable.php, src/Type/ObjectType/RootQuery.php, src/Type/Union/PostObjectUnion.php, src/Utils/InstrumentSchema.php, src/WPSchema.php
This adds two hooks allowing extensions to resolve their nodes when using `nodeByUri`.
no!
I also did a minor cleanup while I was browsing around the codebase.
Just for reference, here is where I'm using it: https://github.com/wp-graphql/wp-graphql-buddypress/issues/77
**Operating System:** MacOS Big Sur 11.3
**WordPress Version:** Version 5.7.1
=> Allowing extensions to support `nodeByUri`

.github/workflows/upload-schema-artifact.yml
This adds a Github Workflow that uploads the `schema.graphql` as an artifact to releases. 
This is part one of #335. 
Once the Schema is output to releases, we can have a workflow that compares the previous release with the upcoming release and check to see if there are any breaking changes.
=> - Add Github workflow to upload schema.graphql as a release asset

.github/workflows/code-quality.yml, .github/workflows/schema-linter.yml, .github/workflows/testing-integration.yml, .github/workflows/wordpress-coding-standards.yml, CHANGELOG.md, readme.txt, src/Model/User.php, src/WPGraphQL.php, wp-graphql.php
- ([#1940](https://github.com/wp-graphql/wp-graphql/pull/1940)): Adds Breaking Change inspector to run on new Pull Requests. Thanks @markkelnar!
- ([#1937](https://github.com/wp-graphql/wp-graphql/pull/1937)): Fixed typo in documentation. Thanks @LeonardoDB!
- ([#1923](https://github.com/wp-graphql/wp-graphql/issues/1923)): Fixed bug where User Model didn't support the databaseId field
- ([#1938](https://github.com/wp-graphql/wp-graphql/pull/1938)): Adds new functionality to the `register_graphql_connection()` API. Thanks @kidunot89!
=> Release v1.3.10

src/Data/DataSource.php, src/Mutation/UpdateSettings.php, src/Registry/TypeRegistry.php, src/Type/ObjectType/Settings.php, src/Utils/InstrumentSchema.php, tests/wpunit/SettingQueriesTest.php, tests/wpunit/SettingsQueriesTest.php
Found a place where we are not scrubbing the group names for WP registered settings consistantly.
https://github.com/wp-graphql/wp-graphql/issues/1925
…
=> Scrub registered settings group names

src/Type/WPInterfaceType.php, src/Type/WPObjectType.php, tests/wpunit/TermNodeTest.php
- This updates the code that merges fields on the WPObjectType with fields from interfaces to properly use resolvers from object definitions. 
- Updates test to ensure URI field on term node matches expected output
closes #1959
=> Bugfix/#1959 - uri returns null on term nodes

CHANGELOG.md, readme.txt, src/WPGraphQL.php, wp-graphql.php
- ([#1963](https://github.com/wp-graphql/wp-graphql/pull/1963)): Fixes a regression in v1.4.0 where the `uri` field on Terms was returning `null`. The issue was actually wider than that as resolvers on Object Types that implement interfaces weren't being fully respected. 
- ([#1956](https://github.com/wp-graphql/wp-graphql/pull/1956)): Adds `SpaceAfterFunction` Code Sniffer rule and adjusts the codebase to respect the rule. Thanks @markkelnar!
=> Release v1.4.2

docker/app.Dockerfile, docker/app.entrypoint.sh, docker/app.post-setup.sh, docker/app.setup.sh, docker/testing.Dockerfile, docker/testing.entrypoint.sh
The app entrypoint sh script is invoked by the testing script. But also invokes the exec CMD, which starts apache. For the testing image, we don't want to do that, we have a different exec CMD to run.  So it has a 'sed' command to modify the apo entrypoint script.  Kinda gross. We want to invoke the app setup for testing and potentially for other docker image.
Right now, don't really change any behavior. Just make it more useable for the next script that wants to invoke it.
Part of https://github.com/wp-graphql/wp-graphql-persisted-queries/issues/1
Any relevant logs, error output, GraphiQL screenshots, …
=> Docker app script for setup without the exec

src/Type/ObjectType/MenuItem.php
From Wordpress it is possible to add a custom link without an URL.
When that happens GraphQL will throw `Cannot return null for non-nullable field \"MenuItem.path\".`.
From Wordpress it is possible to add a custom link without an URL.
When that happens GraphQL will throw `Cannot return null for non-nullable field \"MenuItem.path\".`.
Cannot return null for non-nullable field "MenuItem.path".
**Operating System: …
=> Bugfix: Remove non-null from MenuItem path

docker/testing.Dockerfile, docker/testing.entrypoint.sh
Because we are starting apache independently of the docker image in the testing image, we need to set WORDPRESS environment variables so apache sees them and they are used in the wp-config.php
=> ci: WP environment vars for testing image

docs/connections.md
It fixes Relay Specification url in docs
=> fix: Relay Specification link in connections

src/Data/NodeResolver.php, tests/wpunit/PluginCompatibilityTest.php
Fixes conflict with AmpWP Plugin (and possibly other plugins) where the callback for `parse_request` in that plugin is expecting an instance of the `WP` class and we were passing the NodeResolver class. 
Also includes test to mimic behavior of AmpWP plugin and prevent regression for this scenario.
closes #1979 
With AMPWP plugin active:
=> Fix conflict with AmpWP plugin

src/Type/Enum/ContentTypeEnum.php, tests/wpunit/AssertValidSchemaTest.php
The WPGraphQL Schema generates a `ContentTypesOf{TaxonomyName}Enum` with the values being the names of the associated post types. 
For example, there's an Enum `ContentTypesOfPostEnum` that has values `POST` out of the box: 
Currently when a Taxonomy is registered to "show_in_graphql" but is associated with post type(s) that are set to NOT show in GraphQL, a `ContentTypesOf{TaxonomyName}Enum` is Generated with no values. 
For example, we can register a post type that is not shown in GraphQL, like so: 
```php
register_post_type( 'not_in_graphql', [
'public' => true,
] );
```
And register a taxonomy associated with that post type, that IS shown in GraphQL, like so: 
```php …
```
=> Prevent ContentTypesOf* Enum from generating when associated post types are not shown in GraphQL

docker-compose.yml
Use `mariadb` instead `mysql` image in Docker environment. The `mariadb` image provides images for ARM platforms (including M1 / "Apple Silicon" Macs) without the need for additional Docker configuration.
**Operating System:** macOS on M1 chip
=> Use mariadb instead of mysql for tests

.github/workflows/deploy-docker-image.yml
Build docker images for PHP 8.0 and versions of WP 5.7.2.  This matches what was recently added to the testing integration workflow.
=> Add php8 for docker image build/deploy

docker-compose.yml, docker/testing.Dockerfile, docker/testing.entrypoint.sh
Use the $PROJECT_DIR from the .env file instead of the hardcoded directory in the script. This will allow other docker images to resuse this docker file to base their tests on and run codeception tests from their own PROJECT_DIR.
Related to work for persisted queries plugin tests.
Should not change behavior for this repo.
=> Run tests from PROJECT_DIR var

src/Registry/TypeRegistry.php, src/Type/WPConnectionType.php
This pull request introduces a new WPConnectionType class which handles the logic for registering connections. 
The registration of connections is now moved outside of the TypeRegistry->register_connection() function and into the class. 
This paves the way for future possible functionality such as `rename_graphql_connection`, `deregister_graphql_connection`, `register_graphql_edge_fields`, `register_graphql_connection_args`, etc. 
Closes #1935
=> Refactor TypeRegistry->register_connection() into it's own class

.github/workflows/deploy-docker-image.yml, CHANGELOG.md, docker-compose.yml, docker/testing.Dockerfile, docker/testing.entrypoint.sh, docs/concepts.md, readme.txt, src/Registry/TypeRegistry.php, src/Type/WPConnectionType.php, src/WPGraphQL.php, wp-graphql.php
- ([#2001](https://github.com/wp-graphql/wp-graphql/pull/2001)): Updates Docker environment to use MariaDB instead of MySQL to play nice with those fancy M1 Macs. Thanks @chriszarate!
- ([#2002](https://github.com/wp-graphql/wp-graphql/pull/2002)): Add PHP8 Docker image to deploy upon releases. Thanks @markkelnar!
- ([#2006](https://github.com/wp-graphql/wp-graphql/pull/2006)): Update Docker to use $PROJECT_DIR variable instead of hardcoded value to allow composed docker images to run their own tests from their own project. Thanks @markkelnar!
- ([#2007](https://github.com/wp-graphql/wp-graphql/pull/2007)): Update broken links to Relay spec. Thanks @ramyareye!
- ([#2009](https://github.com/wp-graphql/wp-graphql/pull/2009)): Adds new WPConnectionType class and refactors …
=> Release v1.5.3

.github/workflows/deploy-docker-image.yml
Similar to how we push the built docker image for the app, let's also push the testing built image to the github container registry.  This will help with other plugins that want to reuse that testing image/container flow instead of rebuilding all the pieces.  
First use case as part of https://github.com/wp-graphql/wp-graphql-persisted-queries/issues/2.
=> Tag and deploy testing image for use from the registry

.github/workflows/deploy-docker-image.yml, docker/testing.Dockerfile
Fix the failing workflow that builds the wp-graphql-testing image and deploys it to the container registry.
This job runs when release is tagged.
=> Add docker registry for testing docker image

.github/workflows/testing-integration.yml, readme.txt
This PR updates the Github test integration workflow to run with WordPress 5.8 (using beta-5.8 as [Docker Hub](https://hub.docker.com/_/wordpress) doesn't have 5.8 images yet)
closes #2024
=> Update tests to use WordPress 5.8

.github/workflows/deploy-docker-image.yml, .github/workflows/testing-integration.yml, CHANGELOG.md, docker/app.setup.sh, docker/testing.Dockerfile, readme.txt, src/WPGraphQL.php, tests/_bootstrap/bootstrap.php, tests/_data/config.php, tests/functional.suite.dist.yml, tests/functional/ApolloPreflightRequestCept.php, tests/functional/BasicPostListCept.php, tests/functional/BatchQueriesCept.php, tests/functional/BatchQueriesDisabledCept.php, tests/functional/MenuWithMenuItemsCept.php, tests/functional/PostListWithDifferentStatusCept.php, tests/functional/QueryDepthRuleCept.php, tests/functional/RestrictedQueriesCept.php, tests/functional/bootstrap.php, wp-graphql.php
- ([#2023](https://github.com/wp-graphql/wp-graphql/pull/2023)): Fixes issue with deploying Docker Testing Images. Thanks @markkelnar!
- ([#2025](https://github.com/wp-graphql/wp-graphql/pull/2025)): Update test workflow to test against WordPress 5.8 (released today) and updates the readme.txt to reflect the plugin has been tested up to 5.8
- ([#2028](https://github.com/wp-graphql/wp-graphql/pull/2028)): Update Codeception test environment to prevent WordPress from entering maintenance mode during tests.
=> Release v1.5.5

.distignore, composer.json
- Update .distignore and composer.json to ignore the /docs directory when creating an archive to deploy to WordPress.org
closes #2034
=> Ingore docs in deployed code

src/Registry/TypeRegistry.php, tests/wpunit/AssertValidSchemaTest.php
--------------------------------------------------
This fixes a bug where GraphQL Types that shared the name of a global PHP function would try and lazy load by calling that PHP function. 
For example, a GraphQL Type named `Header` would try and call `header()` to lazy load, which is not what should happen.
This PR does the following:
- Update the TypeRegistry to prefix types in the registry with `graphql_type_`
- Update the logic around `is_callable()` in the setup_type_modifiers function
- Adds a test to register a type that shares the name of a global PHP function (header`
Closes #2047 
With the following …
=> Bug/#2047 - Allow Types to share the name of a global PHP function

src/Utils/Preview.php, tests/wpunit/PreviewTest.php
--------------------------------------------------
Allows for null to be passed in argument 4 (bool) in filter_post_meta_for_previews.
No
`[04-Aug-2021 19:15:35 UTC] PHP Fatal error:  Uncaught TypeError: Argument 4 passed to WPGraphQL\Utils\Preview::filter_post_meta_for_previews() must be of the type bool, null given, called in /nas/content/live/devcasa/wp-includes/class-wp-hook.php on line 305 and defined in /nas/content/live/devcasa/wp-content/plugins/wp-graphql/src/Utils/Previ …
=> allow argument 4 to be null in filter_post_meta_for_previews()

src/Request.php
This sets `is_graphql_request` to `true` in the constructor so that `is_graphql_request()` can be more accurate in its return value.
This would close #2080 
See issue for details.
N/A
**Operating System:** Mac OS 11.5.2
**WordPress Version:** 5.8
=> Set is_graphql_request = true in constructor

src/Admin/Admin.php
This adds the GraphiQL class as a global variable to allow extensions access to it to filter out actions/hooks defined by the 
ex: 
```php
add_action( 'admin_init', function() {
global $graphiql;
// prevent normal GraphiQL from loading
remove_action( 'admin_enqueue_scripts', [ $graphiql, 'enqueue_graphiql' ], 10 );
}, 99 );
```
closes #2088
=> Add `$graphiql` global variable

docs/wpgraphql-vs-wp-rest-api.md
This fixes a link in the WPGraphQL vs. REST docs page.
No.
No.
No.
n/a
=> Fix link in WPGraphQL vs. REST docs page

composer.json, composer.lock
hautelook/phpass is 404 on github. Package dependency build using lucatume/wp-browser are failing on version <3.0.11.  Let's update to at least ^3.0 and see if this fixes the problem faced by some packages requiring hautelook/phpass.
…
…
=> Upgrade lucatume/wp-browser to 3.0 to fix phpass error

src/Request.php
Add new filters during processing of the request to invoke filter before execution of the query. If results are returned from the filter, do not run the full execution of the query.
Related to persisted queries and caching [work](https://github.com/wp-graphql/wp-graphql-persisted-queries/issues/18).
… …
=> Add pre_graphql_execute_request filter to allow cache to be queried first

src/Request.php
Wrong variable which caused $response to always be empty and throw error, when filter returned results.
Related to persisted queries and caching [work](https://github.com/wp-graphql/wp-graphql-persisted-queries/issues/18).
…
=> Use correct variable for pre execure request filter

docs/custom-post-types.md, src/Model/Post.php, tests/wpunit/ContentNodeInterfaceTest.php, tests/wpunit/CustomPostTypeTest.php
Fixes #2134.
Consider a post as private if 'publicly_queryable' is set to false so that only authenticated users with the required capability can access it.
Yes, #2134.
Please test this to double-check that it results in the intended behavior.
I also updated the paragraph at the top of the https://www.wpgraphql.com/docs/custom-post-types/#public-vs-private-data section of the docs to reflect this change (wp-admin edit page is here: https://content.wpgraphql.com/wp-admin/post.php?post=5116&action=edit).
=> Respect 'publicly_queryable' post type setting.

src/Type/WPConnectionType.php, tests/wpunit/FiltersTest.php
This PR adds the `graphql_wp_connection_type_config` filter to WPConnectionType, providing basic parity with the other `WP{$}Type` classes, and making it possible to filter existing connections and resolvers.
This is an additive change. There are no unit test regarding other filters, so I'm assuming none are needed here. Also it seems the docs for filters arent in the repo anymore (autogenerated?) but if they do need to go somewhere, let me know.
#2140 
Usage Example
```php
add_filter( 'graphql_wp_connection_type_config',
function( array $config ) : array {
if ( 'RootQuery' !== …
```
=> fix: Add missing `graphql_wp_connection_type_config` filter.

src/Data/Config.php, tests/wpunit/CursorPaginationForPostsTest.php
- Updates the WP_Query cursor stabilization logic to account for cursor compare direction
- Adds pagination tests for posts with identical dates and titles
Closes #2137, #2133
Here's a video walking through the issue and showing the resolution in action. 
https://www.youtube.com/watch?v=FnARcaOLKVI
=> #2137 - fixes bug with cursor stabilization

src/Type/InterfaceType/TermNode.php, tests/wpunit/TermObjectQueriesTest.php
This PR adds a `taxonomyName` field to the `TermNode` type, since there’s currently no other way to associate a generic term node to its taxonomy. This is also potentially more performant compared to `taxonomy->name` since the taxonomy doesn’t have to be loaded to get the taxonomy name.
=> feat: Add `taxonomyName` field

src/Router.php
Ignores the domain and just makes sure the configured graphql path is the root path.
fixes #2181
https://wpengine.atlassian.net/browse/NEB-844
Should write from tests, but I'll leave that to the experts. 
Right now `/graphql/this/that/the/other/`  passes. If we wanted we could test the path to make sure it's only `/graphql` or `/graphql/` but I'm not sure if it is an issue. 
Tested it on my local PC as per below and also tested on WPEngine and validated it works. 
macOS 11.16.1 …
=> fix: checking for route instead of domain+route

src/Registry/SchemaRegistry.php, src/Router.php, src/WPSchema.php
This passes the TypeRegistry through the "graphql_schema_config" filter
closes #2199 
This also includes a bugfix follow-up to #2182
=> #2199 - pass TypeRegistry to the schema config filter

src/Model/Model.php
The Model constructor should call `prepare_fields()` statically, since A) the method isnt `static`, and B) the method relies on other non-static methods, so it cannot be made `static`.
Screenshot of the issue:
**Operating System:** Ubuntu 20.04 (wsl2).
**WordPress Version:** 5.8.2
=> Model.php: Don't call `prepare_fields()` statically

docs/graphql-resolvers.md, src/Mutation/PostObjectCreate.php, src/Registry/TypeRegistry.php
A filter on the post input args for specific post type when post is created. Allows for args to be filtered, validated, renamed, etc.
Used for [this persisted queries work ](https://github.com/wp-graphql/wp-graphql-persisted-queries/pull/40) to filter input on mutation create/update. 
re: https://github.com/wp-graphql/wp-graphql-persisted-queries/issues/38
=> Add filter for post insert type during create

.github/workflows/deploy-docker-image.yml
Add WP version 5.8 to the matrix list of versions built and deployed for available docker images.  
This version is already included in the 'Testing Integration' action.
=> Add WP 5.8 to the matrix of docker images built

src/Admin/Settings/Settings.php
This adds a note to the GraphQL Introspection setting, that it is force-enabled when GraphQL Debug mode is enabled
closes #2217
=> Add a note to the GraphQL Introspection setting when Debug mode is enabled

src/Registry/TypeRegistry.php, src/Type/ObjectType/TermObject.php, tests/wpunit/TermNodeTest.php
This way the uri will return a relative path even if the term link does not contain the home_url()
When for example` get_term_link( $this->data->term_id )` returns a term link that contains a `host:port` path different than `home_url()`
`get_term_link( $this->data->term_id)` -> `http://localhost:3000/post/example`
`home_url-> 'http://example.com`
The term uri is not substituted correctly because the `home_url` substring does not exist in the `get_term_link` result
`uri` ->` http://localhost:3000/post/example`
With this fix it will replace any host:port path from the term link
`uri` -> `/post/example`
🚨 Please review the [guidelines for …
=> fix: TermObject uri strips host:port path instead of home_url()

src/Type/InterfaceType/CommenterInterface.php, src/Type/ObjectType/CommentAuthor.php, src/Type/ObjectType/User.php, tests/wpunit/CommentObjectQueriesTest.php
This PR does the following:
- Add the avatar field to the Commenter interface so that User and CommentAuthor can both query for avatar field
- Update resolver in CommentAuthor to properly resolve to the avatar
- remove description for avatar field from User type to let it inherit from the Interface
- add tests to query for avatar on comment from a user and a guest author
This allows for the `avatar` field to be queried from User and CommentAuthor Types. 
Before, the avatar was returned only for the User type, but not the CommentAuthor type, so querying for comment authors meant only getting the avatar field for comments written by authors that are also users. 
Now public "guest" authors …
=> Add avatar field to the CommentAuthor Type and Commenter Interface

src/Data/UserMutation.php
When I try to update some user fields like last name, website, etc, with empty values, they're not being updated because of a condition that checks if they're empty and so ignores them. I should be able to update with empty values.
What I've done:
1. I've changed the condition (!empty) to (isset) for optional fields. I haven't changed the required ones.
2. The code was reordered into two groups: Required and optional fields
mutation: updateUser
...
...
…
Where has …
=> Make some user fields optional

src/Data/DataSource.php, src/Mutation/UpdateSettings.php, src/Registry/TypeRegistry.php, src/Type/ObjectType/SettingGroup.php, src/Type/ObjectType/Settings.php, src/Utils/InstrumentSchema.php, tests/wpunit/SettingQueriesTest.php, tests/wpunit/SettingsMutationsTest.php
This PR addresses a bug where settings registered using the `register_setting()` API are mapped to the WPGraphQL Schema, even if the `type` defined is an invalid GraphQL Type.
This fixes the bug by only mapping settings that have a valid type defined (`string`, `integer`, etc). 
Settings that have an arbitrary type such as `array` or `object` are no longer mapped to the Schema. 
for example:
```php
register_setting( 'my_setting_group', 'my_setting_field', [ 
'show_in_rest' => true, 
'type' => 'string',
'sanitize_callback' => 'sanitize_text_field', 
] );
```
Would map to the Schema and be queryable like so: 
```graphql
{
mySettingGroupSettings {
mySettingField
}
}
```
and also queryable …
=> #2065 - Fix bug where settings registered with Types not recognized by WPGraphQL cause errors with Introspection

src/Mutation/UpdateSettings.php, src/Registry/TypeRegistry.php, src/Type/ObjectType/SettingGroup.php
This updates the call to `register_graphql_field` to use `$this->register_field()` for the multisite `generalSettings.url` field
closes #2274 
In v1.6.12, we can see that we can succesfully query for:
```graphql
{
generalSettings {
dateFormat
url
}
}
```
In v1.7.1 we can see that the same leads to an error, as the field `generalSettings.url` is not in the Schema
With this change, we can query the field again:
This PR doesn't have a test for this, as we don't have the …
=> #2274 - fix bug with the generalSettings.url field being removed 

.gitattributes, composer.json
This PR updates the composer scripts to include a post-install script which installs npm dependencies and builds the graphiql app. 
This:
- update .gitattributes, to **_not_** ignore the packages directory, as it includes packages needed to build the JS files
- update `composer.json` to exclude the packages directory for plugin builds. The final result, after building the plugin, does not need the packages directory
closes #2273 
We should be able to also remove the `npm install` / `npm run build` scripts from workflows that already run composer install, as this …
=> Add composer post-install script

docker/testing.entrypoint.sh
When another repo extends the docker file format of wp-graphql (ex. wp-graphql-labs), but doesn't have a package.json file of it's own, running the testing image fails for that repo.  This fix will not run `npm` commands during docker container run/up if the package.json file does not exist.  Prints/echos a message stating that.
No
With the fix, prints "Skipping npm install"
**WordPress …
=> For repos that extend the docker testing image and dont have a package.json

src/Model/Post.php, src/Registry/TypeRegistry.php, src/Type/InterfaceType/ContentTemplate.php
This PR replaces the use of `wp_get_theme()->get_post_templates()` with the filterable `wp_get_theme()->get_page_templates()`.
For sanity, the `register_graphql_object_type()` loop has been moved from class `TypeRegistry` to class `Type\InterfaceType\ContentTemplate`, following the pattern established in `RootQuery::register_post_object_fields()`, and `RootQuery::register_term_object_fields()`.
#1845 
- I would recommend the pattern used here be adopted for the rest of the registration loops in TypeRegistry. Happy to work on a PR.
- From my understanding of the …
=> Register post/page templates with get_page_templates()

src/Mutation/MediaItemUpdate.php, tests/wpunit/MediaItemMutationsTest.php
When running a `updateMediaItem` mutation as a user who can't edit another users' posts, a `UserError` gets thrown, even if this should go through for users who can update their post and are trying to do that. 
The `$author_id` variable was always a string. Both in the initial assignment when pulling it out of the media item post [here](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Mutation/MediaItemUpdate.php#L85), and for the case where a different user ID is provided [here](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Mutation/MediaItemUpdate.php#L109).
This PR should cast the variable to int, and make sure that the comparison with the `get_current_user_id` …
=> fix: MediaItemUpdate mutation comparing string author ID with number returned from get_current_user_id

composer.json
This PR adds the `allow-plugins` config to `composer.json`, so users running Composer v2.2.0+ can run `composer install` without the annoying prompts (pictured):
**Operating System:** Ubuntu 20.04 + PHP 8.0.15, Composer v2.2.5
**WordPress Version:** 5.9.1
=> chore: add `allow-plugins` to composer.json config

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/ContentTypeConnectionResolver.php, src/Data/Connection/EnqueuedScriptsConnectionResolver.php, src/Data/Connection/EnqueuedStylesheetConnectionResolver.php, src/Data/Connection/PluginConnectionResolver.php, src/Data/Connection/TaxonomyConnectionResolver.php, src/Data/Connection/ThemeConnectionResolver.php, src/Data/Connection/UserRoleConnectionResolver.php
This PR refactors `AbstractConnectionResolver::get_nodes()` to use a separate function (`AbstractionConnectonResolver::get_ids_for_nodes()` for slicing the query ids by the `query_amount` and `offset`.
This serves three purposes:
1. Improves the performance of child `get_nodes()` methods, since the models are only fetched for the actual nodes to return.
2. Makes extending `AbstractConnectionResolver` more DRY, since for most use cases in core, `get_nodes()` is really only used to change how the offsets are handled.
3. Fixes issues like #2087 , since currently `parent::get_nodes()` slices by `query_amount` _before_ slicing by `offset`, which is the entire reason `get_nodes()` needs to be …
=> fix: refactor AbstractConnectionResolver::get_nodes() to prevent children double slicing

src/Utils/Utils.php, tests/wpunit/TypesTest.php
This PR adds a basic `Utils::get_database_id_from_id()` method that is able to take a value from any GraphQL `ID` type, and resolve it to an `int` database ID.
**Note:** Naming things is _hard_. I'm open to suggestions.
This lays the groundwork for #998. It: 
- When implemented, will allow users supply _either_ a global or database ID to any input argument that requires a database ID internally, *in a nonbreaking manner*
- Keeps things DRY and slims down the existing codebase by removing the logic of parsing global ids from [multiple existing parts of _our_ codebase](https://github.com/wp-graphql/wp-graphql/search?q=Relay%3A%3AfromGlobalId%28), and helpful to cut down that same …
=> feat: add `Utils::get_database_id_from_id()` for DRY handling of `ID` types.

src/Data/CommentMutation.php, src/Model/Comment.php, src/Mutation/CommentCreate.php, tests/wpunit/CommentMutationsTest.php
This PR fixes `CommentMutation::prepare_comment_object()` to correctly set a comment's author when it differs from the currently logged-in user.
#2131 
- Note the two commented-out asserts in `CommentMutationsTest::testCreateComment()`. For some reason, a subscriber is unable to view their own comment. The resolver creates the model, and the model's visibility is visible, but for some reason `DataSource::resolve_comment()` is coming back null. 
I reverted the changes and tried the asserts, but  `comments` still returns null in the tests (didnt check manually in …
=> Fix: Use comment author when admin are creating/updating a different users comment.

src/Data/Connection/PluginConnectionResolver.php, src/Model/Plugin.php
This PR changes the minimum permissions to query plugins from `update_plugins` to `activate_plugins`. 
See conversation in #2298
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php 8.0.15)
**WordPress Version:** 5.9.2
=> feat: change min permissions for Plugins from `update` to `activate`

src/Model/Comment.php, tests/wpunit/CommentObjectQueriesTest.php
This PR fixes an issue with the Comment model's `contentRendered` field, where the `WP_Comment` object was not passed to the `comment_text` wp filter.
closes #2309 
There are no tests to write. The behavior of the plugin hasnt changed, we're just fixing our use of WP's api.
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php8)
**WordPress Version:** 5.9.2
=> fix: pass `WP_Comment` object to `comment_text` filter

src/Data/Connection/PluginConnectionResolver.php, src/Data/Loader/PluginLoader.php, src/Registry/TypeRegistry.php, src/Type/Enum/PluginStatusEnum.php, src/Type/ObjectType/RootQuery.php, tests/wpunit/PluginConnectionQueriesTest.php
This PR adds the ability to filter plugin connections. It builds off #895 and loosely mimics [`WP_Plugins_List_Table::prepare_items()`](https://github.com/WordPress/wordpress-develop/blob/0b800e21c311e302824e4a025946a6fdb4f6c794/src/wp-admin/includes/class-wp-plugins-list-table.php#L92)
It adds the following where args to `RootQueryToPluginConnection`:
- `search`: a keyword search across all plugin data.
- `status`:  filters by a single `PluginStatusEnum`.
- `stati`: filters by _any_ `PluginStatusEnum` in the given array.
The possible plugin stati that can be filtered are: `ACTIVE`, `DROP_IN`, `INACTIVE`, `MUST_USE`, `PAUSED`, `RECENTLY_ACTIVE`, and `UPGRADE`. On MU, we also get …
=> feat: add where args to plugin connections

src/Utils/Utils.php
The get_allowed_wp_kses_html function was missing "select" and "option" which stripped the HTML when trying to add settings fields.
I noticed this when making an update I'm working on for the wpgraphql-cors repo which has its own tab of settings. Without this change, its not possible to create settings of the "select" type.
…
… …
=> "select" and "option" added to allowed HTML for settings.

src/Type/ObjectType/Comment.php, tests/wpunit/CommentObjectQueriesTest.php
This fixes a bug where Comment Authors are not always returned if the author is a user, and the user is not considered a public node. 
- update resolver for Comment->author connection to load the CommentAuthor (public) by default, and only use the User node if it's publicly visible
- update test to query publicly and authenticated
closes #2348 
Given a user (in my case with `databaseId: 4`) that has no published content in any public post type, have that user post a comment and approve the comment. 
This …
=> Fixes bug with Comment Authors not always returning

src/Utils/Utils.php
The get_allowed_wp_kses_html function was missing the "selected" attribute which stripped the HTML when trying to save a select field in custom wpgraphql settings. This should have been included with #2349 but I didn't realize it wasn't saving until now. Oops =/.
…
…
**Operating System:** Apache2 PHP 7.4 on Docker
**WordPress …
=> Amendment to #2349 to add "selected" attribute to allowed HTML.

src/Connection/Taxonomies.php, src/Connection/TermObjects.php, src/Data/Connection/ContentTypeConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php, src/Data/Loader/PostTypeLoader.php, src/Data/Loader/TaxonomyLoader.php, src/Data/NodeResolver.php, src/Type/Enum/ContentTypeEnum.php, src/Type/ObjectType/RootQuery.php, src/Type/Union/MenuItemObjectUnion.php, src/WPGraphQL.php, tests/wpunit/WPGraphQLTest.php
What does this implement/fix? Explain your changes
This PR refactors `WPGraphQL::get_allowed_post_types()` and `WPGraphQL::get_allowed_taxonomies()` to correctly store data in the `WPGraphQL::$allowed_post_types` and `WPGraphQL::$allowed_taxonomies` class properties.
Additionally, it stores the `WP_Post_Type` and `WP_Taxonomy` objects, allowing the user to retrieve _either_.
This will ensure that the list of possible post types / taxonomies is the same throughout the schema, and will also let us significantly clean up the codebase by removing now-extraneous rehydration calls ( e.g. `get_post_type( \WPGraphQL::allowed_post_type( )[ $n ] )` ) in a future PR.
* The array of `WP_Post_Type`s and `WP_Taxonomies` are stored to their respective …
=> Feat: Refactor get_allowed_post_types() and get_allowed_taxonomies()

src/Data/CommentMutation.php, src/Mutation/CommentCreate.php, src/Mutation/CommentDelete.php, src/Mutation/CommentRestore.php, src/Mutation/CommentUpdate.php, tests/wpunit/CommentMutationsTest.php
This PR enables users to supply _either_ a database ID or a global ID to comment mutation inputs of `type` ID. Part of #998 .
The description of `commentOn` was changed to specify it only takes a database ID  (until #532 can be handled).
Also a new test was added for creating child comments.
Invalidates #2195 
- I'm intentionally handling the different parts of #998 in separate PRs to make merging easier. 
- I removed the empty input `UserError` from `CommentUpdate`, since `id` is non-null and its exclusion will already throw a GraphQL error.
Where has this been …
=> feat: allow global/db ids in comment mutation ID inputs

src/Data/MediaItemMutation.php, src/Mutation/MediaItemCreate.php, src/Mutation/MediaItemDelete.php, src/Mutation/MediaItemUpdate.php, tests/wpunit/MediaItemMutationsTest.php
This PR enables users to supply either a database ID or a global ID to mediaItem mutation inputs of type ID. Part of https://github.com/wp-graphql/wp-graphql/issues/998 .
…
The `mutate_and_get_payload` methods were also refactored to bail earlier on failure and to remove some code duplication. 
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php8.0.15)
**WordPress Version:** 5.9.2
=> feat: allow global/db ids in mediaItem mutation ID inputs

src/Registry/TypeRegistry.php, src/Type/ObjectType/SettingGroup.php, tests/wpunit/SettingQueriesTest.php
This fixes a bug where fields could not be registered to GraphQL Types that are added to the Schema from the register_settings API. 
closes #2381 
Pushed it up with a failing test: https://github.com/wp-graphql/wp-graphql/runs/6459066904?check_suite_focus=true#step:9:463
Then the code that gets the tests to all pass: https://github.com/wp-graphql/wp-graphql/runs/6459071170?check_suite_focus=true#step:9:462
=> (bugfix): #2381 register field to setting group not working

src/Data/NodeResolver.php, tests/wpunit/NodeByUriTest.php
- fixes bug in NodeResolver where the instance of Wp class wasn't being passed properly as a reference
- adds test to ensure filter runs and properly returns the $wp instance
closes #2377
=> (bugfix): #2377 - fixes bug where Wp class wasn't being properly passed as reference to parse_request filter

src/Model/MenuItem.php, src/Mutation/MediaItemUpdate.php, src/Type/ObjectType/MenuItem.php, tests/wpunit/MenuItemQueriesTest.php
This fixes an issue with using wp-graphql in a WordPress multisite using subdirectories where the individual site subdirectory is included with the menu path.
https://github.com/wp-graphql/wp-graphql/issues/2362
**Before**
**After**
**Operating System:** macOS 12.3.1
**WordPress Version:** 5.9.2
=> Add relative `uri` to MenuItem

src/Type/Enum/MenuNodeIdTypeEnum.php, src/Type/ObjectType/RootQuery.php, tests/wpunit/MenuQueriesTest.php
This PR add the ability for user to query a menu by its provided `slug` and `location`.
Also backfilled tests for querying `menu` by all possible `idType`s.
#1458
No tests were added for `menu.isRestricted`. I'm unclear under what circumstances a menu would be considered restricted.
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php 8.0.15 )
**WordPress Version:** 5.9.3
=> Feat: query `menu` by `SLUG` and `LOCATION`.

.github/workflows/deploy-docker-image.yml, .github/workflows/testing-integration.yml
This updates the testing workflow to run tests with WordPress 6.0
It doesn't add 6.0 to the matrix because all of the versions of the matrix are not available as WordPress images on Dockerhub
This also updates our Docker deploy script to deploy Docker images of WPGraphQL
closes #2397
=> - update tests to run in php 8.1 with WP 6.0

CHANGELOG.md, package.json, readme.txt, src/WPGraphQL.php, wp-graphql.php
- ([#2416](https://github.com/wp-graphql/wp-graphql/pull/2416)): Fixes schema artifact workflow in Github.
=> Release v1.8.4

CHANGELOG.md, package.json, readme.txt, src/Utils/Tracing.php, src/WPGraphQL.php, tests/wpunit/TracingTest.php, wp-graphql.php
- ([#2427](https://github.com/wp-graphql/wp-graphql/pull/2427)): Fixes a regression of the 1.8.3 release where there could be fatal errors when GraphQL Tracing is enabled and a queryId is used as a query param.
=> Release v1.8.6

src/Request.php
For when using the graphql() function directly to invoke a request, ie, during unit testing, queryId is not honored/processed.  The query string is empty and the parser throws error on the query string.
This filter allows the graphql() invocation, which uses the execute() function to return a query string. The smart cache plugin can use this callback filter to look for queryId when the query string is not present in the params and look up a saved query string.
…
(If it’s long, please paste to …
=> Add filter in execute() for query string

src/Connection/PostObjects.php, tests/wpunit/TermNodeTest.php
This PR makes contentNodes field available for all the custom taxonomies.
Closes: [ContentNodes field is not available for custom taxonomies](https://github.com/wp-graphql/wp-graphql/issues/2441).
Before:
After:
=> fix: contentNodes field is not available for custom taxonomies #2441

phpcs.xml.dist, src/Data/Connection/PluginConnectionResolver.php
This PR fixes a mistake with the `phpcs.xml.dist` config, where PHPCompatibilityWP was not correctly checking againt PHP v7.1.
Also fixes an extraneous comma that was throwing a fatal error in PHP 7.2
…
Proof linting is working from before the bugfix.
Our `composer.lock` and several dependencies arent compatible with WP 7.1 either... Will open a separate issue to address.
**Operating System:** Ubuntu 20.04 (WSL2 …
=> Chore:fix PHPCompatibilityWP lint config

.github/workflows/code-quality.yml, .github/workflows/wordpress-coding-standards.yml, composer.json, composer.lock, docs/testing.md
This PR instructs composer.json to use ~`PHP 7.4`~ `PHP 7.3` when building the dependency list, and updates workflows to use `composer install`.
#2451
Codeception\stub v4.x requires PHP 7.4 and breaks tests. `composer update` doesnt seem to lower the child dependency for some reason. Since there's no major version differences to our root `dev-dependencies` between 7.3 -> 7.4, it makes sense to use that lower version, so we can continue to test against it.
Where has …
=> chore: build deps for PHP 7.3

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/lint-pr.yml
This adds a workflow to validate PR titles when PRs are opened. 
closes #988
=> ci: add linter to ensure PR titles adhere to conventional commit standards

src/Model/Comment.php, src/Type/ObjectType/Comment.php, tests/wpunit/CommentObjectQueriesTest.php
This PR fixes the resolver for the `Comment.author` connection. 
The current code will only load User objects if the user is logged in. This isn't expected behavior. Instead, the connection should try to load a User and return it if it's considered a public node, otherwise fallback to a CommentAuhor.
closes #2448
related: #1139
BEFORE:
For non-authenticated requests, the comment author was _always_ loading a `CommentAuthor` type
AFTER:
Now a non-authenticated request will return a mix of `User` and …
=> fix: #2448 - Fixes Comment.author connection resolver to properly load both User and CommentAuthor types

docs/testing.md
Update the testing instructions with how to use the codeception command in the docker environments, different PHP and WP versions, etc.
…
…
=> docs: update documentation for docker testing 

src/Data/NodeResolver.php, tests/wpunit/NodeByUriTest.php
This fixes a bug where the incorrect Type is returned when a page is set as the "page_for_posts" value. 
closes #1687 
When a Page is set as the "page_for_posts" setting under Reading Settings:
Querying the path for that page should return a `ContentType` and not the `Page`
Much like visiting the path in the browser returns the "blog" archive with the posts, instead of a static page: 
If the reading settings do not have a `page_for_posts` set
Then a `Page` type should be returned:
Much like you would see when visiting the WordPress rendered URL:
=> fix: #1687 fix node resolver when page for posts is set

src/Type/ObjectType/CommentAuthor.php, tests/wpunit/CommentObjectQueriesTest.php
This PR ensures the `CommentAuthor` avatar url is visible to unauthenticated users.
It solves this by using the `commentID` (stored as the `CommentAuthor`'s `databaseId`) to fetch the email if the user can't access the CommentAuthor's email directly.
Additionally, Comments without a valid email will now have their `avatar` return `null`, instead of returning a malformed `avatar.url`.
#2421 …
=> fix: return CommentAuthor avatar urls to unauthenticated users

packages/graphiql-auth-switch/AuthSwitch.js, tests/e2e/graphiql.spec.js
Tiny tweaks to the “switch to [public|logged-in] user” button in GraphiQL to:
1. Style it as a button to make it more obvious that you can interact with it (I've helped a couple of users toggle to a logged-in user to fix unexpected query results because they didn't realise they could toggle user state via that button).
2. Make the button focusable/keyboard-accessible and add ARIA text to describe to screen readers what it does.
Also extends existing e2e tests with coverage for the user toggle button.
#2372  …
=> fix: make GraphiQL user switch accessible

src/Registry/TypeRegistry.php, src/Type/Enum/CommentNodeIdTypeEnum.php, src/Type/ObjectType/RootQuery.php, tests/wpunit/CommentObjectQueriesTest.php
Adds `idType` arg to `RootQuery.comment` field, enabling querying by either global (default) or database ID.
closes #2395 
…
**Operating System:** Ubuntu 20.04 (WSL2 + devilbox + php 8.0.19)
=> feat: add `idType` arg to `RootQuery.comment`

src/Model/Theme.php, tests/wpunit/ThemeObjectQueriesTest.php
This PR broadens the allowed capabilities for accessing the Theme model to `'edit_themes' || 'switch_themes' || 'update_themes'`.
The premise for this change is that the existing `edit_themes` is too specific, as it refers to the ability to edit theme _files_ in the backend. However, we don't want to just change it to `switch_themes`, since the likelihood of a headless site disabling individual theme capabilities site-wide is fairly high and individualized, meaning we cant assume some sort of capability hierarchy.
Closes #2292 …
=> fix: check for multiple theme capabilities on Theme::is_private()

src/Type/ObjectType/MediaDetails.php, tests/wpunit/MediaItemQueriesTest.php
This PR allows users to filter the list of `MediaSize` objects returned by `MediaDetails.sizes` by specifying a list of `MediaItemSizeEnum`s to `include` or `exclude`, to allow for more performant queries without unnecessary over-fetching.
When `include` and `exclude` are used together, `exclude` will take precedence.
```graphql
{
mediaItems {
nodes {
mediaDetails {
sizes(include: [LARGE, THUMBNAIL], exclude: THUMBNAIL) {
sourceUrl
name
}
}
}
}
}
```
will only return `LARGE` image sizes.
Closes #889 
Any …
=> feat: add `include` and `exclude` args to `MediaDetails.sizes`

src/Data/NodeResolver.php, src/Model/Post.php, src/Type/ObjectType/RootQuery.php, tests/wpunit/PageByUriTest.php
This fixes a bug where querying a page by uri was improperly returning a page node instead of null when that page has been set to be the Posts Page. 
More detailed explanation here: https://github.com/wp-graphql/wp-graphql/issues/2486#issuecomment-1231967361
Closes #2486 
=> fix: bug when querying page set as "Posts Page"

src/Connection/MenuItems.php, src/Connection/PostObjects.php, src/Type/ObjectType/RootQuery.php
This PR changes the description for `id` input arguments of type `Int` to specify that they take a WP database ID.
These input args _cannot_ be handled by #2340 , as they require a breaking change to the GraphQL type.
#1095 ( the rest of that issue is superseded by #998 / which will be resolved by #2340 )
… …
=> fix: specify when `id` arg takes an (int) database ID

src/Mutation/ResetUserPassword.php, tests/wpunit/UserObjectMutationsTest.php
This PR logs in the user after they successfully `resetUserPassword`, as they have successfully authenticated themselves.
This gives them permissions to see their own `user` data in the GraphQL response.
#2100 
Discussion may still be necessary to decide both if we should return the user at all and whether logging in the user is the best way to do it. But it was a simple PR, and I had …
=> feat: login user after successful `resetUserPassword` mutation

access-functions.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Mutation/MediaItemUpdate.php, src/Request.php, src/Router.php, src/Type/ObjectType/Avatar.php, src/Type/ObjectType/Comment.php, src/Type/ObjectType/CommentAuthor.php, src/Type/ObjectType/ContentType.php, src/Type/ObjectType/Menu.php, src/Type/ObjectType/MenuItem.php, src/Type/ObjectType/Plugin.php, src/Type/ObjectType/PostObject.php, src/Type/ObjectType/Taxonomy.php, src/Type/ObjectType/TermObject.php, src/Type/ObjectType/Theme.php, src/Type/ObjectType/User.php, src/Type/ObjectType/UserRole.php, src/Type/WPUnionType.php, src/Utils/QueryAnalyzer.php, src/Utils/Utils.php, src/WPGraphQL.php, tests/functional/GraphQLHeadersCept.php, tests/wpunit/AccessFunctionsTest.php, tests/wpunit/NodesTest.php, tests/wpunit/QueryAnalyzerTest.php, tests/wpunit/UtilsTest.php
This introduces a new "QueryAnalyzer" that tracks Types, Models and Nodes that are queried and returned in any given GraphQL Request, then returns those values in the headers. 
For example, making a query like so `/graphql?query={posts(first:5){nodes{id,title}}}` will return headers like so: 
```bash
X-GraphQL-Keys: list:post cG9zdDoxMTY3 cG9zdDoxMTM1 cG9zdDoxMTIw cG9zdDoxMTA5 cG9zdDoxMDk3 graphql:Query d43c3d17aeaf76b21e747f5350a36262
X-GraphQL-Keys-Size: 121
X-GraphQL-List-Types: list:post
X-GraphQL-Nodes: cG9zdDoxMTY3 cG9zdDoxMTM1 cG9zdDoxMTIw cG9zdDoxMTA5 cG9zdDoxMDk3
X-GraphQL-Operation-Type: Query
X-GraphQL-Query-ID: d43c3d17aeaf76b21e747f5350a36262
```
Does this close any …
=> feat: Add QueryAnalyzer and Expose "X-GraphQL-Keys" in headers

src/Data/Connection/AbstractConnectionResolver.php
This PR deprecates the `AbstractConnectionResolver::getArgs()` in favor of `AbstractConnectionResolver::get_args()`, which is passed through the `graphql_connection_args` WP filter on instantiation.
This PR replaces part of #2340 , and lays the foundation to create the individual PRs necessary to close #998 in a piecemeal approach, by allowing child `ConnectionResolver` classes and 3rd-party code to manipulate connection arg values. before they are used in the resolver.
…
(If it’s long, please paste to …
=> chore: refactor `AbstractConnectionResolver::$args` handling

src/Connection/Comments.php, src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/CommentConnectionResolver.php, tests/wpunit/CommentConnectionQueriesTest.php
This PR allows Comment connection where args with a type `ID` to accept either global IDs or database IDs.
This PR replaces #2340 , and requires #2521 to be merged as a prerequisite.
Part of #998
…
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php 8.0.19)
=> feat: allow global/database IDs in Comment connection where args `ID` inputs

src/Connection/MenuItems.php, src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/MenuItemConnectionResolver.php, tests/wpunit/MenuItemConnectionQueriesTest.php
This PR allows Comment connection where args with a type ID to accept either global IDs or database IDs.
This PR replaces https://github.com/wp-graphql/wp-graphql/pull/2340 , and requires https://github.com/wp-graphql/wp-graphql/pull/2521 to be merged as a prerequisite.
Part of https://github.com/wp-graphql/wp-graphql/issues/998
The `testMenuItemsQueryWithChildItemsUsingDatabaseParentId` …
=> feat: allow global/database IDs in MenuItem connection where args ID inputs

src/Connection/TermObjects.php, src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php, tests/wpunit/TermObjectConnectionQueriesTest.php
This PR allows Term connection where args with a type ID to accept either global IDs or database IDs.
It also deprecates the `termTaxonomId` where arg, in favor of the correctly-spelled `termTaxonomyId`.
This PR replaces https://github.com/wp-graphql/wp-graphql/pull/2340 , and requires https://github.com/wp-graphql/wp-graphql/pull/2521 to be merged as a prerequisite.
Part of https://github.com/wp-graphql/wp-graphql/issues/998 …
=> feat: allow global/database IDs in Term connection where args ID inputs 

src/Connection/PostObjects.php, src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, tests/wpunit/PostObjectConnectionQueriesTest.php, tests/wpunit/PostObjectQueriesTest.php
This PR allows Term connection where args with a type ID to accept either global IDs or database IDs.
Additionally, the descriptions of `tagSlugAnd` and `tagSlugIn` have been updated to better convey what they actually do.
This PR replaces https://github.com/wp-graphql/wp-graphql/pull/2340 , and requires https://github.com/wp-graphql/wp-graphql/pull/2521 to be merged as a prerequisite.
Part of https://github.com/wp-graphql/wp-graphql/issues/998
(If it’s long, please paste to https://ghostbin.com/ and …
=> feat: allow global/database IDs in Post connection where args ID inputs

src/Request.php, src/Utils/QueryAnalyzer.php
This is a follow-up to https://github.com/wp-graphql/wp-graphql/pull/2519
- return unique lists for get_list_types, get_query_types, get_runtime_nodes
- add filter before runtime node is determined, allows keying the node differently by 3rd party plugins
related: #2516
related: #2519
=> fix: ensure responses in QueryAnalyzer are unique

src/Data/Connection/MenuItemConnectionResolver.php, tests/wpunit/MenuItemConnectionQueriesTest.php
This fixes a regression where using 0 as the `parentId` for menuItem queries is no longer returning only menuItems with no parent set. 
closes #2530 
Failing test run: https://github.com/wp-graphql/wp-graphql/actions/runs/3100423158/jobs/5020687861#step:7:270
Failing test commit: https://github.com/wp-graphql/wp-graphql/pull/2532/commits/0575f93646418488c27140c4c301084b29fa22ad
Passing test run: https://github.com/wp-graphql/wp-graphql/actions/runs/3100510553/jobs/5020872900
Passing test commit: https://github.com/wp-graphql/wp-graphql/pull/2532/commits/667558891c …
=> fix: regression to menuItem queries when parentId is 0

CHANGELOG.md, readme.txt, src/Data/Connection/MenuItemConnectionResolver.php, src/WPGraphQL.php, tests/wpunit/MenuItemConnectionQueriesTest.php, wp-graphql.php
- ([#2530](https://github.com/wp-graphql/wp-graphql/pull/2530)): Fixes a regression introduced in v1.11.0 where querying menuItems with parentId where arg set to 0 was returning all menuItems instead of just top level items.
=> release: v1.11.1

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, readme.txt, src/Admin/GraphiQL/GraphiQL.php, src/Utils/QueryAnalyzer.php, src/WPGraphQL.php, wp-graphql.php
- ([#2551](https://github.com/wp-graphql/wp-graphql/pull/2551)): Chunks X-GraphQL-Keys header into multiple headers under a set max header limit length.
- ([#2539](https://github.com/wp-graphql/wp-graphql/pull/2539)): Set IDE direction to prevent breaks in RTL mode. Thanks @justlevine!
- ([#2549](https://github.com/wp-graphql/wp-graphql/pull/2549)): Fix bug_report.yml field to be textarea instead of input. Thanks @justlevine!
=> release: v1.11.2

CHANGELOG.md, readme.txt, src/Utils/QueryAnalyzer.php, src/Utils/Utils.php, src/WPGraphQL.php, wp-graphql.php
- ([#2555](https://github.com/wp-graphql/wp-graphql/pull/2555)): Further changes to `X-GraphQL-Keys` header output. Truncate keys based on a filterable max length. Output the skipped keys in extensions payload for debugging, and add `skipped:$type` keys to the X-GraphQL-Keys header for nodes that are skipped.
=> release: v1.11.3

bin/install-test-env.sh
This PR changes `install-test-env.sh` to use `.env` variables for the `wp core install` command, allowing testers to spinup a test site using whatever `url` etc that is convenient for them, instead of `wp.test`.
*Note*: Based on the current `.env.dist`, the generated install will now default to`localhost` and not `wp.test` and the admin email to `admin@example.com` instead of `admin@wp.test`. If people want to use those old values nstead, they shold update their local .env file.
…
(If it’s long, please …
=> chore: use ENV variables for installing WordPress test environment

src/Registry/Utils/TermObject.php
This PR fixes the PHPStan error in the latest merges to develop in prep for `v1.12.0`
`isset( $parsed = myFunc() )` will always return true, so we more explicitly check that wp_parse_url( $term->link ) gives us a valid array.
…
…
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + PHP 8.0.19)
=> fix: (phpstan) check if wp_parse_url() returns array

src/Utils/QueryAnalyzer.php, tests/functional/GraphQLHeadersCept.php
This update visitor in the QueryAnalyzer to find the "node" type that's being queried in a list and add it to the keys instead of adding the "edge" type.
closes #2589 
The following query:
```graphql
{
posts(first:5) { 
edges { 
node { 
id
title
}
}
}
}
```
Would produce the following X-GraphQL-Keys:
```bash
b682e8e049ae0f0a6c6c65d66a42af48 graphql:Query 
list:rootquerytopostconnectionedge cG9zdDoxMTY3 
cG9zdDoxMTM1 cG9zdDoxMTIw cG9zdDoxMTA5 cG9zdDoxMDk3
```
The same query produces the following …
=> fix: Add list of node types as X-GraphQL-Keys instead of list of edge types

src/Utils/Utils.php
This changes the hash for the queryId to use sha256 by default instead of md5. 
The algorithm is filterable to support any algorithm compatible with the php `hash()` function.
This plays nicer with the existing "standard" set by Apollo's Automated Persisted Queries functionality
closes #2584 
=> feat: use sha256 instead of md5 for hashing the queryId

src/Type/WPConnectionType.php
This passes `deprecationReason` from `register_graphql_connection` config array through to the fields that are registered to create the connection.
closes #2579 
**BEFORE**
Registering a connection with a `deprecationReason` DOES NOT deprecate the field(s) that were registered to create the connection:
**AFTER**
Registering a connection with a `deprecationReason` deprecates the field(s) that were registered to create the connection:
=> feat: support deprecation reason on connections

src/Mutation/SendPasswordResetEmail.php, tests/wpunit/UserObjectMutationsTest.php
This PR refactors `SendPasswordResetEmail` to both provide a valid indicator of the mutation's `success`, as well as obfuscate any errors that could be used to enumerate valid users on the site, by logging them with `graphql_debug()` instead of throwing an exception.
- chore: Refactor `SendPasswordResetEmail` registration config to use static methods.
- feat: add the `success` field to `SendPasswordResetEmailPayload`.
- feat: deprecate the `user` field from `SendPasswordResetEmailPayload`.
- feat: log `SendPasswordResetEmail` mutation errors with `graphql_debug()` to prevent user enumeration.
closes …
=> feat: Obfuscate `SendPasswordResetEmail` response.

.github/workflows/code-quality.yml, .github/workflows/testing-integration.yml, .github/workflows/wordpress-coding-standards.yml, bin/run-docker.sh, docker-compose.yml, docs/testing.md, readme.txt, wp-graphql.php
This PR bumps the WP version to test against to v6.1. The test matrices were also cleaned up, (per: https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/).
...
The default PHP version has also been bumped to 8.1 (since 7.4 sunsets this month).
**Operating System:** Ubuntu 20.04 (WSL2 + devilbox …
=> chore: bump tested WP version to v6.1

src/Connection/Users.php
This updates the resolvers for user connections to check the values of the author databaseId more strictly before using it to resolve. If the value is empty, we can prevent resolution altogether and return null.
Follow-up to: #2605
=> fix: failing tests for restricted user queries in wp 6.1

.github/workflows/code-quality.yml, .github/workflows/testing-integration.yml, .github/workflows/wordpress-coding-standards.yml, CHANGELOG.md, bin/run-docker.sh, docker-compose.yml, docs/testing.md, package-lock.json, readme.txt, src/AppContext.php, src/Connection/Users.php, src/Data/Config.php, src/Data/Connection/AbstractConnectionResolver.php, src/Data/Cursor/CommentObjectCursor.php, src/Data/Cursor/PostObjectCursor.php, src/Data/Cursor/TermObjectCursor.php, src/Data/Cursor/UserCursor.php, src/Data/DataSource.php, src/Data/Loader/AbstractDataLoader.php, src/Mutation/SendPasswordResetEmail.php, src/Router.php, src/Type/Union/MenuItemObjectUnion.php, src/Types.php, src/WPGraphQL.php, tests/wpunit/UserObjectMutationsTest.php, wp-graphql.php
- ([#2541](https://github.com/wp-graphql/wp-graphql/pull/2541)): feat: Obfuscate SendPasswordResetEmail response. Thanks @justlevine!
- ([#2544](https://github.com/wp-graphql/wp-graphql/pull/2544)): chore: log and cleanup deprecations. Thanks @justlevine!
- ([#2605](https://github.com/wp-graphql/wp-graphql/pull/2605)): chore: bump tested version of WordPress to 6.1. Thanks @justlevine!
- ([#2606](https://github.com/wp-graphql/wp-graphql/pull/2606)): fix: update resolver in post->author connection to be more strict about the value of the author ID
- ([#2609](https://github.com/wp-graphql/wp-graphql/pull/2609)): chore(deps): bump loader-utils from 2.0.2 to 2.0.3
=> release: v1.12.2

composer.json, composer.lock, phpstan.neon.dist, src/Data/Connection/PluginConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/NodeResolver.php, src/Model/MenuItem.php, src/Type/Enum/TimezoneEnum.php, src/Type/ObjectType/TermObject.php
This PR moves the logic used in `NodeResolver::resolve_uri()` to mimic [`WP::parse_request()`](https://github.com/WordPress/wordpress-develop/blob/6.0.2/src/wp-includes/class-wp.php#L135) into its own method.
This is in lieu of #2342, as the fragility of `resolve_uri()` and lack of unit testing make it hard to ship multiple changes to that method at once. However, since this particular piece of code is dictated externally and includes no change in behavior to the user, we can merge this now to pave the way for a more stable experience.
Supersedes #2342 
This pr …
=> chore: move `parse_request()` logic from `NodeResolver::resolve_uri()` to its own method.

src/Data/CommentMutation.php, src/Model/Comment.php, src/Mutation/CommentCreate.php, src/Registry/TypeRegistry.php, src/Type/Enum/CommentStatusEnum.php, src/Type/Enum/CommentsConnectionOrderbyEnum.php, src/Type/ObjectType/Comment.php, tests/wpunit/CommentMutationsTest.php, tests/wpunit/CommentObjectQueriesTest.php
This PR deprecates the `approved` Field from the `Comment` model, object, and mutation inputs in favor of the `status` field, which uses the new `CommentStatusEnum`.
Despite its name `WP_Comment->comment_approved`, actually contains 4 possible stati and allows for 6 different values (`'0'` = `hold`, and `'1'` = `approved`). However, WPGraphQL treats it as a boolean, which has some interesting side effects like #807. 
- feat: add `CommentStatusEnum` GraphQL type.
- feat: deprecate `approved` field from `Comment` model, object, and mutations in favor of `status: CommentStatusEnum` field.
- fix: correctly set comment status when using Create/Update mutations.
Does this close any currently …
=> fix: deprecate Comment `approved` field in favor of `status: CommentStatusEnum` 

access-functions.php, composer.json, composer.lock, phpstan.neon.dist, src/Data/Connection/PluginConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/NodeResolver.php, src/Model/MenuItem.php, src/Registry/TypeRegistry.php, src/Type/Enum/TimezoneEnum.php, src/Type/ObjectType/TermObject.php, tests/wpunit/AccessFunctionsTest.php, tests/wpunit/UserObjectMutationsTest.php
This PR adds the `register_graphql_edge_field()`, `register_graphql_edge_fields()`, `register_graphql_connection_where_arg()` and `register_graphql_connection_where_args()` access functions, making it easier to add fields to Connection `edges` and `where` args without needing to know the generated GraphQL type names.
It also cleans up some extraneous conditional logic in `TypeRegistry::get_fields()`, and backfills a WPUnit test for `register_graphql_fields()`
Closes #1522, closes #1214
(If it’s long, …
=> feat: add `register_graphql_edge_fields()` and `register_graphql_connection_where_args()` access functions

access-functions.php, src/Registry/TypeRegistry.php, src/Type/WPConnectionType.php, src/Type/WPUnionType.php, tests/wpunit/AccessFunctionsTest.php
The PR adds a new access method: `deregister_graphql_type( string $type_name ) : void;` for removing a GraphQL type _and all of its references_ from the schema.
The function uses on a new `graphql_excluded_types` filter that prevents types (or fields that resolve to that type) from being registered, and then subsequently removes the type from the list of inherited interfaces by use of the existing `graphql_type_interfaces` filter.
- feat: added new `deregister_graphql_type()` access function.
- feat: add the `graphql_excluded_types` filter.
- feat: add the `graphql_wp_connection_type` action.
- dev: Call `WPConnectionType::register_connection()` from within the class constructor. (see …
=> feat: Add `deregister_graphql_type()` access function and corresponding `graphql_excluded_types` filter. 

src/Mutation/TermObjectUpdate.php, src/Registry/TypeRegistry.php, src/Type/WPMutationType.php
This PR refactors mutation registration to use the new `WPMutationType` class, in line with other GraphQL types and pseudo-types (like connections), paving the way for better extensibility.
- fix: `TermObjectUpdate` mutation names should start with lowercase.
- feat: Use `WPMutationType` to register mutations to the GraphQL schema.
- dev: Add the following filters: `graphql_wp_mutation_type_config`, `graphql_pre_mutate_and_get_payload`, `graphql_mutation_payload`.
- dev: Add the following action: `graphql_wp_mutation_type`.
… …
=> feat: refactor mutation registration to use `WPMutationType`

src/Registry/Utils/PostObject.php
This deprecates the `$postType.preview` connection for post types that are not publicly queryable, and limits the (not yet released) `Previewable` Interface to just `publicly_queryable` post types. 
closes #2621
=> fix: previews should only be on publicly queryable types

src/Registry/TypeRegistry.php, src/Type/WPMutationType.php, tests/wpunit/AccessFunctionsTest.php
This fixes a regression where registering a mutation with an uppercase first letter is added to the schema as a field with an uppercase first letter instead of being transformed to a lowercase-first letter.
- Failing Test: https://github.com/wp-graphql/wp-graphql/actions/runs/3568456806/jobs/5997350686#step:7:752
- Passing Test: https://github.com/wp-graphql/wp-graphql/actions/runs/3568686398/jobs/5997835419
closes #2624
=> fix: mutations being added to the schema without enforcing lowercase first letter

CHANGELOG.md, readme.txt, src/Registry/TypeRegistry.php, src/Type/WPMutationType.php, src/WPGraphQL.php, tests/wpunit/AccessFunctionsTest.php, wp-graphql.php
- ([#2625](https://github.com/wp-graphql/wp-graphql/pull/2625)): fix: Fixes a regression of v1.13.0 where mutations registered with an uppercase first letter weren't properly being transformed to a lowercase first letter when the field is added to the Schema.
=> release: v1.13.1

src/Connection/Comments.php, src/Connection/MenuItems.php, src/Connection/PostObjects.php, src/Connection/Taxonomies.php, src/Connection/TermObjects.php, src/Connection/Users.php
This PR restores the `WPGraphQL\Connection` classes removed in #2617 , as backwards-compatible deprecation wrappers for the new classes.
[Slack](https://wp-graphql.slack.com/archives/CCYJRDN4A/p1669679113213969)
- Since the class is static, each method needs to be deprecated (vs placing one notice in the constructor in an instance class).
- Not entirely sure if this is _worth_ doing, but …
=> fix: removed connection classes as deprecated wrappers (regression)

CHANGELOG.md, readme.txt, src/WPGraphQL.php, wp-graphql.php
- ([#2627](https://github.com/wp-graphql/wp-graphql/pull/2627)): fix: Fixes regression where Connection classes were moved to another namespace. This adds deprecated classes back to the old namespace to extend the new classes. Thanks @justlevine!
=> release: v1.13.2

src/Registry/TypeRegistry.php, tests/wpunit/AccessFunctionsTest.php
This fixes a regression which was causing fields registered with an underscore to be forcibly rewritten to camelCase instead of snake_case. 
While `camelCase` is the "preferred" casing, `snake_case` fields are allowed.
- **FAILING TEST:** https://github.com/wp-graphql/wp-graphql/actions/runs/3595866875/jobs/6055873341#step:7:104
- **PASSING TEST:** https://github.com/wp-graphql/wp-graphql/actions/runs/3595869832/jobs/6055878158#step:7:103
closes #2641
Given the following snippet:
```php
<?php …
```
=> fix: regression where fields on an object type are forced to be camelCase (snake_case) should still be allowed

src/Type/WPConnectionType.php
The `$toType . ConnectionEdge` Interfaces are being registered without properly defining the `node` field. 
This fixes the `node` field definition.
closes #2646
=> fix: properly register node field on $toType . ConnectionEdge interfaces

CHANGELOG.md, readme.txt, src/Registry/TypeRegistry.php, src/Type/WPConnectionType.php, src/WPGraphQL.php, tests/wpunit/AccessFunctionsTest.php, wp-graphql.php
- ([#2647](https://github.com/wp-graphql/wp-graphql/pull/2647)): fix: properly register the node field on ConnectionEdge interfaces
- ([#2645](https://github.com/wp-graphql/wp-graphql/pull/2645)): fix: regression where fields of an object type were forced to be camelCase. This allows snake_case fields again.
=> release: v1.13.5

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/MenuItemConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php
🚨 Please review the [guidelines for contributing](/.github/CONTRIBUTING.md) to this repository.
-->
Adds `original_args` parameter to hook for bypassing WP_Query argument sanitation.
…
… …
=> feat: `original_args` parameter added to `graphql_post_object_connection_args` hook

docker/app.Dockerfile
Building images for PHP version 7 fails because xdebug library dropped support for php 7. This change makes use of the last known working version for PHP 7.*.  Leaving PHP 8 to use latest xdebug library.
This error will be seen in github tests and local develop where a docker image is built.
[Drop PHP 7.3 and PHP 7.4 support](https://github.com/xdebug/xdebug/pull/849)
…
…
Where has this …
=> ci: Use last working version of xdebug for php7

docker/app.Dockerfile, docker/app.setup.sh, tests/acceptance/TwoDomainsSupportedCest.php
Add tests to verify the router changes in this [PR](https://github.com/wp-graphql/wp-graphql/pull/2182) are tested.
closes #2187 
I tested the version of the router.php code and these tests before that change in #2182 and these tests failed.
At this point a apache <VirtualHost> entry is not needed in the docker setup because the Apache ServerName localhost acts as a catchall for requests. …
=> test: Multiple domain tests

.github/workflows/lint-pr.yml, CHANGELOG.md, docker/app.Dockerfile, docker/app.setup.sh, package-lock.json, readme.txt, src/Registry/TypeRegistry.php, src/Type/WPMutationType.php, src/WPGraphQL.php, tests/acceptance/TwoDomainsSupportedCest.php, tests/wpunit/AccessFunctionsTest.php, tests/wpunit/CustomPostTypeTest.php, wp-graphql.php
- ([#2661](https://github.com/wp-graphql/wp-graphql/pull/2661)): chore(deps): bump simple-git from 3.10.0 to 3.15.1
- ([#2665](https://github.com/wp-graphql/wp-graphql/pull/2665)): chore(deps): bump decode-uri-component from 0.2.0 to 0.2.2
- ([#2668](https://github.com/wp-graphql/wp-graphql/pull/2668)): test: Multiple domain tests. Thanks @markkelnar!
- ([#2669](https://github.com/wp-graphql/wp-graphql/pull/2669)): ci: Use last working version of xdebug for php7. Thanks @markkelnar!
- ([#2671](https://github.com/wp-graphql/wp-graphql/pull/2671)): fix: correct regressions to field formatting forcing snake_cace and UcFirst fields to be lcfirst/camelCase
- ([#2672](https://github.com/wp-graphql/wp-graphql/pull/2672)): chore: update lint-pr workflow
=> release: v1.13.7

.github/workflows/sync-develop-with-master.yml
- add workflow to keep develop in sync with master after a push to master
closes #2674
=> ci: keep the develop branch in sync with master

src/Type/ObjectType/RootQuery.php
> Unexpected deprecation notice for WPGraphQL\Data\DataSource::resolve_user.
Function WPGraphQL\Data\DataSource::resolve_user is deprecated since version 0.8.4! Use Use $context->get_loader( 'user' )->load_deferred( $id ) instead. instead.
Failed asserting that an array is empty.
No!
This is currently failing unit tests from the BP extension. …
=> chore: remove deprecated use of `WPGraphQL\Data\DataSource::resolve_user()`

src/Utils/QueryAnalyzer.php, tests/wpunit/QueryAnalyzerTest.php
This prevents list types from being returned in the query analyzer if the type isn't a type that implements the `node` interface.
**failing test**: https://github.com/wp-graphql/wp-graphql/actions/runs/3897357240/jobs/6654945889
**passing test**: https://github.com/wp-graphql/wp-graphql/actions/runs/3897472140/jobs/6655191024
closes #2690
=> fix: prevent non-node types from being output in the query analyzer list type keys

src/Type/WPInterfaceTrait.php, tests/wpunit/InterfaceTest.php
- prevent the interface being registered from implementing itself
- **Failing Test**: https://github.com/wp-graphql/wp-graphql/actions/runs/3894753346/jobs/6649175397
- **Passing Test**: https://github.com/wp-graphql/wp-graphql/actions/runs/3894832627/jobs/6649360575
closes #2687 
With the following code in place:
```php
add_action( 'graphql_register_types', function () {
register_graphql_interface_type( 'InterfaceA', [
'interfaces' => [ 'Node', 'InterfaceA' ],
'fields' => [ 'fieldA' => [ 'type' => …
```
=> fix: prevent infinite recursion when an interface implements itself 

access-functions.php, composer.json, composer.lock, src/Data/Config.php, src/Data/Connection/PluginConnectionResolver.php, src/Data/NodeResolver.php, src/Request.php, src/Utils/InstrumentSchema.php, src/Utils/Tracing.php
This PR updates PHPStan and its associated extensions to their latest versions, and fixes newly-surfaced sniffs.
The majority of the newly-failed sniffs were due to action callbacks trying to return a value instead of `void`.
…
I ignored bc05256314b430e5d163f5ded0c2a47f7531ee6b instead of "fixing", since I'm unclear whether this is a code or a typedef error (and if `[]` is a valid logical …
=> fix: update PHPStan and fix newly-surfaced sniffs

src/Type/Enum/UsersConnectionSearchColumnEnum.php
…
Fixes a missing apostrophe to correct use an escape character. This breaks instropecting the schema.
closes https://github.com/wp-graphql/wp-graphql/issues/2703
```
Failed to load schema from kb.graphql:
Syntax Error: Invalid character escape sequence: "\s".
GraphQLError: Syntax Error: Invalid character escape sequence: "\s".
```
… …
=> fix: missing apostrophe after escape

src/Data/Connection/TermObjectConnectionResolver.php, src/Data/Connection/UserConnectionResolver.php
Fixes a deprecation warning `Function WPGraphQL\Types::map_input is <strong>deprecated</strong> since version 0.6.0! Use WPGraphQL\Utils\Utils::map_input() instead` when querying terms with any kind of condition.
fixes https://github.com/wp-graphql/wp-graphql/issues/2717
`PHP Deprecated:  Function WPGraphQL\Types::map_input is <strong>deprecated</strong> since version 0.6.0! Use WPGraphQL\Utils\Utils::map_input() instead.` …
=> fix: deprecation notice

tests/functional/GraphQLHeadersCept.php
As part of query cache headers/keys, test that the top level graphql query key is present on request.
… related to this [issue](https://github.com/wp-graphql/wp-graphql-smart-cache/issues/193) in smart cache.
…
=> fix: Add test for the graphql all query key in headers

CHANGELOG.md, readme.txt, src/Type/WPConnectionType.php, src/WPGraphQL.php, tests/wpunit/CustomPostTypeTest.php, tests/wpunit/CustomTaxonomyTest.php, wp-graphql.php
- [#2726](https://github.com/wp-graphql/wp-graphql/pull/2726): fix: invalid schema when custom post types and custom taxonomies are registered with underscores in the "graphql_single_name" / "graphql_plural_name"
=> release: v1.13.9

src/Data/NodeResolver.php, src/Type/ObjectType/RootQuery.php, tests/wpunit/ContentNodeInterfaceTest.php, tests/wpunit/NodeByUriTest.php, tests/wpunit/PageByUriTest.php, tests/wpunit/PostObjectQueriesTest.php, tests/wpunit/TermNodeTest.php, tests/wpunit/TermObjectQueriesTest.php, tests/wpunit/UserObjectQueriesTest.php
This pr refactors `NodeResolver::resolve_uri()` to use `WP_Query`, instead of the current approach where we try to replicate the class logic locally.
This brings the resolution process more in line with `WP::main()`, mitigating edge cases and reducing code complexity.
In addition, it adds the following WP filters to the method:
- `graphql_resolve_uri_query_class` . Used to swap out WP_Query with a specialized class, e.g. `WC_Query` from woo.
- `graphql_resolve_uri` . Used to short-circuit `resolve_uri()` after the query has been run, but before our own attempts to resolve it to a WPGraphQL `node`, e.g. if we want a CPT to use a special dataloader.
- `graphql_post_resolve_uri`. Used to …
=> feat: Refactor NodeResolver::resolve_uri() to use WP_Query

docker/testing.entrypoint.sh
When running tests, specifying any value for DEBUG env variable, enables codeception debug mode.  Allow DEBUG=0 to not enable debug mode for tests.  Actually, only enable debug when DEBUG=1 or DEBUG=true.
…[issue](https://github.com/wp-graphql/wp-graphql/issues/2734)
…
=> fix: Explicitly check for DEBUG enabled value for tests

tests/wpunit/PluginConnectionQueriesTest.php, wp-graphql.php
This WordPress plugin's header currently has the [Plugin Name set as **WP GraphQL**](https://github.com/wp-graphql/wp-graphql/blob/develop/wp-graphql.php#L3) (w/space),
with mostly all other references reading as **WPGraphQL** (w/o space).
These changes **ONLY** update the Plugin Name within the plugin's [header fields](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#header-fields) (+  Appsero),
which will be displayed in the Plugins list in the WordPress Admin.
Note that this name is returned when using the WordPress core function [get_plugin_data()](https://developer.wordpress.org/reference/functions/get_plugin_data/),
however I did not find any use of that …
=> fix: Remove space from plugin name

.github/stale.yml
This PR changes the stalebot configuration to no longer automatically close issues, preventing the quarterly "stalepocalypse", where dozens of issues are unceremoniously closed, flooding maintainers with a deluge of notifications, and forcing them to comb through them all or risk them being swept under the rug for good.
Once merged, the following changes to the "triage flow" will take effect:
1. Immediately: the `stale` label will be deleted and replaced by `stale?` on existing issues. (manual task: assigned to @justlevine )
2. After 90 days, issues with no activity will be marked `stale?`.
3. New activity on a `stale?` issue will automatically remove the `stale?` label.
4. Contributors …
=> ci: stop the stalepocalypse 🤖

.github/stale.yml, CHANGELOG.md, readme.txt, src/WPGraphQL.php, tests/wpunit/PluginConnectionQueriesTest.php, wp-graphql.php
- [#2741](https://github.com/wp-graphql/wp-graphql/pull/2741): Change the plugin name from "WP GraphQL" to "WPGraphQL". Thanks @josephfusco!
- [#2742](https://github.com/wp-graphql/wp-graphql/pull/2742): Update Stalebot rules. Thanks @justlevine!
=> release: v1.13.10

access-functions.php, src/Registry/TypeRegistry.php, src/Request.php, src/Type/WPConnectionType.php, src/Utils/Utils.php
**NOTE**: this PR is into the 1.14.0 release branch, replacing [this PR](https://github.com/wp-graphql/wp-graphql/pull/2737) to develop.
This allows fields, connections and mutations to be registered with underscores and have the underscores be preserved when the field is added to the Schema. 
closes #2736 
Given the following snippet: 
```php
register_graphql_object_type( 'TestObject', [
'eagerlyLoadType' => true,
'fields' => [
'test' => [ 'type' => 'String' ],
]
]);
register_graphql_field( 'TestObject', …
```
=> feat: allow fields to be registered with underscores

src/Type/ObjectType/RootQuery.php, src/WPGraphQL.php, tests/wpunit/CustomPostTypeTest.php, tests/wpunit/CustomTaxonomyTest.php
This allows post types/taxonomies to be registered to show_in_graphql without requiring `graphql_plural_name` (graphql_single_name) is still required.
closes #2754 
Registering a post type like so: 
```php
add_action( 'init', function() {
register_post_type( 'test_type', [
'label' => 'Test Type',
'public' => true,
'show_in_graphql' => true,
'graphql_single_name' => 'testType',
]);
});
```
This PR also converts the hard UserError that's thrown and changes it to a …
=> fix: Allow post types and taxonomies to be registered without graphql_plural_name

.github/workflows/deploy-docker-image.yml, .github/workflows/testing-integration.yml, bin/run-docker.sh, docker-compose.yml, docs/testing.md, tests/_data/config.php, tests/wpunit/CustomPostTypeTest.php, tests/wpunit/EnqueuedScriptsTest.php, tests/wpunit/EnqueuedStylesheetsTest.php, tests/wpunit/MediaItemQueriesTest.php, tests/wpunit/PostObjectQueriesTest.php, tests/wpunit/PreviewTest.php, wp-graphql.php
This PR updates the various ci matrices to test against WordPress 6.2
It also fixes two WPUnit test issues that were causing codeception to fail locally:
- tests: Cleans up schema after `testRegisterPostTypeWithoutGraphqlPluralNameIsValid()`, to prevent a `GraphQL\UserError` when running later tests.
- tests: Removed extraneous `/` when concatenating paths with the `WPGraphQL_PLUGIN_DIR` constant.
… …
=> ci: test against WordPress v6.2

src/Type/Union/PostObjectUnion.php, src/Type/Union/TermObjectUnion.php
…
This PR calls `_doing_it_wrong()` when using the deprecated `PostObjectUnion`/`TermObjectUnion` GraphQL types.
These type earned a `@deprecated` tag in #2617 
…
As far as I can tell, beyond the `@deprecated` tag, no other indications that these types were deprecated are in the codebase, nor was it mentioned in the release notes. As such, I'm conflicted whether we should backdate the …
=> chore: call `_doing_it_wrong()` when using deprecated `{PostObject|TermObject}Union`

src/Mutation/CommentCreate.php, src/Mutation/CommentRestore.php, src/Mutation/MediaItemCreate.php, src/Registry/TypeRegistry.php, src/Type/ObjectType/RootQuery.php, tests/wpunit/NodeByUriTest.php, tests/wpunit/PostObjectQueriesTest.php
Removes the internal usage of several deprecated function calls:
- `DataSource::resolve_comment()`
- `DataSource::resolve_post_object()`
- `DataSource::resolve_term_object()`
- `Types::prepare_date_response()`
No
As far as I can tell, this removes the last usages of deprecated methods in core. 
**Operating System:** Ubuntu 20.04 …
=> chore: remove internal usage of deprecated functions

src/Registry/Utils/TermObject.php, src/Type/Connection/PostObjects.php, tests/wpunit/PostObjectConnectionQueriesTest.php, tests/wpunit/TermObjectConnectionQueriesTest.php
This PR fixes the wrong order in the ancestor's resolvers for terms and posts.
- Terms: The default order in [TermObjectConnectionResolver](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/TermObjectConnectionResolver.php#L79) is `$query_args['orderby'] = 'name';`. The [ancestors resolver](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Registry/Utils/TermObject.php#L179) uses `$resolver->set_query_arg( 'include', $ancestor_ids );` that requires `$resolver->set_query_arg( 'orderby', 'include' );` in other to preserve the [initial order from](https://developer.wordpress.org/reference/functions/get_ancestors/) `get_ancestors` function.
- Post: The …
=> fix: wrong order in term and post ancestors.

src/Data/NodeResolver.php, tests/wpunit/NodeByUriTest.php
This fixes a bug in the NodeResolver where querying the posts page prevents the node from fully resolving properly. 
failing test: https://github.com/wp-graphql/wp-graphql/actions/runs/4745816863/jobs/8428653391?pr=2792#step:8:816
passing test: https://github.com/wp-graphql/wp-graphql/actions/runs/4745911977/jobs/8428890823?pr=2792#step:8:813
closes #2791
**BEFORE**
I can query a node by URI and get the node back, but the node returns `null` for the uri field 🤔. This is a bug. If a node can be identified by a uri, the node has a uri. 
**AFTER**
The uri field is …
=> fix: uri field is null when querying the page for posts uri

CHANGELOG.md, readme.txt, src/Data/NodeResolver.php, src/WPGraphQL.php, tests/wpunit/NodeByUriTest.php, wp-graphql.php
- [#2792](https://github.com/wp-graphql/wp-graphql/pull/2792): fix: uri field is null when querying the page for posts uri
=> release: v1.14.2

src/Data/NodeResolver.php, tests/wpunit/NodeByUriTest.php
This fixes a bug where querying for posts (of a non-hierarchical post type) by Slug would return null when the site had custom permalinks set. 
closes #2798 2798
**BEFORE**
**AFTER**
Notes for future reference (written at 2:30AM by @justlevine):
- The original issue only occurs when querying via the non-pretty url (index.php?graphql) like in GraphiQL, not the pretty permalink (/graphql).
- The root cause is that unlike WP native's routing, our parse_request() doesn't match slugs (since the rewrite rules are now prefixed …
=> fix: querying posts by slug fails when custom permalinks are set

composer.lock, src/Data/NodeResolver.php, tests/wpunit/NodeByUriTest.php, tests/wpunit/PageByUriTest.php
This fixes a bug in the NodeResolver for when there are valid duplicate slugs in different post types. 
closes #2800 
Following the steps to reproduce mentioned [here](https://github.com/wp-graphql/wp-graphql/issues/2800#issuecomment-1522393911).
=> fix: Conflict Between Custom Post Type and Media Slugs

CHANGELOG.md, composer.lock, readme.txt, src/Data/NodeResolver.php, src/WPGraphQL.php, tests/wpunit/NodeByUriTest.php, tests/wpunit/PageByUriTest.php, wp-graphql.php
- [#2801](https://github.com/wp-graphql/wp-graphql/pull/2801): fix: conflict between custom post type and media slugs
- [#2799](https://github.com/wp-graphql/wp-graphql/pull/2794): fix: querying posts by slug fails when custom permalinks are set
- [#2794](https://github.com/wp-graphql/wp-graphql/pull/2794): chore(deps): bump guzzlehttp/psr7 from 1.9.0 to 1.9.1
=> release: v1.14.3

composer.lock
Updates the Composer dev-dependencies to their latest versions.
`wp-cli` has _not_ been updated, due to issues with 2.8.0
no
This can be included in #2827 without any additional testing.
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php 8.0.26)
**WordPress Version:** 6.2.2
=> chore: update composer dev-deps to latest

src/Utils/QueryAnalyzer.php, tests/wpunit/QueryAnalyzerTest.php
This modifies the QueryAnalyzer to only track `list:$type_name` for RootConnections.
Nested connections will not tag the query with `list:$type_name` as it was leading to over-purging. 
see: https://github.com/wp-graphql/wp-graphql-smart-cache/issues/225
related: https://github.com/wp-graphql/wp-graphql-smart-cache/issues/225
This should significantly reduce the amount of queries that are purged from common events such as publishing posts.
Here we can see that a query for a Category and it's related posts will return a `list:post` key, meaning it will invalidate …
=> fix: improve tracking of query analyzer list types

.github/workflows/deploy-docker-image.yml, .github/workflows/upload-schema-artifact.yml, CHANGELOG.md, composer.lock, readme.txt, src/Utils/QueryAnalyzer.php, src/WPGraphQL.php, tests/wpunit/QueryAnalyzerTest.php, wp-graphql.php
- [#2834](https://github.com/wp-graphql/wp-graphql/pull/2834): fix: improve how the Query Analyzer tracks list types, only tracking lists from the RootType and not nested lists.
- [#2828](https://github.com/wp-graphql/wp-graphql/pull/2828): chore: update composer dev-deps to latest. Thanks @justlevine!
- [#2835](https://github.com/wp-graphql/wp-graphql/pull/2835): ci: update docker deploy workflow to use latest docker actions.
- [#2836](https://github.com/wp-graphql/wp-graphql/pull/2836): ci: update schema upload workflow to pin mariadb to 10.8.2
=> release: v1.14.5

.github/workflows/code-quality.yml
This PR adds support for using STEP_DEBUG in the Code Quality workflow to run phpstan in debug mode.
This change will allow better debugging of CI failures that cannot be easily replicated locally. 
For example: if [hypothetically](https://github.com/wp-graphql/wp-graphql/pull/2840) a leaky dependency causes phpstan to throw an Out of Memory issues, this would let us pinpoint that the error isnt occurring due to the contents of the PR 
1. Visit the [Code Quality action on this PR](https://github.com/wp-graphql/wp-graphql/actions/runs/5416920029?pr=2841)
2. Click 'Rerun All Jobs'
3. Check `Enable debug logging` and click `Re-run jobs`.
4. Check log for `Run PHPStan` to see the PHPStan …
=> ci: support STEP_DEBUG in Code Quality workflow

.github/workflows/deploy-docker-image.yml, .github/workflows/testing-integration.yml
… The github image build for WP 6.2 are being excluded for all PHP versions instead of just one specific PHP version as intended.  This is a simple fix and should build/deploy images on the next tag/release of this plugin.
… Yes https://github.com/wp-graphql/wp-graphql/issues/2848
…
=> ci: Indent WP 6.2 in workflow file

src/Data/NodeResolver.php, src/Model/Post.php, tests/wpunit/PostObjectQueriesTest.php
This fixes a bug where querying posts by slug or uri was returning null when the post's name (slug) included non-ascii characters.  
Failing Tests: https://github.com/wp-graphql/wp-graphql/actions/runs/5521919716/jobs/10070736088?pr=2851
Passing Tests: https://github.com/wp-graphql/wp-graphql/actions/runs/5522008949/jobs/10070950056?pr=2851
- closes #2847 
- closes #2804
I've created 2 posts with the following titles: 
- (Persian) `سلام-دنیا`
- (Emoji) `🍌`
This gives me posts visible at the following URLs: 
- `/blog/2023/07/11/🍌/`
- `/blog/2023/07/10/سلام-دنیا/` …
=> fix: querying posts by slug or uri when the post name is non-ascii

src/Admin/Settings/Settings.php, src/Server/ValidationRules/QueryDepth.php
This fixes a bug that occurs when leaving the "Max Depth to allow for GraphQL Queries" value empty in the GraphQL > Settings page. 
closes #2809
If the value entered in the "Max Depth" setting is a non-positive integer, the default value of 10 will be saved. If a non-positive integer is already stored for the setting value, the default of 10 will be used.
=> fix: internal server error when query max depth setting is left empty

.github/workflows/deploy-docker-image.yml, .github/workflows/testing-integration.yml, CHANGELOG.md, package-lock.json, readme.txt, src/Admin/Settings/Settings.php, src/Data/NodeResolver.php, src/Model/Post.php, src/Server/ValidationRules/QueryDepth.php, src/WPGraphQL.php, tests/wpunit/PostObjectQueriesTest.php, wp-graphql.php
- [#2853](https://github.com/wp-graphql/wp-graphql/pull/2853): fix: internal server error when query max depth setting is left empty
- [#2851](https://github.com/wp-graphql/wp-graphql/pull/2851): fix: querying posts by slug or uri with non-ascii characters
- [#2849](https://github.com/wp-graphql/wp-graphql/pull/2849): ci: Indent WP 6.2 in workflow file. Fixes Docker deploys. Thanks @markkelnar!
- [#2846](https://github.com/wp-graphql/wp-graphql/pull/2846): chore(deps): bump tough-cookie from 4.0.0 to 4.1.3
=> release: v1.14.7

src/Utils/QueryAnalyzer.php, tests/wpunit/QueryAnalyzerTest.php
This fixes a regression to the 1.14.5 release where `list:$type` keys are no longer being output for RootQuery fields that return a listOf Nodes. 
- failing tests: https://github.com/wp-graphql/wp-graphql/actions/runs/5593265358/jobs/10226719111#step:8:588
- passing tests: https://github.com/wp-graphql/wp-graphql/actions/runs/5593270930/jobs/10226731070#step:8:588
closes #2860 
related: https://github.com/wp-graphql/wp-graphql-smart-cache/issues/228
Given the following snippet: 
```php
add_action( 'graphql_register_types', function() {
register_graphql_field( …
```
=> fix: output `list:$type` keys for Root fields that return a listOf Nodes

packages/graphiql-query-composer/components/RootView.js
This fixes the truncation issue that was hiding the query name on the various queries/fragments in the explorer tab of the GraphiQL Query composer.
before fix:
after fix:
Not that I am aware of.
Windows 11 64 bit
**Browsers**
Google Chrome 114.0.5735.199 (Official Build) (64-bit)
Firefox Browser 113.0.1 (64-bit)
Microsoft Edge Version 114.0.1823.82 (Official build) (64-bit)
6.2.2
=> fix: Prevent truncation of query name inside the GraphiQL Query composer explorer tab.

src/Utils/QueryAnalyzer.php, tests/wpunit/CustomPostTypeTest.php
This fixes a regression from v1.14.7 release where the QueryAnalyzer attempts to load types that might not exist when `graphql_single_name` for post types / taxonomies include underscores.
- failing test: https://github.com/wp-graphql/wp-graphql/actions/runs/5672998214
- passing test: https://github.com/wp-graphql/wp-graphql/actions/runs/5673008689
closes #2868 
Given the following code to register a post type: 
```php
<?php
add_action( 'init', function() {
register_post_type( 'test_events', [ …
```
=> fix: type loader returns null when graphql_single_name value has underscores [regression]

src/Type/ObjectType/User.php, tests/wpunit/UserRoleConnectionQueriesTest.php
When my user does not have any roles assigned.  wp-graphql is returning all existing roles instead of null or empty roles.
…
…
…
**Operating System:** aws lightsail bitnami wordpress
**WordPress Version:** 6.2
=> fix: user roles should return empty 

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, composer.lock, readme.txt, src/Type/ObjectType/User.php, src/Utils/QueryAnalyzer.php, src/WPGraphQL.php, tests/wpunit/CustomPostTypeTest.php, tests/wpunit/ModelUserTest.php, tests/wpunit/UserRoleConnectionQueriesTest.php, wp-graphql.php
- [#2865](https://github.com/wp-graphql/wp-graphql/pull/2865): fix: user roles should return empty if user doesn't have roles. Thanks @j3ang!
- [#2870](https://github.com/wp-graphql/wp-graphql/pull/2870): fix: Type Loader returns null when "graphql_single_name" value has underscores [regression]
- [#2871](https://github.com/wp-graphql/wp-graphql/pull/2871): fix: update tests, follow-up to [#2865](https://github.com/wp-graphql/wp-graphql/pull/2865)
=> release: v1.14.9

src/Data/Cursor/PostObjectCursor.php, tests/wpunit/PostObjectCursorTest.php
- Fixes support for sorting post connection results by multiple meta.
…
=> fix: PostObjectCursor's support for meta fields improved

src/Type/ObjectType/RootQuery.php
Improve description of the `asPreview` argument as discussed in #2876 
closes #2879 
The description is a bit vague.
The description provides more clarity about how the argument will impact the field's response.
=> fix: increase clarity of the description of `asPreview` argument

CHANGELOG.md, readme.txt, src/Data/Cursor/PostObjectCursor.php, src/Type/ObjectType/RootQuery.php, src/WPGraphQL.php, tests/wpunit/PostObjectCursorTest.php, wp-graphql.php
- [#2874](https://github.com/wp-graphql/wp-graphql/pull/2874): fix: improve PostObjectCursor support for meta queries. Thanks @kidunot89!
- [#2880](https://github.com/wp-graphql/wp-graphql/pull/2880): fix: increase clarity of the description of "asPreview" argument
=> release: v1.14.10

composer.json, composer.lock
This PR updates webonyx/graphql-php to [v14.11.10](https://github.com/webonyx/graphql-php/releases/tag/v14.11.10). This release contains some PHP 8.2 deprecation fixes, a version we'll be testing against starting in #2889 
Composer dev-dependencies have also been updated to their latest (semver-compatible) versions.
…
**Operating …
=> chore: bump graphql-php to 14.11.10 and update Composer dev-deps

.github/workflows/deploy-docker-image.yml, .github/workflows/testing-integration.yml
Updates the test matrix to test against WordPress 6.3 (currently available as a beta)
closes #2886 
This simplifies the matrix and drops testing for some older versions of WordPress
=> ci: update tests to test against WordPress 6.3, simplify the matrix

composer.lock, src/Router.php
The graphql url cache key header returned includes http/https as well as path.  But this differs from integration with WPE Varnish cache, where this currently runs.  Bring this to consistent/expected behavior where the varnish rule uses and invalidates only the hostname.
part of [wp-graphql/wp-graphql-smart-cache/issues/246](https://github.com/wp-graphql/wp-graphql-smart-cache/issues/246) …
=> fix: Use hostname for graphql cache header url for varnish

src/Router.php
Reverts wp-graphql/wp-graphql#2890
see: https://github.com/wp-graphql/wp-graphql/pull/2890#issuecomment-1673721688
=> revert: "fix: Use hostname for graphql cache header url for varnish"

phpcs.xml.dist, src/Admin/GraphiQL/GraphiQL.php, src/Admin/Settings/Settings.php, src/Admin/Settings/SettingsRegistry.php, src/Data/Connection/EnqueuedScriptsConnectionResolver.php, src/Data/Connection/EnqueuedStylesheetConnectionResolver.php, src/Data/NodeResolver.php, src/Data/PostObjectMutation.php, src/Model/Post.php, src/Model/PostType.php, src/Model/Taxonomy.php, src/Model/User.php, src/Mutation/MediaItemCreate.php, src/Type/Enum/TimezoneEnum.php, src/Type/InterfaceType/ContentTemplate.php, src/Type/ObjectType/MediaSize.php, src/Type/ObjectType/RootQuery.php, src/Utils/QueryLog.php
This PR adds the `SlevomatCodingStandard.Variables.UnusedVariable` sniff to our PHPCS ruleset and remediates any unused variables in our codebase.
The individual smells that required @jasonbahl 's expertise in #2830 were committed individually to expose those changes, especially 69854f6d0697e7f1f5dba005cf49d3fcbd586230 which reads like a bugfix.
Based off of #2901 (and requires that to be merged first).
Cherrypicked from #2830
… …
=> chore: handle unused variables (phpcs)

.github/workflows/deploy-docker-image.yml, .github/workflows/testing-integration.yml, composer.lock
…The official WP 6.3 docker images are available. Use those for our docker images as well as testing CI/CD workflow.
closes #2906 
…
=> ci: Use WP 6.3 image, not the beta one

src/Router.php
Related to the [work](https://github.com/wp-graphql/wp-graphql-smart-cache/issues/246) to remove wpengine specific code from this plugin, since that is being handled in the wpengine specific codebase to purge their network/varnish cache.  
This change removes the scheme (http://,https://,://) from the graphql url provided as cache header url.  The domain and path remains in the url.
A similar change is being made in the smart cache plugin to send the same hostname as part of the purge cache event.
Any …
=> fix: Use graphql endpoint without scheme in url header

src/Router.php
reverting as this will cause a regression for WP Engine users until a deployment is made to WP Engine MU plugins. 
Will re-open this PR and release after the WP Engine MU plugins are updated for their users.
=> revert: "fix: Use graphql endpoint without scheme in url header"

.github/workflows/deploy-to-wordpress.yml, CHANGELOG.md, composer.json, readme.txt, src/WPGraphQL.php, wp-graphql.php
…The downloadable zip files in the 'assets' for a release [page](https://github.com/wp-graphql/wp-graphql/tags) in GitHub, do not use a subfolder folder as the [plugin](https://wordpress.org/plugins/wpgraphql-smart-cache/) downloaded from wordpress.org does. 
The rsync in this PR is similar to how the 10up WordPress deploy works. 10up/action-wordpress-plugin-deploy
Add this as a composer command to be useable locally.
Similar to wp-graphql-smart-cache [fix](https://github.com/wp-graphql/wp-graphql-smart-cache/issues/256). …
=> fix: zip artifact in GH not in subfolder

src/Data/DataSource.php, tests/wpunit/SettingQueriesTest.php
This PR adds a check to `DataSource::get_allowed_settings_by_group()` to ensure there is an actual `$settings['group']` set before trying to use it, fixing a potential fatal error.
**Note**: the `SettingQueriesTest` class has also been cleaned up, as I was anticipating having to add a test case, and it seems a shame not to commit (see comment below). No actual test cases or logic have changed.
Closes #2553 
(see comments below).
I'm unable to actually replicate this …
=> fix: skip setting if no `$setting['group']`

src/Admin/Settings/SettingsRegistry.php, tests/functional/GraphqlSettingsPageCept.php
This PR fixes `SettingsRegistry::callback_user_role_select()` to correctly check `$args['default']` for the default role to use.
Cherrypicked from @szepeviktor 's work in https://github.com/wp-graphql/wp-graphql/pull/2947
Supercedes #2497 
…
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + PHP 8.1.15 )
**WordPress Version:** 6.3.1
=> fix: correctly get `default` user role for settings selectbox

access-functions.php, src/Type/WPConnectionType.php, tests/wpunit/AccessFunctionsTest.php
This PR fixes `rename_graphql_field()` so fields registered by connections are also renamed (e.g. `RootQuery.users` => `RootQuery.wpUsers` ).
This is done by adding a `graphql_wp_connection_{$this->from_type}_from_field_name` filter to the `WPConnectionType::$from_field_name`. 
**Note: This filter is intended for internal use only, and marked as such**.
Additionally, fixes a PHP warning when the supplied field name doesnt exist.
Closes #1843 
See #1843 before …
=> fix: rename fields registered by connections when using `rename_graphql_field()`

phpstan/constants.php, wp-graphql.php
Follow up to #2954. Removes the use of `@phpstan-ignore-next-line` by defining the constant for PHPStan, and drops some unnecessary conditional logic.
…
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + PHP 8.1.15)
**WordPress Version:** 6.3.1
=> chore: remove @phpstan-ignore annotations

src/Model/Menu.php, src/Model/Term.php, src/Registry/TypeRegistry.php, tests/wpunit/MenuQueriesTest.php, tests/wpunit/TermObjectQueriesTest.php
- Decodes the slug so it works with other languages. Like Hebrew, Arabic, etc.
- ~~Decodes the type name, so it works with different languages (e.g. Chinese, Hebrew, etc.)~~
##Example:
- Before: "**%d7%90%d7%91%d7%99%d7%96%d7%a8%d7%99%d7%9d**"
- After:  "**הטבה לרוכשים**"
**WordPress Version:** 6.3.1
=> fix: Decode slug so it works with other languages

access-functions.php, src/Data/DataSource.php, src/Mutation/UpdateSettings.php, src/Type/ObjectType/SettingGroup.php, src/Type/ObjectType/Settings.php, src/Type/WPEnumType.php, src/Utils/Utils.php, tests/wpunit/AccessFunctionsTest.php
This PR adds the `graphql_format_name()` access function to the codebase, and refactors methods to use that function instead of their own `preg_replace()` calls.
The `graphql_format_name()` method allows us to centralize the logic for ensuring that all GraphQL names meet the [spec](http://spec.graphql.org/draft/#sec-Names), ensuring uniformity and reducing user error. The method can be called with one parameter ( `graphql_format_name( $string_to_format )` ) to return a fully compliant name, or with additional parameters to provide a custom replacement character or regex ( e.g. `graphql_format_name( $string_to_format, ' ', '/[^a-zA-Z0-9 -]/' )`, used often before a `camelCase` or similar …
=> feat: add `graphql_format_name()` access method

src/Type/Enum/UserRoleEnum.php
This PR changes `UserRoleEnum` to use _all_ role values instead of just those filtered by [`editable_roles`](https://developer.wordpress.org/reference/hooks/editable_roles/).
The purpose of the `editable_roles` is to limit the roles that _the current user may assign to another user_. As such, it neither represents the roles a privileged user can query for, nor stays the same in the schema across all users.
Additionally, we're using `wp_roles()` instead of directly accessing the global, and early-returning to reduce code complexity.
fixes #2537 
Any relevant logs, error output, GraphiQL screenshots, …
=> fix: use all roles for `UserRoleEnum` instead of the filtered `editible_roles`

composer.json, composer.lock
This PR updates the composer deps in the lockfile to their latest available versions. Specifically:
- ivome/graphql-relay-php  => v0.7.0
- phpstan/phpstan => 1.10.40
- szepeviktor/phpstan-wordpress => 1.3.2
- wp-cli/wp-cli-bundle  => 2.9.0
** No production code has been changed ** (including in the deps).
…
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php 8.1.15
**WordPress Version:** 6.3.2
=> chore: update composer deps to latest

phpcs.xml.dist, src/Data/Connection/ThemeConnectionResolver.php, src/Data/Connection/UserRoleConnectionResolver.php, src/Model/UserRole.php, src/Type/Connection/MenuItems.php, src/Type/Connection/TermObjects.php
This PR adds the (auto-fixable) `SlevomatCodingStandard.Variables.UselessVariable` sniff to our PHPCS ruleset, and remediates the handful of smells in our codebase.
While useless variables aren't inherently a bad thing, the standardization will make code refractoring easier (since it'l be easier to spot duplicate code), and the fact that its auto-fixable means that there's no additional load for project maintainers.
… …
=> chore: lint and remove useless variables [phpcs]

.github/workflows/graphiql-e2e-tests.yml, .github/workflows/testing-integration.yml, package-lock.json, readme.txt, tests/e2e/setup-test-framework.js, tests/wpunit/PostTypeObjectQueriesTest.php, tests/wpunit/ThemeObjectQueriesTest.php, wp-graphql.php
Updates the test matrix to run tests against WP 6.4 and updates README and main plugin file to indicate that.
closes #2983
=> ci: run tests against WordPress 6.4

.github/workflows/graphiql-e2e-tests.yml, .github/workflows/testing-integration.yml, CHANGELOG.md, package-lock.json, readme.txt, tests/e2e/setup-test-framework.js, tests/wpunit/PostTypeObjectQueriesTest.php, tests/wpunit/ThemeObjectQueriesTest.php, wp-graphql.php
- [#2984](https://github.com/wp-graphql/wp-graphql/pull/2984): ci: update tests to run against WordPress 6.4. Update README, plugin file's "tested up to" to reflect.
=> release: v1.18.1

.github/workflows/deploy-docker-image.yml, .github/workflows/testing-integration.yml, CHANGELOG.md, readme.txt, wp-graphql.php
- ci: update tests to run against WordPress 6.4.1. Update Docker Deploy to include WP 6.4.1. Update README, plugin file's "tested up to" to reflect.
=> release: v1.18.2

access-functions.php
Adds PHP 8.0 polyfills for `str_starts_with()` and `str_ends_with()`.
We're only using `str_ends_with()` locally, the former is added preemptively since if a dev sees one, theyre going to assume they dont see the other.
Fixes #2991 
It's not getting picked up by PHPCompatibilityWP because our other dev-deps install symfony's polyfill package, so even on <8.0 the method exists on all dev environments.
**Operating …
=> fix: add polyfills for `str_starts_with()` and `str_ends_with()` to prevent fatal errors in PHP < 8.0

src/Model/User.php, tests/wpunit/UserObjectQueriesTest.php
This PR makes the `User.url` field public, as it is intended to be public (and is so on the REST API).
Tests have been updated to check for public/private fields on an unauthenticated query of a `user`.
Fixes #2766 
…
**Operating System:** Ubuntu 20.04 (wsl2 +devilbox + php 8.1.15)
**WordPress Version:** 6.4.1
=> fix: make `User.url` public

src/Data/Connection/AbstractConnectionResolver.php, tests/wpunit/PostObjectConnectionQueriesTest.php
This PR adds a debug message to the GraphQL response when the requested amount (`first`, `last`) is greater than the `graphql_connection_max_query_amount` filter value set on the server.
This addition provides developers with an important indication that they're not actually getting the full results requested, which is particularly important to new users coming from traditional WP-PHP for whom setting `WP_Query( [ 'posts_per_page' => -1 ] )` is discouraged, but commonplace.
A debug message was chosen over throwing a `GraphQLError`, both to preserve back-compat, and because IMO this is the ideal GraphQL pattern: a too-large `first` isnt a schema error, it's something that gets filtered …
=> feat: output GRAPHQL_DEBUG message if requested amount is larger than connection limit

composer.json, composer.lock
This PR updates our Composer dev-dependencies to their latest versions. Additionally, it explicitly sets `phpcompatibility/php-compatibility` to the `dev-develop` branch, so PHPCS can catch issues related to PHP 8.0+
[Reference](https://github.com/PHPCompatibility/PHPCompatibilityWP/issues/40#issuecomment-1139623926)
This change will expose the bug addressed in #3007 , so the [linting](https://github.com/wp-graphql/wp-graphql/actions/runs/7392468178/job/20110979617?pr …
=> chore: update composer dev-dependencies and use `php-compatibility:develop` branch to 8.0+ lints

src/Type/Connection/Taxonomies.php
This PR replaces the deprecated call to `AbstractConnectionResolver::setQueryArg()` in `ContentType.connectedTaxonomies` resolver with `AbstractConnectionResolver::set_query_arg()`.
…
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php8.1.15)
**WordPress Version:** 6.4.2
=> fix: replace deprecated `AbstractConnectionResolver::setQueryArg()` call with `::set_query_arg()`

activation.php, src/Admin/Settings/Settings.php, src/Router.php, src/Utils/QueryAnalyzer.php, tests/functional/GraphQLHeadersCept.php, tests/wpunit/QueryAnalyzerTest.php
This PR adds an admin setting for enabling/disabling the Query Analyzer, and defaults the setting value to `off` on new installs, unless GraphQL Debugging is enabled. In other words **by default, the QueryAnalyzer will only be enabled when GraphQL Debugging is also enabled**.
The reason for this is the overhead caused by having QueryAnalyzer enabled. While this cost is justified during debugging, or when needed to cache future responses, on vanilla WPGraphQL setups there is no need to pay for that extra processing.
More specifically:
- Adds a new `query_analyzer_enabled` setting to the WPGraphQL Settings page. The setting control is _disabled_ if `GraphQL::debug()` is true.
- Adds a new …
=> perf: Expose `graphql_should_analyze_queries` as setting

src/Registry/TypeRegistry.php, tests/wpunit/AccessFunctionsTest.php
This introduces a more helpful error when a field in the Schema references a GraphQL Type that has not been registered to the Schema.
closes #3034 
When registering a field that references a Type that doesn't exist: 
```php
<?php
add_action( 'graphql_register_types', function() {
register_graphql_field( 'User', 'fakeField', [
'type' => 'NonExistingType'
]);
} );
```
Then querying for the field like so: 
```graphql
{
users {
nodes {
id
fakeField
}
}
}
```
A vague error was returned with limited information to quickly identify the issue. 
A clearer Error is …
=> feat: provide better error when field references a type that does not exist

src/Type/Enum/UsersConnectionSearchColumnEnum.php, tests/wpunit/UserConnectionQueriesTest.php
This PR fixes the Enum `values` used by `UserConnectionSearchColumnEnum` to use the prefixed `user_*` as expected by [`WP_User_Query`](https://developer.wordpress.org/reference/classes/wp_user_query/#search-parameters)
Fixes #2419 
…
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php8.1.14)
**WordPress Version:** 6.4.3
=> fix: `UsersConnectionSearchColumnEnum` values should be prefixed with `user_`

src/Data/Connection/MenuItemConnectionResolver.php, tests/wpunit/MenuItemConnectionQueriesTest.php
This PR fixes an issue in the `MenuItemConnectionResolver` logic, where querying a `menuItem` by a `location` with unset terms would return _all_ menu items, instead of _none_.
Logic has been changed so the `tax_query` args are given a `'term_id' => []`.
Tests have been added to cover:
- A `location` with no menu items returns null.
- A `location` with no menu items returns null _as an admin_.
- A `location` with menu items, doesn't return items from a different `location` (either public or as an admin).
Fixes #3029  …
=> fix: return empty when filtering `menuItems` by a `location` with no assigned items

src/Data/NodeResolver.php, src/Model/Comment.php, src/Type/InterfaceType/UniformResourceIdentifiable.php, src/Type/ObjectType/Comment.php, tests/wpunit/CommentObjectQueriesTest.php, tests/wpunit/NodeByUriTest.php
This PR add the `UniformResourceIdentifiable` interface to the `Comment` object type. More specifically:
- `Comment` types now implement `UniformResourceIdentifiable`, which exposes the `uri` field.
- Added the `Comment.link` field, for parity with the [REST API](https://developer.wordpress.org/rest-api/reference/comments/#schema)
- Added support to `nodeByUri` for querying Comment URIs (`{post_link}#comment-{id}`}.
`nodeByUri` does *not* validate that the …
=> feat: add `UniformResourceIdentifiable` interface to `Comment` type

src/Admin/Settings/Settings.php
This updates the enqueue_admin_assets callback to expect a possible null value for the argument passed from `do_action( 'admin_enqueue_scripts' );`
closes #3056
=> fix: admin_enqueue_scripts callback should expect a possible null value passed to it

composer.json, composer.lock
This pins the composer dev dependency "wp-browser" to "<3.5" to allow our automated tests to run. 
See: https://wpbrowser.wptestkit.dev/migration/#staying-on-version-3-lower-than-35
closes #3060
=> ci: pin wp-browser to "<3.5" to allow automated tests to run properly

src/Data/DataSource.php, src/Model/Avatar.php, src/Utils/QueryAnalyzer.php, tests/wpunit/AvatarObjectQueriesTest.php
This fixes a bug where avatar information would be returned even if the "show_avatars" setting is turned "off" under Settings > Discussion. 
closes #3064 
This doesn't change the schema, just the resolve logic. 
Since the Avatar field is already nullable, responsible consumers should already be prepared to expect null values for avatars, so preventing avatars from being returned is not considered a breaking change.
=> fix: respect show avatar setting

src/Data/Config.php
This fix resolves the issue when the 'ORDER BY' is missing in cursor pagination.
I have installed WPGraphQL Version 1.21.0 in addition to this version of an offset pagination plugin <https://github.com/alaa-alshamy/wp-graphql-offset-pagination/releases/tag/v0.2.0.2>. 
I have the following categories for example as parent, child
When I run the following GraphQL query to count total of children of the targeted parent that id is `38`.
```graphql
query terms {
categories(where: {
parent: 38
}) {
pageInfo { …
```
=> fix: taking care about the case of empty order by

CHANGELOG.md, constants.php, readme.txt, src/Data/Config.php, src/Data/DataSource.php, src/Model/Avatar.php, src/Utils/QueryAnalyzer.php, tests/wpunit/AvatarObjectQueriesTest.php, tests/wpunit/TermObjectCursorTest.php, wp-graphql.php
- [#3067](https://github.com/wp-graphql/wp-graphql/pull/3067): fix: respect show avatar setting
- [#3063](https://github.com/wp-graphql/wp-graphql/pull/3063): fix: fixes a bug in cursor stability filters that could lead to empty order
- [#3070](https://github.com/wp-graphql/wp-graphql/pull/3070): test(3063): Adds test for [#3063](https://github.com/wp-graphql/wp-graphql/pull/3063)
=> release: v1.22.1

src/Model/Post.php, src/Registry/Utils/PostObject.php, tests/wpunit/PostObjectQueriesTest.php
This PR exposes the `hasPassword` and `password` fields on Post objects.
It **does not** provide a mechanism to _provide_ a password, which will be handled in a separate PR.
closes #3069 
Until #930 is addressed, password-protected posts require a WP cookie or the `edit_posts` capability. You can see that ticket for workarounds.
**Operating System:** Ubuntu 20.04 (Wsl2 + devilbox + php 8.1.19)
**WordPress …
=> feat: expose `hasPassword` and `password` fields on Post objects

src/Data/Connection/PluginConnectionResolver.php
This PR refactors our `PluginConnectionResolver` class to use a DRY `::get_all_plugins()` method for building the list of available plugins.
This list is then stored in a class property, so the fetching, filtering, etc only occur once.
Part of #2749
This PR is based on #3082 , which should be merged first.
**WordPress Version:** 6.4.3
=> perf: refactor `PluginConnectionResolver` to only fetch plugins once

src/Admin/AdminNotices.php
This PR introduces the following:
- `graphql_admin_notices_render_notices` action
- `graphql_admin_notices_render_notice` action
- `graphql_admin_notices_is_plugin_scoped_page` filter
These actions and filters enable 3rd party codebases to hook into the rendering of admin notices registered via `register_graphql_admin_notice` and modify things like: 
- which page(s) the notices can be displayed on
- styles applied to the notices
closes #3090 
While working on the new WPGraphQL IDE (https://github.com/wp-graphql/wpgraphql-ide) I wanted to add support for the admin …
=> feat: introduce actions and filters for GraphQL Admin Notices

.github/workflows/build-graphiql.yml, .github/workflows/code-quality.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deploy-docker-image.yml, .github/workflows/deploy-to-wordpress.yml, .github/workflows/graphiql-e2e-tests.yml, .github/workflows/schema-linter.yml, .github/workflows/sync-develop-with-master.yml, .github/workflows/testing-integration.yml, .github/workflows/upload-schema-artifact.yml, .github/workflows/wordpress-coding-standards.yml, bin/run-docker.sh, docker-compose.yml, tests/wpunit/CommentConnectionQueriesTest.php
This PR:
- Updates the various GitHub actions used by our workflows to their latest versions.
- Removes `matrix` testing from our workflows when only one value (e.g. `php-version`, `node-version`) used.
- Replaces the use of `styfle/cancel-workflow-action` with the built-in `concurrency` property.
- Bumps the default PHP version used for workflows to PHP 8.2
- Updates the WordPress/PHP matrixes to make them more readable/manageable.
This PR **does not**
- Bump the active Node version used for workflows to Node 20.  …
=> ci: Update actions in GitHub workflows and cleanup

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/CommentConnectionResolver.php, src/Data/Connection/ContentTypeConnectionResolver.php, src/Data/Connection/EnqueuedScriptsConnectionResolver.php, src/Data/Connection/EnqueuedStylesheetConnectionResolver.php, src/Data/Connection/PluginConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/TaxonomyConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php, src/Data/Connection/ThemeConnectionResolver.php, src/Data/Connection/UserConnectionResolver.php, src/Data/Connection/UserRoleConnectionResolver.php
This PR refactors the way `AbstractConnectionResolver` handles `DataLoader`s. More specifically:
- Child classes now define their loader names in `::loader_name()`
- `::get_loader_name()` is no longer an `abstract` method, and instead calls `::loader_name()` if it has not already been set as a class property.
- Added a new `graphql_connection_loader_name` filter to more easily apply custom data loaders to an existing Connection Resolver (e.g. CPT-specific).
- The `AbstractConnectionResolver::$loader` property now only gets instantiated once, no matter how many times `::get_loader()` is called. As a result, all direct calls to `::$loader` have been replaced with `::get_loader()`.
- The …
=> refactor: improve `loader` handling in `AbstractConnectionResolver`

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/CommentConnectionResolver.php, src/Data/Connection/EnqueuedScriptsConnectionResolver.php, src/Data/Connection/EnqueuedStylesheetConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php, tests/wpunit/PostObjectConnectionQueriesTest.php
This PR refactors how `AbstractConnectionResolver` calculates the query amount in the following ways:
- Refactor `::get_query_amount()`  to only calculate the query amount 1x in the lifecycle, by checking if `AbstractConnectionResolver::$query_amount` is set.
- Source the default `$max_query_amount` from `::max_query_amount()`, allowing child classes to overload the max amount without using the `graphql_connection_max_query_amount` filter. Child classes using that filter have been updated to set `::max_query_amount()` instead.
- Move the `graphql_connection_amount_requested` filter into `::get_query_amount()` to improve DX. The filter will only be applied once due to the aformentioned …
=> feat: improve query amount handling in `AbstractConnectionResolver`

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/CommentConnectionResolver.php, src/Data/Connection/MenuItemConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php
This PR adds the public `get_unfiltered_args()` method to `AbstractConnectionResolver` for fetching the GraphQL `$args` before they have been modified by any filters/side effects.
Additionally child classes that were using an unmodified local copy of `$args` have been updated to use `::get_unfiltered_args()` instead.
Part of #2749
- This PR is based on https://github.com/wp-graphql/wp-graphql/pull/3082 , which should be merged first.
- Despite the new …
=> refactor: add `AbstractConnectionResolver::get_unfiltered_args()` public getter

src/Data/Connection/AbstractConnectionResolver.php
This PR refactors `AbstractConnectionResolver::get_page_info()` into an overloadable, protected `::prepare_page_info()`.
`::get_page_info()` will now call that (or child) method, apply the filter, and store it in a new `AbstractConnectionResolver::$page_info` property so future calls to the getter don't need to rebuild the array.
This both improves DX (smaller footprint, only need to overload the actual `$page_info` logic in children, consistent return value regardless of when it is called), and potentially increases performance (if `::get_page_info()` is called multiple times in the lifecycle).
Part …
=> refactor: add `AbstractConnectionResolver::prepare_page_info()`and only instantiate once

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/CommentConnectionResolver.php, src/Data/Connection/ContentTypeConnectionResolver.php, src/Data/Connection/EnqueuedScriptsConnectionResolver.php, src/Data/Connection/EnqueuedStylesheetConnectionResolver.php, src/Data/Connection/PluginConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/TaxonomyConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php, src/Data/Connection/ThemeConnectionResolver.php, src/Data/Connection/UserConnectionResolver.php
This PR deprecates the following camelCased methods in `AbstractConnectionResolver` for their `snake_cased` equivalents. More specifically:
- `::getSource()` => `::get_source()`
- `::getContext()` => `::get_context()`
- `::getLoader()` => `::get_loader()`
- `::getInfo()`   => `::get_info()`
- `::getShouldExecute()` => `::get_should_execute()`
Part of #2749 
- 🚨 Don't forget to replace `@todo` with the version number before release.
> [!IMPORTANT]
> As these …
=> refactor: deprecate `camelCase` methods in `AbstractConnectionResolver` for `snake_case` equivalents

src/Data/Loader/AbstractDataLoader.php, tests/wpunit/QueryAnalyzerTest.php
This fixes a bug where Node IDs are not being output by the QueryAnalyzer when a resolver uses the `load_many()` method of the DataLoader.
This bug can lead to issues with tag-based caching / tag-based cache invalidation as some nodes might not be getting tagged as expected.
closes #3101 
Given the scenario outlined in #3113:
The Node IDs are not present in the Query Analyzer output
The Node IDs _are_ present in the Query Analyzer output
=> fix: node ids not showing in query analyzer when using DataLoader->load_many()

src/Data/Connection/AbstractConnectionResolver.php, src/Data/Connection/CommentConnectionResolver.php, src/Data/Connection/ContentTypeConnectionResolver.php, src/Data/Connection/EnqueuedScriptsConnectionResolver.php, src/Data/Connection/EnqueuedStylesheetConnectionResolver.php, src/Data/Connection/PostObjectConnectionResolver.php, src/Data/Connection/TaxonomyConnectionResolver.php, src/Data/Connection/TermObjectConnectionResolver.php, src/Data/Connection/ThemeConnectionResolver.php, src/Data/Connection/UserConnectionResolver.php
This PR refactors the DX around `AbstractConnectionResolver::should_execute()`.
More specifically:
- `AbstractConnectionResolver::$should_execute` is no longer instantiated with a value. Instead `::should_execute()` is no longer abstract and returns true by default, so only Resolvers that require custom `should_execute` logic need to overload the method.
- Resolver-specific `pre_should_execute` logic has been abstracted out of AbstractConnectionResolver's constructor and into a new `::pre_should_execute()` method. This overloadable method is then wrapped in a new `::get_pre_should_execute()` method which uniformly filters the value with the new `graphql_connection_pre_should_execute` …
=> refactor: make `AbstractConnectionResolver::should_execute()` non-abstract and add `::pre_should_execute()`

README.md, packages/wpgraphiql/screens/Help/Help.js, readme.txt
Update references in the WPGraphQL codebase that link to Slack to link to Discord instead
=> chore: Update references to Slack, pointing folks to Discord instead

src/Data/Connection/AbstractConnectionResolver.php, tests/wpunit/PostObjectConnectionQueriesTest.php
This PR adds the new `AbstractConnectionResolver::get_is_valid_model()` method, which wraps the `::is_valid_model()` logic in the new `graphql_connection_is_valid_model` filter.
This filter is useful for developers who wish to override a Connection Resolver's `is_valid_model()` check. The separation of concerns helps those extending a Connection Resolver by minimizing the about of boilerplate they need to copy when overloading `is_valid_model()` in their child classes.
This is a *non-breaking* change.
Additionally, the spacing in some docblocks was cleaned up.
There are _no breaking changes_ in this …
=> refactor: wrap `AbstractConnectionResolver::is_valid_model()` in `::get_is_valid_model()`

src/Data/Connection/AbstractConnectionResolver.php, tests/wpunit/PostObjectConnectionQueriesTest.php
This PR refactors the AbstractConnectionResolver in the following ways:
- `::get_nodes()` and `::get_edges()` now instantiate `AbstractConnectionResolver::$nodes` and `AbstractConnectionResolver::$edges` only once.
- The node generation logic has been relocated from `::get_nodes()` into the new `::prepare_nodes()` method.
- The edge generation logic has been relocated from `::get_edges()` into the new `::prepare_edges()` method. The `::prepare_edges()` method itself calls the new `::prepare_edge()` method, and wraps it in the preexisting `graphql_connection_edge` filter.
Together, these changes improve the DX by reducing the amount of boilerplate needed when extending the …
=> refactor: split `AbstractConnectionResolver::get_nodes()` and `get_edges()` into `prepare_*()` methods

src/Data/Connection/AbstractConnectionResolver.php
This PR moves the abstract `AbstractConnectionResolver::is_valid_offset()` method to be alongside the other abstract methods in the class.
**No actual code changes were made in this PR**
Part of #2749 
**WordPress Version:** 6.5.2
=> chore: relocate `AbstractConnectionResolver::is_valid_offset()` with other abstract methods.

src/Data/Connection/AbstractConnectionResolver.php, tests/wpunit/PostObjectConnectionQueriesTest.php
The PR refactors `AbstractConnectionResolver` in the following ways:
- `::get_ids()` now instantiates `AbstractConnectionResolver::$ids`, only once.
- The ID preparation logic has been moved into a new `::prepare_ids()` method.
This improves the DX by reducing the amount of boilerplate needed when extending the AbstractConnectionResolver class, and improving lifecycle consistency, with potential performance benefits for child classes with complex ID preparation logic.
There are _no breaking changes_ in this PR.
> [!IMPORTANT]
> This PR requires #3121 which should be merged first.
>
> The relevant diff for this PR can be seen at f6babda8e0a04383d46bf253dcf053539c238e4e
Does this close …
=> refactor: split `AbstractConnectionResolver::get_ids()` into `::prepare_ids()`

access-functions.php, composer.lock, src/Admin/Settings/SettingsRegistry.php, src/Data/Connection/AbstractConnectionResolver.php, src/Data/Cursor/CursorBuilder.php, src/Mutation/PostObjectDelete.php, src/Registry/TypeRegistry.php, src/Registry/Utils/PostObject.php, src/Registry/Utils/TermObject.php, src/Request.php, src/Type/ObjectType/PostObject.php, src/Utils/QueryAnalyzer.php, src/WPGraphQL.php, tests/_data/classes/WP_Query_Custom.php, wp-graphql.php
This PR:
- Updates `wp-graphql-test-case` to 3.0.1 (just in case)
- Cleans up `AbstractConnectionResolver` with doc-blocks, formatting, and rearranging where some of the methods are in the class.
- Removes multiple repeat newlines from the source files.
**No code logic has been changed in this PR**
…
**WordPress Version:** 6.5.2
=> chore: cleanup AbstractConnectionResolver before release.

access-functions.php
This ensures that the `$settings_fields` param passed to the `graphql_get_setting_section_field_value` filter is an array as documented in the filter params. Previously the value was documented to be an array, but was not always returning an array. 
closes #3138
=> fix: `$settings_fields` param on "graphql_get_setting_section_field_value" filter not passing the correct type

src/Admin/Settings/SettingsRegistry.php
This pull request enhances the tab state management for the WPGraphQL settings page by integrating query arguments with a fallback to localStorage. This ensures that tab states are sharable via URLs while maintaining backward compatibility with users' existing localStorage preferences.
closes #3142
Testing
1. Navigate to a tab using a URL with the tab query argument and verify the correct tab opens.
2. Clear the query argument, navigate to different tabs, and ensure the last active tab is remembered across page loads.
3. Click on different tabs and verify that …
=> feat: Enhance tab state management with query arguments and localStorage fallback

src/WPGraphQL.php
This adds a filter to prevent WPML from redirecting within WPGraphQL requests. 
Also, this tests the modified Github Workflow intended to run phpcbf to fix changes and commit them back to the PR. 
no
I've referred folks to this snippet many times. Adding it to core leads to a reduced support burden.
=> fix: prevent wpml from redirecting in WPGraphQL requests

.wp-env.json, tests/e2e/plugins/README.md, tests/e2e/plugins/settings-page-spec/settings-page-spec.php, tests/e2e/specs/settings-page.spec.js, tests/e2e/utils.js
Following up for https://github.com/wp-graphql/wp-graphql/pull/3143
=> test: Add e2e test coverage for tabs in the settings page

src/Registry/Utils/PostObject.php, src/Type/WPInterfaceTrait.php, tests/wpunit/InterfaceTest.php
The PR cleans up the `InterfaceTrait` class and addresses regressions in #3100 and #3112 in the following ways:
- chore: Reduce code complexity by breaking up nested conditionals into smaller methods with simpler logic. Similarly, variables were renamed and additional annotations added to improve readability.
- dev: Add new `graphql_debug()` message when a field has _no_ associated type. The faux `PostObject.ancestors` and `PostObject.parent` have been fixed to be registered as deprecated Connections (that resolve null) to prevent schema breaks for people using those deprecated fields in the same query as a `HierarchicalContentNode.ancestors/parent`.
- fix: the use of `$this->name` to …
=> fix: handle regression when implementing interface with identical args.

src/Data/Connection/AbstractConnectionResolver.php, src/Registry/Utils/TermObject.php, tests/wpunit/PostObjectConnectionQueriesTest.php
This reverts a change introduced in #3066 that could be a breaking change, and instead handles it by merging args in the connection resolver and using set_query_arg with the merged args (instead of assuming set_query_arg will do the merging under the hood).
n/a
related: #3066
related: #3161 
More info here: https://github.com/wp-graphql/wp-graphql/pull/3161#issuecomment-2204937986
=> fix: set_query_arg should not attempt to merge args

cli/wp-cli.php, src/Registry/TypeRegistry.php, src/Request.php, src/Utils/QueryAnalyzer.php, src/WPGraphQL.php, tests/wpunit/AccessFunctionsTest.php, tests/wpunit/AssertValidSchemaTest.php, tests/wpunit/CustomPostTypeTest.php, tests/wpunit/CustomTaxonomyTest.php, tests/wpunit/InterfaceTest.php, tests/wpunit/PostObjectMutationsTest.php, tests/wpunit/RequestTest.php
Any type that is registered to `eagerlyLoadType` will now only be eagerly loaded for Introspection requests (typically used for tooling such as GraphiQL IDE, Codegen, etc)
For standard execution of queries the eagerly loaded types will not be eagerly loaded which dramatically reduces the number of Object Types that are required to be generated per request.
This introduces: 
- WPGraphQL::set_is_introspection_query
- WPGraphQL::is_introspection_query
Closes #3159 
This _might_ be a breaking change if shipped as-is, as the Schema is now generated later in the …
=> fix: only `eagerlyLoadType` on introspection requests

CHANGELOG.md, composer.lock, constants.php, readme.txt, wp-graphql.php
This release contains an internal refactor for how the Type Registry is generated which should lead to significant performance improvements for most users. 
While there are no intentional breaking changes, because this change impacts every user we highly recommend testing this release thoroughly on staging servers to ensure the changes don't negatively impact your projects.
- [#3172](https://github.com/wp-graphql/wp-graphql/pull/3172): feat: only `eagerlyLoadType` on introspection requests.
- [#3181](https://github.com/wp-graphql/wp-graphql/pull/3181): ci: replace `docker-compose` commands with `docker compose`
- [#3182](https://github.com/wp-graphql/wp-graphql/pull/3182): ci: test against WP 6.6
- [#3183](https://github.com/wp-graphql/wp-graphql/pull/3183): fix: improve performance of …
=> release: v1.28.0

src/Data/Loader/UserLoader.php
This PR fixes a regression introduced in #3183 , where the lack of placeholders when interpolating the `$ids` into `$wpdb->prepare()` was throwing a `_doing_it_wrong()`.
```log
PHP Notice:  Function wpdb::prepare was called <strong>incorrectly</strong>. The query argument of wpdb::prepare() must have a placeholder. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.9.0.) in /shared/httpd/wptest/htdocs/wp-includes/functions.php on line 6085
```
Run a user query or a post query (since the post model preloads the author), and confirm no PHP Notice is …
=> fix: [regression] missing placeholder in $wpdb->prepare

CHANGELOG.md, constants.php, readme.txt, src/Data/Loader/UserLoader.php, wp-graphql.php
- [#3189](https://github.com/wp-graphql/wp-graphql/pull/3189): fix: [regression] missing placeholder in $wpdb->prepare() call
=> release: v1.28.1

src/Data/Connection/TermObjectConnectionResolver.php, tests/wpunit/TermObjectConnectionQueriesTest.php
This fixes a bug where the connectedTerms connection was returning terms of any taxonomy instead of a specific relevant taxonomy.
- [Failing Test](https://github.com/wp-graphql/wp-graphql/actions/runs/10688931102/job/29630077623#step:7:882)
- [Passing Test](https://github.com/wp-graphql/wp-graphql/actions/runs/10688938581/job/29630508452)
closes #3200 
Querying for connected terms from a category was returning both category and tag nodes:
Querying for connected terms from a category returns just category nodes:
=> fix: ensure connectedTerms returns terms for the specified taxonomy only

.github/LABELS.md
This adds a .github/LABELS.md file to describe the labels we use on the repo and can be used as a reference for other projects trying to be consistent. These labels have been implemented on the following repos: 
- wp-graphql/wp-graphql
- wp-graphql/wpgraphql-ide
- wp-graphql/wp-graphql-smart-cache
- wp-graphql/wpgraphql-acf
- wp-graphql/acf.wpgraphql.com
- wp-graphql/wpgraphql.com
- wpengine/faustjs
- wpengine/wp-graphql-content-blocks
closes #3195
=> chore: add LABELS.md

access-functions.php, src/Admin/Admin.php, src/Admin/AdminNotices.php, src/Model/Comment.php, src/Type/ObjectType/Comment.php, tests/wpunit/AdminNoticesTest.php, tests/wpunit/CommentObjectQueriesTest.php
This introduces new fields on the "Edge" on the `CommentToCommenter` connection:
- name: The display name of the comment author for this particular comment
- url: The url entered for the comment author on this particular comment
- email: The email address representing the author for this particular comment
- ipAddress: IP address of the author at the time of making this comment. 
This allows for the relational data between a Commenter and the Comment to be queried for, in addition to the Commenter node itself. 
Comment Authors can be represented by both their User object data _and_ conditional data related to a specific comment.
By exposing this edge data, the client application can …
=> feat: expose commenter edge fields

.github/LABELS.md, .github/workflows/graphiql-e2e-tests.yml, CHANGELOG.md, access-functions.php, constants.php, package-lock.json, readme.txt, src/Admin/Admin.php, src/Admin/AdminNotices.php, src/Data/Connection/TermObjectConnectionResolver.php, src/Model/Comment.php, src/Type/ObjectType/Comment.php, src/WPGraphQL.php, tests/wpunit/AdminNoticesTest.php, tests/wpunit/CommentObjectQueriesTest.php, tests/wpunit/TermObjectConnectionQueriesTest.php, wp-graphql.php
- [#3208](https://github.com/wp-graphql/wp-graphql/pull/3208): feat: expose commenter edge fields
- [#3207](https://github.com/wp-graphql/wp-graphql/pull/3207): feat: introduce get_graphql_admin_notices and convert AdminNotices class to a singleton
- [#3213](https://github.com/wp-graphql/wp-graphql/pull/3213): chore(deps): bump the npm_and_yarn group across 1 directory with 4 updates
- [#3212](https://github.com/wp-graphql/wp-graphql/pull/3212): chore(deps): bump dset from 3.1.3 to 3.1.4 in the npm_and_yarn group across 1 directory
- [#3211](https://github.com/wp-graphql/wp-graphql/pull/3211): chore: add LABELS.md
- [#3201](https://github.com/wp-graphql/wp-graphql/pull/3201): fix: ensure connectedTerms returns terms for the specified taxonomy only
- …
=> release: v1.29.0

docs/upgrading.md
This updates the docs at `wpgraphql.com/docs/upgrading` to include more details about how breaking changes will be handled going forward. 
Open to feedback and adjustments (now or in the future) to the content on the page / processes outlined on the page.
closes #3173
=> docs: update upgrading.md to highlight how breaking change releases will be handled

assets/blueprints/blueprint.json
This adds a blueprint for WordPress Playground so the plugin can be tested by users with a live preview button on WordPress.org
n/a
related: https://github.com/WordPress/blueprints/pull/74
=>  chore: add blueprint.json so WPGraphQL can be demo'd with a live preview on WordPress.org

src/Model/Post.php
**This PR addresses a deprecation warning in PHP 8+ caused by passing a null value to the trim() function within the titleRendered method. Previously, if $this->data->post_title was null, it would be passed to apply_filters, potentially resulting in a null value for trim(). This caused a warning in environments using PHP 8+.**
**Changes Made:** 
- Added a default empty string '' as a fallback for $title if $this->data->post_title is null.
- This ensures $title is always a string, preventing trim() from encountering a null value.
**Reason for Change:**
- This change prevents deprecation warnings when using PHP 8+, improving compatibility and removing unnecessary noise in logs related to deprecated behavior.
- 
**Testing Notes:**
- Verified that titleRendered returns the post title if …
=> fix: Deprecated null value warning in `titleRendered` callback

composer.json, composer.lock, phpstan.neon.dist, phpstan/constants.php, src/Data/NodeResolver.php, wp-graphql.php
This PR updates `appsero/client` to v2.0.4, which [contains the compatibility fix for WP 6.7](https://github.com/Appsero/client/releases/tag/v2.0.4)
To prevent 3rd party conflicts (and a repeat of https://github.com/wp-graphql/wp-graphql/pull/2599), use of `Appsero\Client` has been wrapped in a try/catch block. 
> [!IMPORTANT]
> This PR is based on #3242 which should be merged first.
Fixes #3239 
Alternatively tried namespacing the dependency (which is the code-ideal …
=> fix: update `appsero/client` to v2.0.4 to prevent conflicts with WP6.7

src/Data/NodeResolver.php, tests/wpunit/NodeByUriTest.php
This fixes a bug where entering a uri for an invalid node might return a node with a different uri. 
Closes #3240 
With this PR in place, following the same steps to reproduce (as documented in #3240):
Querying for a node by uri might return a node that has a _different_ uri. 
Now, querying for a node using a uri that would 404 in traditional WP will return a `null` instead of returning a node that doesn't match the uri input. 
And querying with the correct uri continues to return the expected node:
=> fix: receiving post for Incorrect uri

.cursor/prd.md, .cursorrules, .gitignore
Adds initial support for contributors that want to use the Cursor IDE. 
- updates the .gitignore to ignore the .cursor directory other than the pr…d.md file (as users can use the .cursor directory for their own personal configurations)
- add .cursor/prd.md file (Product Requirements Document) to help the cursor IDE understand the project structure, dependencies, who the audience is, etc
- add a .cursrrules file to help Cursor understand the project. Should work hand-in-hand with the PRD document helping Cursor users have a better experience
no
I'm experimenting …
=> chore: add cursor files

src/Data/PostObjectMutation.php, tests/wpunit/PostObjectMutationsTest.php
This fixes a bug where the `createPost` mutation would assign the "default category" to newly created posts even when other categories were explicitly assigned during the mutation. 
The default category should only be assigned if other categories are not assigned during the creation.
closes #3269 
Submitting the `createPost` mutation with categories would create the post with the submitted categories, but _also_ include the default category. 
Submitting the `createPost` mutation with categories would create the post with the submitted categories, and **not …
=> fix: default cat should not be added when other categories are added

src/Registry/TypeRegistry.php, src/Type/Enum/ScriptLoadingGroupEnum.php, src/Type/Enum/ScriptLoadingGroupLocationEnum.php, src/Type/InterfaceType/EnqueuedAsset.php, src/Type/ObjectType/EnqueuedScript.php, tests/wpunit/RegisteredScriptConnectionQueriesTest.php, tests/wpunit/RegisteredStylesheetConnectionQueriesTest.php
This PR adds support for exposing the `WP_Dependency->extra['group']` field to the Schema. This field is useful for developers trying to imitate WordPress's frontend, and load their assets at the correct point in the rendered document.
Cherrypicked from #3169 (with some changes noted below - @kidunot89 see bd1627b9c51257b9c6610c7d9b3ec123eeca06e2)
- Exposes the `EnqueuedAsset.group` field, which returns the `Int` value of `$asset->extra['group']`
- Change from #3169: If unset, this will return `null` for fidelity with WordPress, instead of cast to a default `0`
- Exposes the `EnqueuedScript.groupLocation` field, which returns a `ScriptLoadingGroupEnum` corresponding to header/footer …
=> feat: expose `EnqueuedAsset.group` and `EnqueuedScript.location` to schema

src/Admin/Extensions/Registry.php
This adds the WPGraphQL for Yoast SEO to the extensions page registry. 
I've verified basic functionality with the plugin. 
With the following environment:
WordPress 6.7.1
PHP: 8.2.23
WPGraphQL v1.29.3
WPGraphQL Yoast SEO Addon v4.23.2
Yoast SEO v24.2
I was able to create a post with some SEO data: 
And I was able to query the SEO data for the post: 
Here's the full query I used:
```graphql
query GetPostWithSEOFields {
post(id:83 idType:DATABASE_ID) {
id
databaseId
seo {
...PostTypeSEO
}
}
}
fragment PostTypeSEO on PostTypeSEO {
canonical
metaKeywords
metaDesc
title
}
```
And the payload I received: 
```json
{
"data": {
"post": {
"id": "cG9zdDo4Mw==",
"databaseId": 83,
"seo": { …
```
=> feat: add the WPGraphQL Yoast SEO addon to the extensions page

.github/workflows/deploy-to-wordpress.yml
Add step to install subversion. 
see: https://github.com/10up/action-wordpress-plugin-deploy/issues/158#issuecomment-2565445055
closes #3275
=> fix: update deploy-to-wordpress.yml

src/Admin/Updates/Updates.php
This fixes a bug where wp-graphql can't be found in the array of plugins when WPGraphQL is active as an mu-plugin.
Closes #3282 
Error shown when WPGraphQL is active as an MU plugin
No error:
I haven't done thorough testing yet to ensure this change doesn't accidentally cause unpredicted side-effects. The get_plugins function that we were using does use get_plugin_data under the hood, so I think this more direct call to get_plugin_data should do what we need with the …
=> fix: Error in update checker when WPGraphQL is active as an mu-plugin

CHANGELOG.md, cli/wp-cli.php, constants.php, docs/menus.md, readme.txt, src/Admin/Updates/Updates.php, wp-graphql.php
- [#3278](https://github.com/wp-graphql/wp-graphql/pull/3278): feat: add option to provide custom file path for static schemas when using the `wp graphql generate-static-schema` command
- [#3284](https://github.com/wp-graphql/wp-graphql/pull/3284): fix: fix: Updated docs link for example of hierarchical data
- [#3283](https://github.com/wp-graphql/wp-graphql/pull/3283): fix: Error in update checker when WPGraphQL is active as an mu-plugin
=> release: v1.31.0

src/Request.php, src/Server/ValidationRules/DisableIntrospection.php, tests/wpunit/AssertValidSchemaTest.php
This determines whether the DisableIntrospection rule is enabled before instantiating the rule. 
related: https://github.com/wp-graphql/wp-graphql/pull/3247#discussion_r1941685001
=> fix: update DisableIntrospection rule to pass the enabled/disabled state to class instead of being re-defined within the class

src/Request.php, src/Router.php, tests/functional/ContentTypeHeaderCept.php, tests/functional/HttpStatusCodeCept.php
This updates the response to return a 415 status code if the POST request to the endpoint is missing a "content-type" header or has an invalid value (something other than `application/json`)
This closes #1692 
**This is considered a breaking change** as clients will now have different behavior. 
While it's already documented that the content-type needs to be application/json and that errors were returned, this changes the status code from 500 to 415, which might require some clients to make adjustments. 
We've introduced the …
=> fix: return 415 status code for missing or invalid content type header

src/Type/ObjectType/MediaDetails.php, tests/wpunit/MediaItemMutationsTest.php, tests/wpunit/MediaItemQueriesTest.php
This fixes a bug where the `MediaDetails.file` field was returning a path to the file instead of the filename. 
The description of the field is: `The filename of the mediaItem`, however values such as `2025/02/test-4.png` were being returned, which is unexpected behavior.
closes: #2982 
Running a query like so:
```graphql
query GetMediaItemFilePath($id: ID!) {
mediaItem(id: $id, idType: DATABASE_ID) {
mediaDetails {
file
}
}
}
```
the file field returns a path: 
the file field returns just the filename as the field description states it will: 
Breaking Change? …
=> fix: correct the resolver for the MediaDetails.file field to return the file name

docs/submit-extension.md, src/Admin/Extensions/Extensions.php, src/Admin/Extensions/Registry.php, src/Request.php
Somehow, I shipped the `get_extensions()` function as `get_extenions()` (missing `s`). This fixes that super awkward mistake.
Considering this a regression.
🤦
**Operating System:** Ubuntu 24.04 (wsl2 + ddev + php 8.2.26)
**WordPress Version:** 6.7.1
=> fix: typo in `Extensions\Registry\get_extensions()` method name

src/Registry/Utils/PostObject.php, src/Type/ObjectType/MediaDetails.php, src/Type/ObjectType/MediaSize.php, tests/wpunit/MediaItemQueriesTest.php
This introduces some new fields for retrieving MediaItem file values: 
- `MediaDetails.filePath`: The path to the mediaItem relative to the uploads directory
- `MediaItem.file`: The filename of the mediaItem for the specified size (default size is full)
- `MediaItem.filePath`: The path to the original file relative to the uploads directory
- `MediaSize.filePath` The path of the file for the referenced size (default size is full)
related: #2982 
In #3293 we fixed a bug in how the MediaDetails.file field resolved. This introduces some new fields to access both the …
=> feat: introduce new fields for getting mediaItem files and filePaths

src/Data/TermObjectMutation.php, src/Mutation/TermObjectCreate.php, src/Utils/Utils.php, tests/wpunit/TermObjectMutationsTest.php
This fixes a bug where updating child terms to have no parent was being prevented. 
The bug was that we were using some `if ( empty() ) ` checks vs `if ( ! isset() )` checks.
So, when the ID `0` was passed for the parentId, it was bailing because it was "empty", even though it was set intentionally as 0 and 0 is a valid ID to set as the parent of a term.
closes: #3296 
Executing the updateCategory mutation on a child term, setting the parentId to `"0"` would not properly set the term's parent to `0`, leaving the child category a child category instead of a top …
=> fix: update term mutation was preventing terms from removing the parentId 

CHANGELOG.md, constants.php, package.json, readme.txt, src/Data/TermObjectMutation.php, src/Mutation/TermObjectCreate.php, src/Utils/Utils.php, tests/wpunit/TermObjectMutationsTest.php, wp-graphql.php
- [#3308](https://github.com/wp-graphql/wp-graphql/pull/3308): fix: update term mutation was preventing terms from removing the parentId
=> release: v1.32.1

src/Admin/Updates/UpdateChecker.php
This PR fixes edge cases in UpdateChecker::is_incompatible_plugin() by replacing the SemVer parser in that function with a basic `version_compare()`.
Before:
After:
**Operating System:** Ubuntu 24.04 (wsl2 + ddev + php 8.2.26)
**WordPress Version:** 6.7.1
=> fix: use `version_compare` to simplify incompatible dependent check

CHANGELOG.md, readme.txt
Looks like the changelog and upgrade notice got messed up during the v2.0 release process, I believe due to an erroneous merge conflict resolution. 
This brings the changelog up to date for v2.0
=> docs: update changelog and upgrade notice

docs/quick-start.md
This updates the quick-start guide to mention wpackagist-plugin/wp-graphql instead of wp-graphql/wp-graphql
related to #3317
=> docs: update quick-start.md

.github/workflows/generate-changeset.yml
Fixes a bug in the Github workflow that generates changesets.
Only use fromJson if there's a payload for the tags
=> fix: error in Github Workflow

.github/workflows/generate-changeset.yml
Fixes a bug in the Github workflow that generates changesets.
Use Personal Access Token instead of GITHUB_TOKEN for the `peter-evans/create-pull-request@v7` action
=> fix: error in Github Workflow 

src/Admin/Extensions/Registry.php
This adds the WPGraphQL IDE plugin to the "Extensions" page
The WPGraphQL IDE is a new version of GraphiQL that ships with the core WPGraphQL plugin.
It provides users with the ability to open the IDE from any page in WordPress via the Admin Bar, leading to increased productivity when testing queries and mutations.
The new IDE allows for users to test queries as authenticated or public users, open queries in tabs, and more. 
I've been using the new IDE daily for quite some time and I think users will enjoy it. 
It has a pluggable architecture, allowing for plugins to add new panels and interact with the IDE. 
The plugin is maintained as an external plugin to WPGraphQL as it will have it's own release cycles that may include breaking changes independent from the core WPGraphQL Schema.
=> chore: add WPGraphQL IDE to the extensions page

docs/custom-post-types.md, docs/custom-taxonomies.md, src/Registry/Utils/PostObject.php, src/Registry/Utils/TermObject.php, src/Type/ObjectType/Comment.php, src/Type/ObjectType/Menu.php, src/Type/ObjectType/User.php, src/WPGraphQL.php
This adds support for passing `graphql_description` when registering a Post Type or Taxonomy. This field will be used as the description in the Schema for the Type representing the Post Type or Taxonomy. 
In addition to adding support for the `graphql_description` arg, this also updates the descriptions for the built in post types and taxonomies, as well as the User, Menu and Comment types. 
|GraphQL Type | Current Description | Improved Description |
|---------------|---------------------|----------------------|
| Category | "The category type" | "A taxonomy term that classifies content. Categories support hierarchy and can be used to create a nested structure." |
| Post | "The post type" | "A chronological content entry typically used for blog posts, news articles, or similar date-based …
=> feat: add support for graphql_description on register_post_type and register_taxonomy

src/Request.php
This updates a `@since next-version` placeholder that didn't properly get replaced during the v2.1.0 release
=> chore: update `@since next-version` placeholder that didn't properly get replaced during release

.github/workflows/testing-integration.yml
This PR updates our Codeception workflow to trigger more often.
More specifically it now:
- Triggers on changes to Composer dependencies.
- Triggers on changes to any test files
- _Only_ triggers on changes to `'.github/workflows/testing-integration.yml'` and not on all workflow changes.
To be pedantic, you could merge this to ensure #3358 is tested
=> ci: trigger Codeception workflow more often

.github/workflows/deploy-docker-image.yml, access-functions.php, constants.php, docs/testing.md
This PR fixes the `GRAPHQL_MIN_PHP_VERSION` constant to correctly be `7.4`.
Additionally, code, workflow matrices, and doc references to v7.3 have been updated/removed.
=> fix: bump `GRAPHQL_MIN_PHP_VERSION` and remove 7.3 references

access-functions.php, src/Admin/AdminNotices.php
This PR implements a reusable PHPStan array shape for the `AdminNotices` class, removing all unintentional uses for `mixed`. (`mixed` is still used for the filter, so it can be validated).
As a result of this change, PHPStan caught (and this fixes) the incorrect validation of the filtered notice.
_There are no breaking changes in this PR_.
LLMs + IDEs + Extenders all really like shaped arrays. This is the first PR of hopefully many getting rid of the `mixed` type however possible.
=> chore: implement array shapes for `AdminNotices`

access-functions.php, activation.php, deactivation.php, src/Admin/Extensions/Extensions.php, src/Data/Cursor/PostObjectCursor.php, src/Data/Cursor/TermObjectCursor.php, src/Data/Cursor/UserCursor.php, src/Data/Loader/AbstractDataLoader.php, src/Data/UserMutation.php, src/Model/Model.php, src/Mutation/SendPasswordResetEmail.php, src/Registry/Utils/PostObject.php, src/Request.php, src/Server/WPHelper.php, src/WPGraphQL.php, wp-graphql.php
This PHP inlines return types for number functions where this change has been confirmed to be nonbreaking i.e.:
- cant cause an error
- wont cause an error
- would already cause an error
- are private and cant affect extenders/users
Native return types provide:
- better IDE support (dont need an extra doc-block parser)
- better LLM support (less likely to get confused or lose context)
- better DX (since the error happens where it's caused and not where the correct type is expected ).
- better refactorability (since we know what parts of the codebase are "safe".
No but I Should make more for all the 3.0 breaking type changes I wanna make 🧑‍🍳
=> chore: inline (non-breaking) native return types

src/Admin/AdminNotices.php, src/Admin/Extensions/Extensions.php, src/Admin/Extensions/Registry.php
This PR fixes the use of `mixed` in iterable types inside the `Admin\Extensions` and `Admin\AdminNotices` class. The only remaining uses of mixed in that class are intentional: i.e. when we're trying to validate if a filtered list of extensions has the necessary data.
Additionally, native types have been implemented in all places in those classes where to do so would not cause any breakings.
There are _no_ breaking or user-facing changes in this PR.
=> chore: add array shapes to `Admin\Extensions` and `Admin\AdminNotices`

phpcs.xml.dist, src/Data/DataSource.php, src/Data/Loader/PostTypeLoader.php, src/Data/Loader/TaxonomyLoader.php, src/Data/PostObjectMutation.php, src/Mutation/PostObjectCreate.php, src/Registry/TypeRegistry.php, src/Type/Connection/PostObjects.php, src/Type/Connection/TermObjects.php, src/Type/Enum/ContentNodeIdTypeEnum.php, src/Type/Enum/ContentTypeEnum.php, src/Type/Enum/TaxonomyEnum.php, src/Type/ObjectType/RootQuery.php, src/Type/Union/MenuItemObjectUnion.php, src/Type/Union/PostObjectUnion.php, src/Type/Union/TermObjectUnion.php, src/WPGraphQL.php
This PR:
- Inlines all (backwards-compatible) PHPDoc types into their native PHP types
- Replaces the use of `mixed` with the specific array shape (_where possible_)
- Adds type-narrowing to `WPGraphQL::get_allowed_post_types()` and `::get_allowed_taxonomies()`, so the correct traversable type of the array is hinted correctly.
References to these functions have been cleaned up accordingly (usually just by removing a `/** @var {...} */` typehint.
There are _no_ breaking changes in this PR.
=> chore: improve type-safety for `WPGraphQL` class

docs/using-data-from-custom-database-tables.md, src/AppContext.php, src/Data/Cursor/AbstractCursor.php
This PR refactors `AppContext` in the following ways:
1. Only instantiate DataLoaders when they're used instead of instantiating _all_ of them):
- Deprecates the `graphql_data_loaders` filter in favor of the new `graphql_data_loader_classes` filter. (so you can replace the loader _before_ it's instantiated
- Accessing `AppContext::$loaders` has been deprecated, in lieu of changing the property's visibility to `protected`/`private` in a future breaking release.
2. Updates the PHPStan typehinting for `::get_loader()` to correctly type-hint the loader instance for the given key.
E.g. Previously, this would have thrown a PHPStan error that `::get_public_users()` doesn't exist on `AbstractDataLoader`
```php
$users = $context->get_loader( 'user' )->get_public_users( [ ] );
````
This is a …
=> perf: refactor `AppContext` to lazy-load dataloaders

src/Data/Loader/AbstractDataLoader.php, src/Model/Avatar.php, src/Model/Comment.php, src/Model/CommentAuthor.php, src/Model/Menu.php, src/Model/MenuItem.php, src/Model/Model.php, src/Model/Plugin.php, src/Model/Post.php, src/Model/PostType.php, src/Model/Taxonomy.php, src/Model/Term.php, src/Model/Theme.php, src/Model/User.php, src/Model/UserRole.php
This PR refactors the `Model` class to reduce code complexity and improve maintainability and DX. More specifically:
- `Model::$data` is now typed via a Generic type, instead of needlessly type-hinting in child classes.
As a result, many doc types have been updated to use that generic instead of `mixed` or a lower-fidelity type.
- Splits the `wrap_fields()` method into several smaller functions (Single Responsibilities principle)
- **Fixes** the `graphql_model_field_capability` filter, so it runs on _all_ fields, not just those that are registered with a `capability` property. 
This allows the filter to be used to add capability checks to existing fields, and not just to modify preset capabilities.
- Clarifies usage of various functions, specifically that `setup()` and `tear_down()` …
=> refactor: cleanup `Model` class to reduce complexity and improve type safety

composer.lock, src/Type/WPInterfaceTrait.php, tests/wpunit/InterfaceTest.php
This PR refactors `WPInterfaceTrait` to improve the recursive handling of inherited interfaces.
The code quality and cyclomatic complexity of the class has been improved as well.
> [!IMPORTANT]
> ~This PR is based on #3382 which should be merged first.~
> ~Relevant diff: https://github.com/wp-graphql/wp-graphql/pull/3383/files/3eaa153b2399bfd4ca5732cecd9595093d145326..9d85d28915c2e71d58f7203cf6dd993cb507fc02~
> Rebased on develop
- _Possibly closes_ https://github.com/wp-graphql/wp-graphql/issues/3341
- Replication [steps](https://github.com/wp-graphql/wp-graphql/issues/3341#issuecomment-2869170869):
=> fix: cleanup `WPInterfaceTrait` logic

.github/workflows/release.yml
The release workflow was deleting changesets on master after the release, then syncing master back to develop, which included the changeset deletions. This caused subsequent PRs from develop to include unwanted changeset deletions.
Fixed by:
- Moving changeset deletion to happen on develop BEFORE merging to master
- Removing the post-release changeset deletion step on master
- Adding comments explaining the change
This ensures changesets are cleaned up without affecting future PRs.
closes #3411
=> fix: prevent changeset deletions from being synced back to develop

src/Admin/Updates/PluginsScreenLoader.php
**This PR fixes issue #3318: Bad string injection of plugin update message.**
The update message for WPGraphQL in the WordPress admin was previously injected in a way that could cause duplicate or broken messages (e.g., the word "Updated" appearing multiple times).
The fix removes forced paragraph wrapping and ensures the update message is injected cleanly, without duplication or broken HTML.
**Does this close any currently open issues?**
Closes #3318
**Any other comments?**
I tested by lowering the plugin version in [wp-graphql.php] to simulate an update, copying the plugin to the WordPress plugins directory, and viewing the update message in the WordPress admin Plugins list.
The update message now displays correctly, with no duplication or broken formatting.
**Please see the attached …
=> fix: Prevent bad string injection in plugin update message (#3318)
