wp-graphql/wp-graphql

- .travis.yml
- src/Type/PostObjectType.php
- tests/test-posts.php
- Setup travis.ci
- Adds posts tests
- Updates to resolvers on PostObjectType
> Unit Tests

- src/Type/Comment/CommentType.php
- src/Type/PostObject/PostObjectQuery.php
- src/Type/PostObject/PostObjectType.php
- src/Type/TermObject/TermObjectQuery.php
- src/Type/Union/PostObjectUnionType.php
- src/Types.php
Add PostObjectUnionType and use it for PostObjectType "parent" field and "CommentType" "commentedOn" field
Also fixes old array notations that were leftover
> PostObjectUnionType

- README.md
This adds some info about available extensions.
> Add a section in docs about available extensions

- README.md
Hey, I just spotted an inditation error 👍
> Readme: fix indentation

- src/Type/Avatar/AvatarType.php
- src/Type/User/UserType.php
- tests/test-avatar-object-queries.php
Closes #60 and #124. Adds a basic avatar test.
> Add basic avatar test.

- tests/test-comment-connection-queries.php
Closes #84. Basic tests for covering a comments connection.
> Add basic comments conection query tests.

- tests/test-plugin-object-queries.php
Closes #64.  Adds basic tests for the PluginType.
> Add PluginType tests.

- tests/test-theme-object-queries.php
Closes #72. Adds basic theme tests.
> Add basic theme tests.

- tests/test-user-object-queries.php
Closes #74.  Adds basic UserType tests.
> Adds basic UserType tests.

- src/Data/DataSource.php
- tests/test-term-object-queries.php
Closes #71. Adds basic tests for Term Object Type.
> Add basic tests for TermType object queries.

- tests/test-access-functions.php
> #92-test-access-functions

- src/Router.php
- src/Type/Plugin/PluginType.php
- src/Type/PostObject/Connection/PostObjectConnectionDefinition.php
- src/Type/PostObject/Mutation/PostObjectDelete.php
- src/Type/PostObject/PostObjectQuery.php
- src/Type/TermObject/Connection/TermObjectConnectionDefinition.php
- src/Type/TermObject/Connection/TermObjectConnectionResolver.php
- src/Type/TermObject/TermObjectQuery.php
- src/Type/Theme/ThemeType.php
- src/Type/Union/PostObjectUnionType.php
- tests/test-avatar-object-queries.php
- tests/test-media-item-queries.php
- tests/test-plugin-queries.php
- tests/test-post-connection-queries.php
- tests/test-post-object-mutations.php
- tests/test-post-object-queries.php
- tests/test-post-type-object-queries.php
- tests/test-router.php
- tests/test-term-object-queries.php
- tests/test-theme-connection-queries.php
- tests/test-theme-queries.php
- tests/test-user-object-queries.php
> #78 - test router

- wp-graphql.php
Handle rewrite rule flushes automatically. This will take that responsibility off the user. Resolves #196.
Also, sets version into option table so future versions can execute actions on upgrades.
> Activation and deactivation hooks

- CONTRIBUTING.md
- README.md
- src/Router.php
- wp-graphql.php
* Inline docblocks
* CONTRIBUTING.md
> Inline docs

- README.md
- readme.txt
- wp-graphql.php
> #217 Document the required PHP version

- wp-graphql.php
This moves the ‘graphql_execute’ hook to happen right after execution. Allowing for Tracing to be hooked in for post execution logging. Then, this filters the results, then another action is fired before returning the response.
This allows for tracing to be filtered into the response OR just enabled server side for tracking behind the scenes and not output in the response.
Additionally, this changes the “execute” method to the newer “executeAndReturnResult” which is where the “extension” support has been added in GraphQL php.
> #225 - GraphQL Tracing Support

- src/Router.php
- This addresses #227, and sets the HTTP status as 403 for requests that are not authenticated. It will still execute and return the request, but the 403 status is something clients can use to ask the user to re-authenticate, or refresh a token, etc.
For authenticated requests, the status is 200.
For requests where there’s an error in the request itself (for example, no request data, or an empty “query”), the status will be 500.
> #227 - Return 403 for unauthenticated requests

- src/Data/Config.php
> #232 - fix placeholder in wpdb->prepare

- src/Router.php
This adds support for the preflight requests that HTTP clients such as Axios and Apollo use.
This also adds a filter to the status header so folks can override it as needed
Addresses #256
> #256 - Preflight Request Support

- src/Type/Plugin/PluginType.php
- tests/test-plugin-queries.php
> Change plugin version to string

- wp-graphql
> #337 - Remove Ghost File

- .travis.yml
Related to #334
https://github.com/travis-ci/travis-ci/issues/4579#issuecomment-127972205
> CI: Do not cache Composer vendor folder

- src/Type/User/Connection/UserConnectionArgs.php
> fix User nicename type

- coveralls.yml
- wp-graphql.php
- Adding `GRAPHQL_DEBUG` constant
- removing unused coveralls.yml file (the proper file is .coveralls.yml)
> Release v0.0.23 (missed files)

- src/Utils/InstrumentSchema.php
> Filter Field Definition in Schema Instrumentation

- src/Type/PostObject/Connection/PostObjectConnectionArgs.php
- tests/wpunit/PostObjectConnectionQueriesTest.php
> fix: hasPassword type should be boolean

- src/Type/MediaItem/Mutation/MediaItemCreate.php
- src/Type/MediaItem/Mutation/MediaItemMutation.php
- src/Type/MediaItem/Mutation/MediaItemUpdate.php
- src/Type/PostObject/Mutation/PostObjectCreate.php
- src/Type/TermObject/Mutation/TermObjectCreate.php
- src/Type/TermObject/Mutation/TermObjectUpdate.php
- src/Type/User/Mutation/UserCreate.php
- src/Type/User/Mutation/UserMutation.php
- src/Type/User/Mutation/UserUpdate.php
- tests/_data/config.php
> #394 - Set Post Status Late on Create Mutations

- src/Router.php
Referenced params missing from prepare_headers() and after_execute()
methods.
None opened, just Slack discussion.
… …
> Fix undefined vars in Router introduced in v0.0.25

- src/Type/PostObject/PostObjectType.php
- tests/wpunit/PostObjectQueriesTest.php
The arg passed is an array of taxonomies itself, and so doesn't need to
be wrapped in one.
See #400 
See #400
…
**Operating System:** See #400
**WordPress Version:** See #400
> Fix for issue #400 😺😺😺😺

- tests/functional/PostListWithDifferentStatusCept.php
> Update comment for clarity.

- src/Type/PostObject/PostObjectType.php
adds $post->ID to the_title filter
#470 
…
**Operating System:** Ubuntu 18.04 …
> $id added to the the_title filter call

- src/Type/User/Mutation/UserMutation.php
This improves an error message when a user attempts to remove user editing permissions from their own user account.
Yes: https://github.com/wp-graphql/wp-graphql/issues/500 …
> Update UserMutation.php to improve error message

- README.md
> * * added to debugging to make it visual

- Dockerfile
- README.md
- docker-tasks/run-test-environment/docker-compose.yml
- run-docker-test-environment.sh
- src/Type/Object/PostObject.php
- [x ] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x ] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!
* Restored a line of PHP code that was removed so that all tests pass now
* No longer dynamically creating a "tester" Docker container user for …
> CI-5745-2 | Fixing PHP code to get the tests passing; Fixing some broken Docker configuration.

- src/Type/Object/Settings.php
- tests/wpunit/SettingsMutationsTest.php
This fixes #528. When the day of the week setting was set to Sunday an error was thrown. This fixes that and allows Sunday to be a valid value.
Original PR by @davidwhiletrue, but the v0.1.0 refactor lead to conflicts, so this just resolves those. 
#528
> Davidwhiletrue bugfix/528

- src/Connection/PostObjects.php
- src/Data/Config.php
- src/Data/PostObjectConnectionResolver.php
- src/Type/Object/PostObject.php
- src/TypeRegistry.php
- tests/wpunit/PostObjectConnectionQueriesTest.php
- wp-graphql.php
Reverts wp-graphql/wp-graphql#588
> Revert "#326 - Add Revisions Support"

- src/Connection/PostObjects.php
- src/Data/Config.php
- src/Data/PostObjectConnectionResolver.php
- src/Type/Object/PostObject.php
- src/TypeRegistry.php
- tests/wpunit/PostObjectConnectionQueriesTest.php
- wp-graphql.php
Reverts wp-graphql/wp-graphql#595
> Revert "Revert "#326 - Add Revisions Support""

- src/Mutation/PostObjectCreate.php
- src/Type/Object/PostObject.php
Just a typo
I guess not :)
See above
Thank you for this plugin!
I guess it's not relevant. …
> Ttypo in comments field description (compatability => compatibility)

- src/Type/Object/RootQuery.php
Fixes incorrect types on RootQuery `[type]By` query args
#632 
Hello
**Operating System:**  Windows …
> #632 fix types

- tests/wpunit/TermObjectQueriesTest.php
adds test for quering term children
#575
accidently used my develop branch here https://github.com/wp-graphql/wp-graphql/pull/670
Where has this been …
> add test for term children #575

- src/Model/Post.php
> Fixing issue with auto-draft posts being visible

- src/Data/DataSource.php
- src/Data/ThemeConnectionResolver.php
- src/Model/Menu.php
- src/Model/MenuItem.php
- src/Model/Model.php
- src/Model/Post.php
- src/Model/Term.php
- src/Model/Theme.php
- src/Model/User.php
- src/Type/Object/Theme.php
- tests/wpunit/NodesTest.php
- tests/wpunit/ThemeConnectionQueriesTest.php
- tests/wpunit/ThemeObjectQueriesTest.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
Implements the model layer for Theme objects and fixes up/expands testing
#606 
…
**Operating …
> Feature/606 - Theme Model

- src/Data/DataSource.php
- src/Data/PluginConnectionResolver.php
- src/Model/Plugin.php
- src/Type/Object/Plugin.php
- tests/wpunit/NodesTest.php
- tests/wpunit/PluginConnectionQueriesTest.php
- tests/wpunit/PluginObjectQueriesTest.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
Adds a Model for Plugins. Now all plugins are private unless you have the `update_plugins` cap. Adjusted the tests to account for this.
#607 
…
Where has …
> Feature/607 - Plugin Model

- src/Connection/PostObjects.php
> Only pass data to model when resolving rather than registering

- README.md
- docs/README.md
- src/Data/DataSource.php
- src/Data/MenuItemConnectionResolver.php
- src/Request.php
- src/Type/Enum/MenuLocationEnum.php
- src/Type/Enum/TimezoneEnum.php
- src/TypeRegistry.php
- src/Utils/InstrumentSchema.php
- tests/wpunit/PostObjectConnectionQueriesTest.php
- tests/wpunit/PostObjectQueriesTest.php
- wp-graphql.php
- none
- #676: New `TimezoneEnum` type added to the Schema
- #719: New `graphql_menu_item_connection_args` and `graphql_menu_item_connection_query_args` filters added to the MenuItemConnectionResolver. Thanks @epeli! 
- #714 Fixes global $post not properly being setup before resolving fields for posts. Thanks @epeli!
- #716: Adjusts how the `MenuLocationEnum` values are determined to include all locations, not just locations with a menu already assigned.
> 🚀 Release v0.2.3

- src/Data/DataSource.php
Fixes php warning in `get_registered_nav_menu_locations()`
closes #726
> 🐛 BUGFIX - PHP Warning in DataSource.php

- src/AppContext.php
- src/Data/Connection/AbstractConnectionResolver.php
- src/Data/Connection/UserConnectionResolver.php
- src/Data/DataSource.php
- src/Type/Object/PostObject.php
Adds the ability to add new DataLoaders to the AppContext.
> Another attempt at adding the additional loaders

- src/Data/DataSource.php
- src/Model/Avatar.php
- src/Type/Object/Avatar.php
- src/Type/Object/User.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
Adds a model for the Avatar object
#756 
…
> Feature/756 - Avatar model

- src/Connection/UserRoles.php
- src/Data/Connection/UserRoleConnectionResolver.php
- src/Data/DataSource.php
- src/Model/UserRole.php
- src/Type/Object/RootQuery.php
- src/Type/Object/User.php
- src/Type/Object/UserRole.php
- tests/wpunit/ModelUserTest.php
- tests/wpunit/UserObjectMutationsTest.php
- tests/wpunit/UserObjectQueriesTest.php
- tests/wpunit/UserRoleConnectionQueriesTest.php
- tests/wpunit/ViewerQueryTest.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_framework_classmap.php
- vendor/composer/autoload_static.php
Adding a model layer for user roles
#763 
…
> Feature/763 Model for user roles

- src/Data/DataSource.php
- src/Model/CommentAuthor.php
- src/Type/Object/Comment.php
- src/Type/Object/CommentAuthor.php
- tests/wpunit/CommentObjectQueriesTest.php
- tests/wpunit/NodesTest.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
Adds a model layer for the CommentAuthor object
#757 
Also fixed some tests with comments and a weird bug …
> Feature/757: Model for CommentAuthor

- src/Connection/TermObjects.php
- src/Data/DataSource.php
- src/Model/Taxonomy.php
- src/Type/Object/Taxonomy.php
- tests/wpunit/TaxonomyObjectQueriesTest.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
Adds the model layer to taxonomies
#698 
…
> Feature/698 Taxonomy model

- src/Model/Avatar.php
- src/Model/Comment.php
- src/Model/CommentAuthor.php
- src/Model/Menu.php
- src/Model/MenuItem.php
- src/Model/Model.php
- src/Model/Plugin.php
- src/Model/Post.php
- src/Model/PostType.php
- src/Model/Taxonomy.php
- src/Model/Term.php
- src/Model/Theme.php
- src/Model/User.php
- src/Model/UserRole.php
Cleaning up some things in the model layers
#699 
Should be broken out into commits pretty well, you can go through them one by one to see everything that …
> Feature/699 - Model layer cleanup

- src/Model/Post.php
> Removing older filter code I forgot

- src/Data/DataSource.php
Adds context instance to graphql_resolve_node hook for use in custom type resolve functions
…
… …
> Adds context instance to graphql_resolve_node hook

- src/Data/Config.php
Uses the posts table from the `$wpdb` global instead of hard coding it.
https://github.com/wp-graphql/wp-graphql/issues/785
… …
> Remove hard coded table prefix

- wp-graphql.php
#803 - Allowed Post Types and Taxonomies were hooked in _too_ early causing issues for Custom Post Types
closes #803
> :bug: BUGFIX

- src/Type/Object/PostObject.php
> Restore missing resolver

- .travis.yml
- Dockerfile.test-base
- Dockerfile.xdebug
- README.md
--------------------------------------------------
- Updated PHP Composer and XDebug versions.
- Updated `docker-compose` version used by Travis
- Also updated xdebug README instructions.  
N/A
N/A
N/A
OS X …
> CI-6319 | Updating PHP composer, Xdebug, docker-compose versions; updating XDebug README info

- src/Connection/TermObjects.php
It's false https://github.com/wp-graphql/wp-graphql/blob/ea881ecbecc7c03fa10f7e82acffb01e293ca0d2/src/Data/Connection/TermObjectConnectionResolver.php#L64-L67
> Fix hideEmpty description

- src/Data/Connection/AbstractConnectionResolver.php
Fixes #840 where an edge resolver doesn't have visibility of the source node.
#840 
…
**Operating …
> Pass $source to edge resolver

- src/TypeRegistry.php
- wp-graphql.php
Implements static `clear_schema()` in `WPGraphQL` class.
#846 
…
**Operating System:** Ubuntu 18.04 …
> Adds clear_schema

- src/Model/MenuItem.php
- src/TypeRegistry.php
> #839 - Fix typo with cssClasses

- src/Model/Post.php
- src/Type/Object/PostObject.php
…l layer.
- This moves the resolvers out of the models and into the `register_post_object_types` function. `srcSet` and `sizes` return varying values that rely on a provided parameter, and shouldn't be pre-queried in the mode.
- Cleans up of the `PostObject` model class, `register_post_object_types` function, and `get_post_object_fields` function and bring them into compliance with `WPCS` on everything except class name and filename.
Does this close any …
> Fixes attachment size issue

- .travis.yml
- composer.json
- composer.lock
- phpcs.xml.dist
Added coding standards check in the composer, and also fixed the travis to run it using composer (since it already uses it).
**This fix doesn't include the fix for the issues found by the phpcs**
This means that the travis will, probably, fail. If you want me to fix the issues I can do it, although the current status when running phpcs is the following:
<details>
<summary>Summary of the phpcs scan</summary>
<pre>
PHP CODE SNIFFER REPORT SUMMARY
----------------------------------------------------------------------
FILE                                                  ERRORS  WARNINGS
---------------------------------------------------------------------- …
> Update coding standards

- src/Model/Model.php
- src/Model/Post.php
- tests/wpunit/CustomTaxonomyTest.php
> Setup post data just before executing resolver functions 

- src/Data/PostObjectMutation.php
- wp-graphql.php
> #989 - Ensure inputs for taxonomies are respected on post object mutations

- src/Model/Comment.php
- src/Model/Post.php
- src/Model/PostType.php
- src/Model/Taxonomy.php
- src/Model/User.php
Just some formatting cleanup in the model layer.
Closes #779 
…
**WordPress …
> Cleaning up code in the model layer

- docs/source/getting-started/install-and-activate.mdx
Informs users that the plugin is also available on Packagist and not simply via GitHub :)
- [ ✅] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [ ✅] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!
Adds composer installation instructions …
> 📝Docs - add composer instructions for core installation

- docs/source/extensions/wpgraphql-advanced-custom-fields.mdx
Just fixes some typos in the acf docs.
> Fix typos in ACF Docs.

- src/Router.php
- Adds a more strict conditional to `Router::is_graphql_request()`.
#1021 
… …
> Adds more strict check to "is_graphql_request()"

- src/Model/Post.php
- src/Type/Object/PostObject.php
- tests/wpunit/PostObjectQueriesTest.php
Follow-up to #1029 
@CodeProKid @zgordon This is a follow up to #1029 
I'm having some funky git issues locally I think. I couldn't pull Zac's branch, but now I'm having other strange issues. 
Anyway, this addresses the formatting suggestions from @CodeProKid and fixes the edge case @zgordon was running into
> #1029 follow up

- src/Router.php
Fixes bug related to WP installations parked at subdomains.
…
…
**WordPress …
> bugfix for "Router::is_graphql_request"

- access-functions.php
- src/Registry/TypeRegistry.php
- tests/wpunit/TypesTest.php
See: #1053 
This addresses some issues some extensions reported
> #1052 follow-up

- docs/gatsby-config.js
- docs/src/gatsby-theme-apollo-docs/components/page-layout.js
This adds the proper configuration and components to support Algolia Docsearch.
closes #1036
> #1036 - Add Docsearch

- src/Type/WPUnionType.php
Adds a `__get` function to `WPUnionType` so filters can access the `$type_registry` instance on the object.
…
… …
> initial commit

- tests/wpunit/PostTypeObjectQueriesTest.php
- wp-graphql.php
This helps resolve #1083 to allow `post_format` as a taxonomy type.
#1083
> adds support for post_format as a taxonomy

- docs/src/gatsby-theme-apollo-core/components/sidebar-nav/category.js
- docs/src/gatsby-theme-apollo-core/components/sidebar-nav/index.js
Address accessibility issues on the documentation site. Mostly aria and color contrast ratio elements for now.
#1049 
None
Kicking this PR off. **It will be a WIP as I have some questions about the theme and such.**
FF, Chrome
> Docs: Accessibility

- docs/source/extensions/wpgraphql-jwt-authentication.mdx
> Docs: Adds JWT plugins readme

- docs/gatsby-config.js
- docs/source/extensions/wpgraphql-seopress.mdx
Adding docs for a new plugin
https://github.com/moonmeister/wp-graphql-seopress
> feat: add seopress plugin to docs

- src/Data/NodeResolver.php
- src/Model/Model.php
This updates the NodeResolver class to better resolve Posts by their path.
closes #1142 
> #1142 - Child Pages not resolving by path in NodeResolver

- docs/source/getting-started/install-and-activate.mdx
…
Firecamp GraphQL IDE added in the list. Doc changes.
> Firecamp link added

- src/Data/Connection/AbstractConnectionResolver.php
`AbstractConnectionResolver::is_valid_model()` isolates model validation in `get_nodes()` for nodes not sourced by `Model` classes, helping keep the extending classes dry.
… …
> is_valid_model() added.

- tests/wpunit/ModelUserTest.php
Fixes tests for php 7.4
closes #1213
> #1213 - fix tests for PHP 7.4

- docs/source/getting-started/install-and-activate.mdx
I have added Postman to the list of GraphQL IDE Tools. Currently I am rebuilding the blog using wpgraphql and testing graphql calls with Postman. 
There is no open issue, I thought it would be a nice addition to the docs.
(If it’s long, please paste to https://ghostbin.com/ …
> added Postman client to list GraphQL IDE tools

- src/Data/Connection/AbstractConnectionResolver.php
Add ability for extension plugins to modify the connection pages sizes.
wp-graphql-offset-pagination would use this 
https://github.com/valu-digital/wp-graphql-offset-pagination/pull/5
> Add graphql_connection_amount_requested filter

- docs/README.md
- docs/gatsby-config.js
- docs/gatsby-node.js
- docs/package.json
- docs/src/gatsby-theme-apollo-docs/components/template.js
- docs/yarn.lock
I went to resolve another docs issue for plugins and was having a rough time for some reason getting the site working. Did some updates and other cleanup and all is happy now (best I can tell from clicking around the site). 
I'll open the original work I was going to do in another pr.
> docs site udpates and cleanup

- phpcs.xml
- src/Connection/PostObjects.php
- src/Data/Config.php
- src/Data/Connection/AbstractConnectionResolver.php
- src/Data/Connection/CommentConnectionResolver.php
- src/Data/Connection/MenuItemConnectionResolver.php
- src/Data/Connection/UserConnectionResolver.php
- src/Data/Cursor/CursorBuilder.php
- src/Data/Cursor/PostObjectCursor.php
- src/Data/Cursor/UserCursor.php
- src/Data/DataSource.php
- src/Data/NodeResolver.php
- src/Data/UserMutation.php
- src/Model/Comment.php
- src/Mutation/CommentDelete.php
- src/Mutation/MediaItemUpdate.php
- src/Mutation/PostObjectCreate.php
- src/Mutation/PostObjectUpdate.php
- src/Mutation/UserRegister.php
- src/Registry/TypeRegistry.php
- src/Type/Enum/ContentNodeIdTypeEnum.php
- src/Type/Enum/TimezoneEnum.php
- src/Type/Object/PostObject.php
- src/Type/Object/TermObject.php
- src/Type/WPEnumType.php
- src/Type/WPInputObjectType.php
- src/Type/WPInterfaceType.php
- src/Type/WPObjectType.php
- src/Utils/Utils.php
- wp-graphql.php
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.
Made a bunch of updates to the PHPCS file. I disabled a bunch of rules that didn't need to be disabled, and I went through a bunch of them one by one and fixed issues where I thought we should be enforcing rules. This should get us in a much better spot, and we can start deciding what other rules we should start enforcing outside of the WP coding standards.
I also broke out everything into separate commits 😉so you can go through the changes one by one.
Does …
> PHPCS updates

- src/Data/Connection/AbstractConnectionResolver.php
@jasonbahl I couldn't push straight up to develop because of github's settings. Here's the fix to get PHPCS passing.
> Fixing PHPCS issue

- src/Model/Post.php
- vendor/composer/autoload_real.php
Reverts wp-graphql/wp-graphql#1253
> Revert "Makes "allowed_restricted_fields" extendable for class child classes"

- .github/PULL_REQUEST_TEMPLATE.md
- src/Data/Loader/AbstractDataLoader.php
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.
Fixing some small issues from the 0.8.4 release
This closes #1282, closes #1283.
…
**Operating …
> Fixing some small issues from the latest release

- src/Model/Comment.php
- src/Model/Menu.php
- src/Model/MenuItem.php
- src/Model/Model.php
- src/Model/Post.php
- src/Model/PostType.php
- src/Model/Taxonomy.php
- src/Model/Term.php
- src/Model/Theme.php
- src/Model/User.php
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.
This makes the model layer a little more flexible so that _any_ data can be pushed through the model classes for modeling. I also added a param to a filter that was needed per some convo's with @jasonbahl and @kidunot89 
…
(If it’s long, please paste to https://ghostbin.com/ and …
> Make model layer more flexible

- src/Utils/InstrumentSchema.php
- tests/wpunit/PreresolveTest.php
Add an ability to short circuit field resolvers. 
Closes #1247
> Add` graphql_pre_resolve_field` filter

- src/Model/Comment.php
- src/Model/Menu.php
- src/Model/MenuItem.php
- src/Model/Model.php
- src/Model/Post.php
- src/Model/PostType.php
- src/Model/Taxonomy.php
- src/Model/Term.php
- src/Model/Theme.php
- src/Model/User.php
Reverts wp-graphql/wp-graphql#1281
> Revert "Make model layer more flexible"

- src/AppContext.php
- src/Data/DataSource.php
Bugfix for v0.9.0 release.
- Update node resolver to resolve menus properly
- Update AppContext to have a nav_menu loader registered
closes #1321
> Fix menus not resolving with node query

- docs/source/getting-started/posts.mdx
A simple update to the link to the docs for WP_Query 😁 
No
No
N/A - Just a change to the docs.
> bugfix/Update WP_Query docs link

- phpstan.neon
- phpstan.neon.dist
Run: `vendor/bin/phpstan analyze -l 0`
There are critical errors in the plugin.
Related to #940
> Complete PHPStan configuration

- src/Type/Object/MediaItemMeta.php
> fix: Update focalLength to be a float instead of an int

- src/Model/Post.php
- src/Type/Object/PostObject.php
Add field isPostsPage
Add new isPostsPage field to check if page is the posts page.
Did not see any issues on this.
Very small change, but hope it helps. Thanks
**Operating …
> Add field isPostsPage to check if page is the main posts archive page

- docs/source/extensions/wpgraphql-extensions.mdx
Adds WPGraphQL Send Email plugin to the extensions page.
> Add WPGraphQL Send Email plugin

- docs/source/extensions/wpgraphql-extensions.mdx
Adds Posts 2 Posts extension to docs.
No
> Add Posts 2 Posts extension to docs

- docs/source/extensions/wpgraphql-extensions.mdx
add a link to the new wp-graphql-wpml plugin that improves using wpgraphql together with WPML
not sure
N/A
this is just a doc change
**Operating System:** N/A
**WordPress …
> add link for wp-graphql-wpml plugin

- src/Type/WPInterfaceType.php
Adds centralized hook to allow for filtering interface resolve type.
@jasonbahl This is needed for the `UniformResourceIdentifiable` interface to play nice with the `Product` types using the following.
```
/**
* Injects interface type resolvers that resolve to Product(Interface) type and retrieves the proper Product child types
*
* @param WPObjectType    $type          Type be resolve to.
* @param mixed           $value         Object for which the …
```
> "graphql_interface_resolve_type" hook added

- src/Data/Connection/PostObjectConnectionResolver.php
- wp-graphql.php
- (#1488) Fixes  bug in PostObjectConnectionResolver where empty array for `post__in` argument is not properly handled. Thanks @jonshipman!
> Release v0.13.3

- src/Router.php
- Only execute checks for $_SERVER if the $_GET request doesn't match the host
closes #1517
> #1517 - fix ?graphql endpoint

- .github/workflows/wordpress-coding-standards.yml
> Make caching effective, fix things in CI

- .github/workflows/code-quality.yml
> Make caching effective, upgrade actions in CI

- .github/workflows/code-quality.yml
- composer.json
1. remove redundant class loader
1. calling scripts the Composer way https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands
💡 This needs lock file update!!
> Fix composer config

- docs/source/extending/resolvers.mdx
This PR fixes the Overriding Resolvers code example which is currently not working.
> Fix Overriding Resolvers code example

- .gitattributes
- README.md
- readme.txt
- wp-graphql.php
This release updates the README.md and README.txt to prepare the plugin for deploying to the WordPress.org plugin repo. 
There is no change in functionality to the GraphQL API in this release.
> Release v0.15.4

- docs/source/getting-started/interacting-with-wpgraphql.mdx
Updated doc with GraphQL tool list.
> Firecamp's GraphQL Playground linked

- readme.txt
> I've been added

- src/Connection/ContentTypes.php
Each post type now has there in connection to their ContentType node. This PR changes this so that the `contentType` connection is registered on the common `ContentNode` interface.
Previously, you couldn’t do this query:
```graphql
query MyQuery {
contentNodes {
nodes {
contentType {
node {
name
}
}
}
}
}
```
You had to do this:
```graphql
query MyQuery {
contentNodes {
nodes {
... on Post {
contentType {
node {
name
}
}
}
... on Page {
contentType {
node {
name
}
}
}
}
}
}
```
Closes #1607
> Move `contentType` connection to the `ContentNode` interface

- src/Request.php
- [ :heavy_check_mark: ] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [ :heavy_check_mark: ] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!
Change the $variables parameters in docblock from string to array …
> #1563 - update docblock in do_graphql_request

- CHANGELOG.md
- readme.txt
- src/Data/NodeResolver.php
- src/Model/Post.php
- src/Type/Object/RootQuery.php
- tests/wpunit/NodeByUriTest.php
- vendor/composer/InstalledVersions.php
- vendor/composer/installed.php
- wp-graphql.php
- ([#1670](https://github.com/wp-graphql/wp-graphql/issues/1670)) Fixes a bug with querying pages that are set as to be the posts page
> Release: v1.1.1

- phpstan.neon.dist
> Fix 1-12 regexp in phpstan.neon.dist

- src/Type/Enum/ContentTypeEnum.php
I think, there should be an option to retrieve non-public post types.
> Remove public condition

- src/Telemetry/Tracker.php
Fix deprecation: Required parameter $extra_info follows optional parameter $event_type in wp-graphql/src/Telemetry/Tracker.php on line 193
No
**Operating System: Mac OS Big Sur
**WordPress Version: 5.6
> Fix deprecation

- .github/PULL_REQUEST_TEMPLATE.md
> Hide message to user in PR template

- .github/workflows/testing-integration.yml
Defines CI jobs only once: in the matrix.
> Remove redundant CI jobs Act 2

- src/Model/Post.php
- src/Type/ObjectType/PostObject.php
- tests/wpunit/PostObjectQueriesTest.php
Adds an isPrivacyPage field similar like isFrontPage
…
…
This is my first PR ever, so forgive me if I did something wrong, I think i've followed all the guidelines
…
> added isPrivacyPage to schema

- src/Type/WPEnumType.php
- tests/wpunit/WPEnumTypeTest.php
Add WP apply filter for graphql_enum_values while values for the enum are being prepared.
#1587 
…
> Add apply for graphql_enum_values enum filter

- access-functions.php
- src/Type/Enum/AvatarRatingEnum.php
- src/Type/Enum/CommentsConnectionOrderbyEnum.php
- src/Type/Enum/UsersConnectionSearchColumnEnum.php
- src/Type/Input/UsersConnectionOrderbyInput.php
Add missing field descriptions warned about by graphql schema linter. This is only a few of the issues. Pushing up in small consumable PRs.
Not completely, but part of #1790  
…
> Add field descriptions to resolve schema warning

- src/Type/ObjectType/RootQuery.php
- tests/wpunit/NodeByUriTest.php
follow up to #1793. Adds additional test and resolves issue specific to the source_url entry for media
Follow up to #1783 / #1793
> #1783/#1793 - follow-up

- tests/wpunit/TypesTest.php
This test action was not being invoked.  Fixes that.
No
…
> Make sure the custom type registration test was running

- .github/workflows/schema-linter.yml
- src/Registry/TypeRegistry.php
- src/Type/Enum/ContentNodeIdTypeEnum.php
- src/Type/ObjectType/SettingGroup.php
- src/Type/ObjectType/Settings.php
- src/Type/WPInputObjectType.php
Identify and add a few remaining root query descriptions.
Enable the schema linter but exclude a few types of linting errors that we still have left to remedy.
#1790 
https://github.com/wp-graphql/wp-graphql/pull/1829
…
> Add description and enable schema linter with exclusions

- .github/workflows/schema-linter.yml
> Separate schema linting steps

- src/Router.php
It lowers the amount of data sent.
No.
It is literally a litter in the code and in the requests.  There is absolutely no point in sending that header.
**Operating System:** Archlinux
**WordPress Version:** N/A
> Remove `x-hacker` header.

- src/Type/WPInterfaceType.php
- src/Type/WPUnionType.php
Documentation for params to the right object type.
#1554 
…
> Update doc block params from WPObjectType

- src/Router.php
Adds a filter for capturing/reporting errors before the query results are returned.
…
…
**Operating System:** Ubuntu 20.04
**WordPress Version:** 5.7.2
> 'graphql_http_request_response_errors' hook added.

- .github/workflows/deploy-to-wordpress.yml
- .github/workflows/schema-linter.yml
- .github/workflows/upload-schema-artifact.yml
Use graphql inspector (see the [action](https://github.com/marketplace/actions/graphql-inspector)) cli to compare latest tagged version with the schema created by this PR.
https://github.com/wp-graphql/wp-graphql/issues/335
…
> Add schema inspector for breaking changes

- composer.lock
- src/Data/Connection/AbstractConnectionResolver.php
- src/Data/Connection/PostObjectConnectionResolver.php
- src/Data/Connection/UserConnectionResolver.php
- src/Registry/TypeRegistry.php
- src/Utils/InstrumentSchema.php
- tests/wpunit/TypesTest.php
- Add `auth` and `queryClass` support the `register_graphql_connection()` configuration, allowing for auth restricting of connections, as well as querying results with a custom query class.
- `TypesTest` upgraded to a `WPGraphQLTestCase` and new test added.
#1935 
…
**Operating System:** Mac OS
**WordPress Version:** 5.7.2
> Extended connection configurations

- bin/run-docker.sh
`composer run-app` results in error. When the WP/PHP environment variables were added recently, need to also switch to `docker compose up`.
…
…
> Use docker compose instead of docker-compose for up

- .github/workflows/deploy-docker-image.yml
- docker/testing.entrypoint.sh
Push docker images on tag.
Docker build with multiple tags for 'latest'.
Docker image re-use as part of https://github.com/wp-graphql/wp-graphql-persisted-queries/issues/1.
…
…
…
> Get tag from REF.

- src/Utils/Preview.php
…
Fixes a bug interfering with various plugins including WPML and wp-hotel-booking-authorize-payment
…
Closes [this](https://github.com/wp-graphql/wp-graphql/issues/1983) issue
https://github.com/wp-graphql/wp-graphql/issues/1983
[06-Jul-2021 21:08:51 UTC] PHP Notice: Trying to access array offset on value of type bool in /nas/content/live/devcasa/wp-content/plugins/wp-hotel-booking-authorize-payment/inc/class-hb-payment-gateway …
> fix for bug 1983

- docs/concepts.md
fix relay.dev links for object-identification / mutations / connections
> fix: concepts.md broken links to relay.dev

- .codeclimate.yml
- src/Data/Loader/UserLoader.php
- src/Model/User.php
- src/Mutation/ResetUserPassword.php
- src/Mutation/SendPasswordResetEmail.php
- src/Mutation/UserCreate.php
- src/Mutation/UserDelete.php
- src/Mutation/UserRegister.php
- src/Mutation/UserUpdate.php
- tests/wpunit/UserObjectMutationsTest.php
This is the same PR as #1684, just opened from a branch on this Repo as @chriszarate no longer is with Quartz and I don't have permission to push iterations to that fork. 
Will use this PR for iteration and close #1684
> Fix negative performance with Post / User model

- docs/intro-to-graphql.md
…
Just simple typo fix in the docs
P.-S. sorry for all these commits, I didn't figure out how to amend within GitHub web interface.
> Fix one md link syntax in the docs

- CHANGELOG.md
- readme.txt
- src/WPGraphQL.php
- wp-graphql.php
- No functional changes from v1.6.8. Fixing an issue with deploy to WordPress.org
> Release v1.6.9

- src/Registry/TypeRegistry.php
Prevents PHP notices described in issue. 
Fixes issue #2176 PHP Notice for missing clientMutationId
> only set payload clientMutationId if inputed

- .github/workflows/codeql-analysis.yml
This adds a new workflow to analyze JavaScript code on pull requests
> Add JavaScript code analysis workflow

- .github/workflows/deploy-docker-image.yml
- .github/workflows/testing-integration.yml
- bin/run-docker.sh
- docker-compose.yml
Add WP version 5.9 to the matrix list of ci/cd workflows and as the default if non is provided.
…
…
> Add WP version 5.9 to build matrix

- docs/authentication.md
WordPress 5.6 introduced a new system for making authenticated requests to various WordPress APIs -- Application Passwords.
No
…
> Documentation for authentication with Wordpress application password.

- src/Connection/Comments.php
- src/Connection/PostObjects.php
- src/Connection/Taxonomies.php
- src/Connection/TermObjects.php
- src/Data/DataSource.php
- src/Data/Loader/UserLoader.php
- src/Data/NodeResolver.php
- src/Data/PostObjectMutation.php
- src/Mutation/PostObjectCreate.php
- src/Registry/TypeRegistry.php
- src/Type/Enum/ContentNodeIdTypeEnum.php
- src/Type/Enum/ContentTypeEnum.php
- src/Type/Enum/TaxonomyEnum.php
- src/Type/Enum/TermNodeIdTypeEnum.php
- src/Type/InterfaceType/MenuItemLinkable.php
- src/Type/InterfaceType/UniformResourceIdentifiable.php
- src/Type/ObjectType/RootQuery.php
- src/Type/ObjectType/Taxonomy.php
- src/Type/ObjectType/TermObject.php
- src/Type/Union/MenuItemObjectUnion.php
- src/Type/Union/PostObjectUnion.php
- src/Type/Union/TermObjectUnion.php
This PR builds on #2353, by replacing the previous hydration pattern that used allowed post type / taxonomy names to get their objects, with the updated `WPGraphQL::get_allowed_{type}( 'object' ) method. 
e.g  this:
```php
$allowed_post_types = \WPGraphQL::get_allowed_post_types();
if ( ! empty( $allowed_posts_types ) && is_array( $allowed_post_types ) {
foreach( $allowed_post_types as $post_type ) {
$post_type_object = get_post_type_object( $post_type );
if ( $post_type_object instanceof \WP_Post ) {
// do stuff with $post_type_object.
}
}
}
```
becomes this :
```php
$allowed_post_types = \WPGraphQL::get_allowed_post_types( 'objects' );
foreach( $allowed_post_types as $post_type_object …
```
> chore: refactor codebase using `WPGraphQL::get_allowed_{type}( 'objects ')`

- README.md
Swaps out the old codecov badge with coveralls: 
[![Coverage Status](https://coveralls.io/repos/github/wp-graphql/wp-graphql/badge.svg)](https://coveralls.io/github/wp-graphql/wp-graphql)
We're on the verge of [turning yellow](https://github.com/wp-graphql/wp-graphql/pull/2363#issuecomment-1119669389), so no time like the present.
> Chore: replace codecov badge with coveralls

- src/Type/Enum/PostObjectFieldFormatEnum.php
Changes the descriptions on `PostObjectFieldFormatEnum` to clarify default / unauthenticated behavior
#2301
Opted to specify what happens on an unauthenticated request to directly address the confusion point for users.
**Operating System:** Ubuntu 20.04 (WSL2 + devilbox + PHP 8.0.15
**WordPress Version:** 5.9.3
> chore: update PostObjectFieldFormatEnum value descriptions

- composer.json
- composer.lock
- tests/wpunit/FiltersTest.php
- tests/wpunit/PluginCompatibilityTest.php
- tests/wpunit/RootQueryConnectionsTest.php
- tests/wpunit/TypesTest.php
- tests/wpunit/UserObjectMutationsTest.php
This PR updates PHPUnit to `^9.5.`, WPBrowser to `^3.1.6` and `WPGraphQL Test Case to `~2.3`.
As a result, several failing tests had to be updated.
To address #2343, we need to backfill tests handling connection pagination, and the best way to do that is with the improvements in [WPGraphQL Test Case v2.3.0](https://github.com/wp-graphql/wp-graphql-testcase/releases/tag/v2.3.0).
This already would have happened automatically, but [we rolled back to `v2.1`](https://github.com/wp-graphql/wp-graphql/pull/2396#issuecomment-1140146822)
… …
> chore: update PHPUnit, WPBrowser, and WPGraphQL Test Case

- deactivation.php
- phpstan.neon.dist
- phpstan/class-wp-dependency.stub
- src/Data/Connection/AbstractConnectionResolver.php
- src/Data/Connection/EnqueuedScriptsConnectionResolver.php
- src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
- src/Data/Connection/PostObjectConnectionResolver.php
- src/Data/Cursor/CursorBuilder.php
- src/Data/Loader/AbstractDataLoader.php
- src/Data/Loader/EnqueuedScriptLoader.php
- src/Data/Loader/TermObjectLoader.php
- src/Data/NodeResolver.php
- src/Data/PostObjectMutation.php
- src/Model/MenuItem.php
- src/Model/Model.php
- src/Model/User.php
- src/Registry/SchemaRegistry.php
- src/Registry/TypeRegistry.php
- src/Request.php
- src/Router.php
- src/Server/ValidationRules/RequireAuthentication.php
- src/Type/WPInputObjectType.php
- src/Utils/DebugLog.php
- src/Utils/InstrumentSchema.php
- src/Utils/Preview.php
- src/Utils/QueryLog.php
- src/Utils/Tracing.php
- src/WPGraphQL.php
- src/WPSchema.php
This PR fixes ~63~ 66 stan errors when using PHPStan v1.6, as well as a pesky formatting issue that was causing WPCS to fatal error on PHP8.
**Note**: no changes to actual code or the projects dependencies are in this PR. That will happen in a separate PR to fix the remaining ~73~ 70 errors (which do require changes to the code to resolve).
1. On `develop`, run `composer require --dev szepeviktor/phpstan-wordpress phpstan/phpstan`, followed by `composer phpstan`.
2. Checkout this PR, and then run  `composer require --dev szepeviktor/phpstan-wordpress phpstan/phpstan`, followed by `composer phpstan`.
3. Confirm the number of PHPStan errors dropped from 136 to 73
Any relevant logs, error …
> Chore: PHPStan 1.6 fixes (first pass)

- .github/workflows/upload-schema-artifact.yml
This updates the upload-schema-artifact workflow to use PHP 8.1
closes #2415
> Bugfix: fix upload-schema-artifact workflow

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This PR adds YML issue templates to the GitHub repo, in an effort to streamline creating and triaging issues.
Specifically:
- chore: add GH templates for Bug Reports and Feature Requests
- chore: let users ignore templates and add custom links in `config.yml`
#2462
( I cant figure out how to preview the forms in the repo).
Open to all suggestions, my focus is the use of forms, not the particulars of the templates. A second set of eyes to proofread the proposed copy …
> chore: add issue templates to repo

- composer.json
- composer.lock
- phpcs.xml.dist
- src/Connection/TermObjects.php
- src/Connection/Users.php
- src/Data/Connection/CommentConnectionResolver.php
- src/Data/Connection/PostObjectConnectionResolver.php
- src/Data/DataSource.php
- src/Data/MediaItemMutation.php
- src/Data/NodeResolver.php
- src/Data/PostObjectMutation.php
- src/Data/TermObjectMutation.php
- src/Model/Post.php
- src/Mutation/SendPasswordResetEmail.php
- src/Mutation/UpdateSettings.php
- src/Router.php
- src/Type/Enum/MediaItemSizeEnum.php
- src/Type/InterfaceType/ContentTemplate.php
- src/Type/ObjectType/MediaDetails.php
- src/Type/ObjectType/RootQuery.php
- src/WPGraphQL.php
- wp-graphql.php
- Introduces support for the WordPress VIP Go standard
- It either silences or fixes the errors
- It removes duplicate composer packages already bundled in `automattic/vipwpcs`
fixes #1535 
Code reviewer: see my comments for some questions/considerations.
> feat: PHPCS: adding support for the WordPress VIP Go standard

- .github/workflows/testing-integration.yml
This PR updates the testing-integration workflow to enable codeception debugging using the [GitHub `ACTIONS_STEP_DEBUG` secret](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging).
This change allows contributors to more easily debug codeception tests that are passing locally but failing on GH Actions.
1. Visit the integration tests for this PR
2. Click 'Rerun All Tests', and select `Enable debug logging`
…
See here: …
> ci: enable codeception debugging via GH Actions

- docs/authentication.md
The old link points to a version in `master` in which the relevant lines have moved to a different place.
None
> docs: Update permalink to nonce example.

- .github/ISSUE_TEMPLATE/bug_report.yml
It should be a text area, not an input
> chore: Fix bug_report.yml description input

- src/Utils/QueryAnalyzer.php
- wp-graphql.php
This PR modifies the QueryAnalyzer class in the following ways:
- Add a `header_length_limit` property to QueryAnalyzer
- pass `header_length_limit` through a filter, allowing plugins to customize. Default is 8k (8192) to play nice with common clients (Next, Varnish, Node, Fastly)
- Chunk the keys into strings below 8k (or filtered header_length_limit) value and expose the first set as `X-GraphQL-Keys` and the remaining as `X-GraphQL-Skipped-Keys` into multiple headers, each showing their respective strlen
closes #2535  …
> fix: max header length issues with X-GraphQL-Keys

- access-functions.php
- composer.lock
- src/Admin/GraphiQL/GraphiQL.php
- src/Router.php
- src/WPGraphQL.php
- tests/functional/GraphQLHeadersCept.php
- tests/wpunit/AccessFunctionsTest.php
This exposes a new `X-GraphQL-Endpoint` header to be returned in HTTP requests for WPGraphQL.
closes #2564
> feat: add X-GraphQL-URL to headers of GraphQL Responses

- docs/intro-to-graphql.md
> docs: Correct typo

- composer.json
- composer.lock
- wp-graphql.php
Updates the Appsero SDK to v1.2.1 and updates the initialization.
> chore: update Appsero SDK to 1.2.1

- composer.json
- composer.lock
- phpstan.neon.dist
- src/Data/Connection/PluginConnectionResolver.php
- src/Data/Connection/PostObjectConnectionResolver.php
- src/Data/NodeResolver.php
- src/Model/MenuItem.php
- src/Type/Enum/TimezoneEnum.php
- src/Type/ObjectType/TermObject.php
This PR updates the `phpstan` and `phpstan-wordpress` Composer dependencies to their latest versions, and fixes newly surfaced static analysis issues due to this update.
Specific details of these changes are in the comment review.
…
…
**Operating System:** Ubuntu 20.04 (WSL2 + devilbox + PHP 8.0.19)
> chore: update phpstan and fix surfaced issues

- composer.json
- composer.lock
- phpstan.neon.dist
- src/Data/Connection/PluginConnectionResolver.php
- src/Data/Connection/PostObjectConnectionResolver.php
- src/Data/NodeResolver.php
- src/Model/MenuItem.php
- src/Type/Enum/TimezoneEnum.php
- src/Type/ObjectType/TermObject.php
- tests/wpunit/UserObjectMutationsTest.php
This PR updates WPBrowser to v3.1.x along with its associated Composer dev-dependencies, and fixes the tests for `SendPasswordResetEmail` by ensuring a valid `from` email address is used.
Closes #2456
This PR is based on #2538 , which should be merged first to prevent conflicts with `composer.json` and `composer.lock`.
**Operating …
> chore: add WPBrowser v3.1.x compatibility

- access-functions.php
- package.json
- src/Connection/TermObjects.php
- src/Registry/TypeRegistry.php
- src/Registry/Utils/PostObject.php
- src/Registry/Utils/TermObject.php
- src/Type/ObjectType/PostObject.php
- src/Type/ObjectType/TermObject.php
- src/WPGraphQL.php
Adds/ updates the `@since`/`@deprecated` tags, bumps package.json version (since `@wordpress/env` got updated), and cleans up some extra whitespace.
…
…
**Operating System:** Ubuntu 20.04 (WSL2 + Devilbox + PHP 8.0.19)
> chore: cleanup and update version tags

- docs/contributing.md
formatting issues that were breaking the compiler.
> docs: fix contributing doc render errors

- src/AppContext.php
- src/Data/Config.php
- src/Data/Connection/AbstractConnectionResolver.php
- src/Data/Cursor/CommentObjectCursor.php
- src/Data/Cursor/PostObjectCursor.php
- src/Data/Cursor/TermObjectCursor.php
- src/Data/Cursor/UserCursor.php
- src/Data/DataSource.php
- src/Data/Loader/AbstractDataLoader.php
- src/Router.php
- src/Type/Union/MenuItemObjectUnion.php
- src/Types.php
- src/WPGraphQL.php
This PR logs the use of deprecated methods/arguments to debug.log, as well as removes the internal usage of these deprecations from the plugin code.
…
This _does_ not remove deprecated usage from tests.
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + PHP 8.0.19)
> chore: log and cleanup deprecations

- CHANGELOG.md
- readme.txt
- src/WPGraphQL.php
- wp-graphql.php
update versions for WordPress.org deploys
> release: v1.13.3

- .github/workflows/lint-pr.yml
> chore: update lint-pr

- .github/workflows/lint-pr.yml
1. Updates `amannn/action-semantic-pull-request` to v5 to fix node 12 deprecation warnings.
2. Removes `pull_request` trigger, which is both unnecessary since it [duplicates `pull_request_target`](https://github.com/wp-graphql/wp-graphql/actions/runs/4086244952), and [recently started causing failures](https://github.com/wp-graphql/wp-graphql/actions/runs/4086244943). 
…
I don't actually …
> ci: update and fix Lint PR workflow

- .github/workflows/build-graphiql.yml
- .github/workflows/code-quality.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy-docker-image.yml
- .github/workflows/deploy-to-wordpress.yml
- .github/workflows/graphiql-e2e-tests.yml
- .github/workflows/graphiql-unit-tests.yml
- .github/workflows/schema-linter.yml
- .github/workflows/testing-integration.yml
- .github/workflows/upload-schema-artifact.yml
- .github/workflows/wordpress-coding-standards.yml
This PR updates our GitHub workflows to address numerous deprecation warnings.
More specifically:
- Updated `actions/checkout` from v2 to v3.
- Updated `styfle/cancel-workflow-action` from v0.5 v0.11
- Updated `github/codeql-action` suite from v1 to v2
- Updated `actions/setup-node` from various to v3
- Replace deprecated usage of `set-output` with `$GITHUB_OUPUT`
Additionally, the `Cancel Previous Runs` step has been added to additional workflows, to prevent successive commits from causing the runner to stall out.
… …
> ci: fix deprecation warnings in GitHub workflows

- composer.json
- composer.lock
Updates `webonyx/graphql-php` to the latest _minor_ version: `v14.11.9`, as well as any outdated Composer dev-dependencies.
This is to take advantage of updated PHP 8.1 and PHP 8.2 compatibility, such as:
- [14.11.7](https://github.com/webonyx/graphql-php/releases/tag/v14.11.7) : Fix PHP 8.2 deprecation of "static" in callables
- [14.11.3](https://github.com/webonyx/graphql-php/releases/tag/v14.11.3) : Fix compatibility of more methods with native return type in PHP 8.1
- [14.11.1](https://github.com/webonyx/graphql-php/releases/tag/v14.11.1) : Fix compatibility of methods with native return type in PHP 8.1
1. Spin up a WordPress instance running PHP 8.1
2. Run `composer instal`
3. Go …
> chore: update `webonyx/graphql-php` to v14.11.9

- .github/workflows/deploy-docker-image.yml
This updates the Docker Deploy workflow to use latest docker actions.
no
no functional changes to the plugin
> ci: update docker deploy workflow to use latest docker actions

- composer.json
- composer.lock
- phpstan.neon.dist
- src/Mutation/MediaItemCreate.php
- tests/wpunit/MediaItemMutationsTest.php
This adds additional validation to the `createMediaItem` mutation to prevent invalid input to the `filePath` argument.
> fix: adjust validation of createMediaItem mutation

- CHANGELOG.md
- readme.txt
- src/WPGraphQL.php
- wp-graphql.php
- [#2841](https://github.com/wp-graphql/wp-graphql/pull/2841): ci: support STEP_DEBUG in Code Quality workflow. Thanks @justlevine!
- [#2840](https://github.com/wp-graphql/wp-graphql/pull/2840): fix: update createMediaItem mutation to have better validation of input.
- [#2838](https://github.com/wp-graphql/wp-graphql/pull/2838): chore: update security.md to mention where to contact us about security related issues
> release: v1.14.6

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/lint-pr.yml
This PR makes some QoL tweaks to the GitHub Issue and PR templates.
Specifically:
- PR: The Pastebin instruction has been commented out, so it doesnt pollute the the pull request (like in this issue)
- PR: Stripped the `[markdown](links)` from the comment instructions. Since comments are hidden on view, the markdown just makes it harder to read/copy-paste when filling out the PR.
- PR: Adds a the list of allowed PR prefixes to the instructions, so contributors dont need to look in the link/github action.
- Issue: Add a link to the [WPGraphQL Debugging Guide](https://www.wpgraphql.com/docs/debugging) to the bug report instructions. Small victory would be users sharing their debug …
> chore: GitHub template tweaks

- src/Utils/Utils.php
Adds a `skip` param to the `Utils::map_input()` function.
…
> chore: `Skip` param added to `Utils::map_input()`

- CHANGELOG.md
- composer.json
- composer.lock
- readme.txt
- src/Data/Config.php
- src/Data/Connection/TermObjectConnectionResolver.php
- src/Data/Cursor/AbstractCursor.php
- src/Data/Cursor/CommentObjectCursor.php
- src/Data/Cursor/CursorBuilder.php
- src/Data/Cursor/PostObjectCursor.php
- src/Data/Cursor/TermObjectCursor.php
- src/Data/Cursor/UserCursor.php
- src/Router.php
- src/WPGraphQL.php
- tests/wpunit/CommentObjectCursorTest.php
- tests/wpunit/DataConfigTest.php
- tests/wpunit/PostObjectCursorTest.php
- tests/wpunit/TermObjectConnectionQueriesTest.php
- tests/wpunit/TermObjectCursorTest.php
- tests/wpunit/TermObjectQueriesTest.php
- tests/wpunit/UserObjectCursorTest.php
- wp-graphql.php
For WPGraphQL Smart Cache users, you should update WPGraphQL Smart Cache to v1.2.0 when updating 
WPGraphQL to v1.16.0 to ensure caches continue to purge as expected.
This version fixes some behaviors of Cursor Pagination which _may_ lead to behavior changes in your application.
As with any release, we recommend you test in staging environments. For this release, specifically any 
queries you have using pagination arguments (`first`, `last`, `after`, `before`). 
- [#2918](https://github.com/wp-graphql/wp-graphql/pull/2918): feat: Use graphql endpoint without scheme in url header. 
- [#2882](https://github.com/wp-graphql/wp-graphql/pull/2882): feat: Config and Cursor Classes refactor
> release: v1.16.0

- activation.php
- composer.json
- composer.lock
- constants.php
- deactivation.php
- tests/wpunit/TermNodeTest.php
- wp-graphql.php
This refactors the logic around determining whether the plugin can load or not to play nicer with Bedrock.
closes #2946
> fix: regression to autoloader for bedrock sites

- tests/wpunit/AccessFunctionsTest.php
This PR adds basic tests for `register_graphql_input_type()` and `register_graphql_union_type()`
closes #1523
closes #1527 
…
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + PHP 8.1.15)
**WordPress Version:** 6.3.1
> test: backfill `register_graphql_input|union_type()` tests

- src/Model/Model.php
This PR explicitly sets the flags used in `html_entity_decode()`.
The reason for this change is that PHP 8.1+ [changes the default flags](https://www.php.net/manual/en/function.html-entity-decode.php) from `ENT_COMPAT` to `ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401`.
1. By specifying them explicitly, we ensure uniform behavior across current (and potentially future) PHP versions.
2. By adopting the default values from PHP 8.1 as our explicit flags, we get a minor enhancement in < PHP 8.1 versions.
Any other …
> fix: call `html_entity_decode()` with explicit flags and decode single-quotes

- readme.txt
This PR adds @justlevine (me) to the list of contributors, after 499 commits.
No actual code has been changed. 
That's a question for my therapist, but it sure _feels_ good.
500 commits b*tches 🦾
> chore: add @justlevine to list of contributors

- tests/wpunit/TermObjectCursorTest.php
- add test for terms_clauses, ensuring the where arg is properly set (fails in v1.22.0, passes with PR #3063)
no
> test(3063): Adds test for #3603 

- composer.json
- composer.lock
- tests/wpunit/AccessFunctionsTest.php
- tests/wpunit/CommentConnectionQueriesTest.php
- tests/wpunit/ConnectionRegistrationTest.php
- tests/wpunit/ContentTypeConnectionQueriesTest.php
- tests/wpunit/CustomPostTypeTest.php
- tests/wpunit/CustomTaxonomyTest.php
- tests/wpunit/MenuConnectionQueriesTest.php
- tests/wpunit/MenuItemConnectionQueriesTest.php
- tests/wpunit/PluginConnectionQueriesTest.php
- tests/wpunit/PostConnectionPaginationTest.php
- tests/wpunit/RegisteredScriptConnectionQueriesTest.php
- tests/wpunit/RegisteredStylesheetConnectionQueriesTest.php
- tests/wpunit/TaxonomyConnectionQueriesTest.php
- tests/wpunit/TermObjectConnectionQueriesTest.php
- tests/wpunit/ThemeConnectionQueriesTest.php
- tests/wpunit/TracingTest.php
- tests/wpunit/UserConnectionPaginationTest.php
- tests/wpunit/UserRoleConnectionQueriesTest.php
- Upgrades WPGraphQL Testcase to v3.
- Updates tests using `assertIsResponseValid` assertion to use the new `assertResponseIsValid` assertion.
- Fixes issues in preexisting wpunit tests surfaced by the new versions.
…
> chore: WPGraphQLTestcase upgraded to v3

- src/Type/WPInterfaceTrait.php
- tests/wpunit/InterfaceTest.php
This PR does some code quality work on #3116 to improve readability / reduce complexity, and backfill some asserts.
I don't think these warrant special changelog comments vs what's already there.
**WordPress Version:** 6.5.2
> chore: post #3116 cleanup

- composer.json
- composer.lock
- src/WPGraphQL.php
This PR:
1. Updates our composer `dev-deps` to their latest nonbreaking versions.
2. Fixes the `WPGraphQL::get_static_schema()` method to:
- only call `file_get_contents()` once
- correctly return `string|null` instead of `string|false|null`
Before/after with PHPStan 1.11.x
…
**WordPress Version:** 6.5.3
> fix: update dev-deps and fix `WPGraphQL::get_static_schema()`

- bin/run-docker.sh
- composer.json
- docs/testing.md
This PR replaces all remaining uses of `docker-compose` commands with `docker compose`.
Cant find a post about it, but seems as of today `docker-compose` is failing in public GH runners.
E.g. https://github.com/wpengine/wp-graphql-content-blocks/pull/258
…
> ci: replace `docker-compose` commands with `docker compose`

- .github/workflows/deploy-docker-image.yml
- .github/workflows/testing-integration.yml
- bin/run-docker.sh
- composer.json
- docs/testing.md
- readme.txt
- wp-graphql.php
Bumps our headers / testing matrix to test against WordPress 6.6
> [!IMPORTANT]
> This PR is based on #3181 and requires that to be merged first.
…
> ci: test against WP 6.6

- .github/workflows/testing-integration.yml
- src/Data/Loader/UserLoader.php
- wp-graphql.php
This improves the performance of the SQL query in the User Loader that checks whether a user is considered a published author.
closes #3178
> fix: improve performance of SQL query in the user loader

- src/Model/Post.php
- src/Registry/Utils/PostObject.php
This PR fixes an issue where trying to get a `sourceUrl` by `size` would cause the image URLs for _all_ the sizes to resolve. This inevitably leads to slowdowns on sites with lots of registered image sizes (e.g. WooCommerce sites)
The fix works by introducing a new `Post::get_source_url_by_size()` public method used instead of the `sourceUrlsBySize` model field, which has been deprecated.
Discord: https://discord.com/channels/838854618406453300/1282730629305208832/1283796889615073321 …
> fix: lazy-resolve `Post.sourceUrl` and deprecate `Post.sourceUrlsBySize`

- docs/quick-start.md
- use wpackagist-plugin/wp-graphql in the composer example
closes: #3179
> chore: update quick-start.md to provide more clarity around using wpackagist

- composer.json
This PR fixes an issue with Composer's autoloader due to `WPGraphQL.php` not being PSR-4 compatible.
It is addressed by adding the file manually to the `classmap`.
- Before
- After
…
**Operating System:** Ubuntu 24.04 (WSL + ddev + PHP 8.2.24)
**WordPress Version:** 6.7
> chore: fix Composer autoloader for `WPGraphQL.php`

- docs/authentication-and-authorization.md
- docs/build-your-first-wpgraphql-extension.md
- docs/categories-and-tags.md
- docs/comments.md
- docs/performance.md
- src/Data/Connection/CommentConnectionResolver.php
- src/Model/Post.php
- src/Type/Connection/Comments.php
- tests/wpunit/CommentMutationsTest.php
- tests/wpunit/CommentObjectQueriesTest.php
This improves some documentation: 
Re-organize the article and clarify and expand on some points. 
- Re-organize the article and expand on some topics to give a bit more depth and clarity. 
- Added pre-reqs. 
- Explained some best practices.
- Provided conceptual and practical example. 
- re-organized the article
- fixed some typos
- provided more examples
- called out performance considerations
- Updated content on hierarchical queries / mapping
- Provided more example queries
- Added more clarity around comment visibility / user capabilities and comment statuses
- Discussed comment meta and provided examples for using comment meta
- Called out performance considerations and using …
> chore: update docs & improve comment functionality

- .github/workflows/code-quality.yml
- .github/workflows/graphiql-e2e-tests.yml
- .github/workflows/schema-linter.yml
- .github/workflows/testing-integration.yml
- .github/workflows/wordpress-coding-standards.yml
This PR enables our GH Workflows to trigger on commits/prs to `release/*` branches.
Addresses https://github.com/wp-graphql/wp-graphql/pull/3247#issuecomment-2557238011
…
> ci: trigger PR workflows on `release/*` branches

- composer.json
- composer.lock
- src/Data/Connection/CommentConnectionResolver.php
- src/Data/Cursor/AbstractCursor.php
- src/Data/UserMutation.php
- src/Model/Menu.php
- src/Model/Term.php
- src/Model/Theme.php
- src/Mutation/MediaItemCreate.php
- src/Registry/TypeRegistry.php
- src/Utils/InstrumentSchema.php
- src/Utils/QueryAnalyzer.php
This PR:
- Adds `phpstan/phpstan-deprecation-rules` to the Composer dev-deps
- _Begins_ implementing [bleeding edge](https://phpstan.org/blog/what-is-bleeding-edge) PHPStan fixes
Both of these are part of the [PHPStan 2.0 migration path](https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md). They're being dealt with here in preparation of the PHP version bump in  #3247 which will allow us to upgrade the dependency.
Further bleeding edge fixes will be …
> chore: fix bleeding edge/deprecated PHPStan smells [first pass]

- cli/wp-cli.php
Added an option to provide a custom path for a file.
Resolves #3277 
…
- Ubuntu 24.04.01 LTS
- Ubuntu 22.04.5 LTS
- Core v6.7.1 running against PHP v8.3.15
> feat: add option to provide custom file path for static schemas

- docs/menus.md
Fixes a broken link for https://www.wpgraphql.com/docs/menus#hierarchical-data
See "You can see this technique in action in the codebase for the website you’re reading [here](https://github.com/wp-graphql/wpgraphql.com/blob/master/src/components/DocsSidebar.js#L8-L26)."
No.
No.
…
> fix: Updated docs link for example of hierarchal data

- .github/workflows/deploy-docker-image.yml
- phpcs.xml.dist
- src/Registry/TypeRegistry.php
- src/Type/WPConnectionType.php
- src/Type/WPInputObjectType.php
- src/Type/WPInterfaceType.php
- src/Type/WPObjectType.php
- src/Type/WPUnionType.php
This PR removes a lot of the unnecessary type coersions, instead opting for remediating against the source of truth (with `@phpstan-import-type.
As a result a few bugs in the v2.0 migration were fixed (e.g missing `$config` names, union `resolveType` missing the new $context/$info params, etc.
Follows up #3288 , but there's probably at least one more pass of type safety that should be done (the parallel feedback on #3247 directly)
… …
> fix: [v2.0] Cleanup PHPStan type coercions and fix underlying issues (second pass)

- phpcs.xml.dist
- src/Data/Connection/AbstractConnectionResolver.php
- src/Data/Loader/AbstractDataLoader.php
This PR restores the following PHPCS excluded rules:
- `WordPress.NamingConventions.ValidFunctionName.MethodNameInvalid`
- `SlevomatCodingStandard.TypeHints.NullableTypeForNullDefaultValue.NullabilityTypeMissing`
The remaining singular use of each these have been inlined.
> [!NOTE]
> No changes to production code have been made.
…
> chore: restore excluded PHPCS rules

- src/Admin/Extensions/Registry.php
This PR submits the following plugins for consideration to the WPGraphQL Extension Library
- WPGraphQL for Gravity Forms: https://github.com/axewp/wp-graphql-gravity-forms
- Headless Login for WPGraphQL: https://github.com/axewp/wp-graphql-headless-login
- WPGraphQL for Rank Math SEO: https://github.com/axewp/wp-graphql-rank-math 
Did these in a single PR to avoid the merge conflicts, but if it's better for documentation purposes, I can split them up.
> chore: submit GF, Rank Math, and Headless Login plugins

- .coveralls.yml
- .distignore
- .github/workflows/testing-integration.yml
- .gitignore
- composer.json
- composer.lock
This PR removes the local use of `php-coveralls` in favor of the official [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action), and then bumps Composer dev-deps to their latest (semver-compatible) versions.
The PR is applied on v2.0.0 since that's where the dependency tree matters.
…
> chore: (v2.0) remove php-coveralls from dev-dependencies

- src/Data/Connection/AbstractConnectionResolver.php
- src/Data/Connection/README.md
Adds an `.md` file for using and extending `AbstractConnectionResolver`.
Additionally cleans up typos in the AbstractConnectionResolver file.
Part of #2749 
…
**WordPress Version:**n/a
> docs: add developer docs for `AbstractConnectionResolver`

- .github/workflows/generate-changeset.yml
Fixes a bug in the Github workflow that generates changesets.
> fix: error in Github Workflow

- .changeset/pr-3333-1741323496547.md
Automatically generated changeset for PR #3333. This PR contains version bump information and changelog entries.
> Changeset for PR #3333

- src/Router.php
This fixes the following error appearing on the GraphQL endpoint: `Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated`
…
…
> fix: Avoid the deprecation warning when sending null header values

- .github/workflows/changeset-generation.yml
- .github/workflows/release.yml
- .github/workflows/schema-linter.yml
This updates GitHub workflows to use node 20
> chore: update workflows to use node version 20

- .github/workflows/README.md
- .github/workflows/changeset-generation.yml
- README.md
This updates the README files for workflows and updates badges in the main readme for workflows that weren't previously badged.
n/a
> chore: update README's for github workflows

- src/Type/InterfaceType/Commenter.php
- src/Type/InterfaceType/Connection.php
- src/Type/InterfaceType/ContentNode.php
- src/Type/InterfaceType/ContentTemplate.php
- src/Type/InterfaceType/DatabaseIdentifier.php
- src/Type/InterfaceType/Edge.php
- src/Type/InterfaceType/EnqueuedAsset.php
- src/Type/InterfaceType/HierarchicalContentNode.php
- src/Type/InterfaceType/HierarchicalNode.php
- src/Type/InterfaceType/MenuItemLinkable.php
- src/Type/InterfaceType/Node.php
- src/Type/InterfaceType/NodeWithAuthor.php
- src/Type/InterfaceType/NodeWithComments.php
- src/Type/InterfaceType/NodeWithContentEditor.php
- src/Type/InterfaceType/NodeWithExcerpt.php
- src/Type/InterfaceType/NodeWithFeaturedImage.php
- src/Type/InterfaceType/NodeWithPageAttributes.php
- src/Type/InterfaceType/NodeWithRevisions.php
- src/Type/InterfaceType/NodeWithTemplate.php
- src/Type/InterfaceType/NodeWithTitle.php
- src/Type/InterfaceType/NodeWithTrackbacks.php
- src/Type/InterfaceType/OneToOneConnection.php
- src/Type/InterfaceType/PageInfo.php
- src/Type/InterfaceType/Previewable.php
- src/Type/InterfaceType/TermNode.php
- src/Type/InterfaceType/UniformResourceIdentifiable.php
- src/Type/WPConnectionType.php
This updates Interface Type descriptions to provide more clarity in the schema for what the Types mean and are intended for.
> chore: update interface descriptions

- .github/workflows/deploy-docker-image.yml
- .github/workflows/testing-integration.yml
- access-functions.php
- bin/run-docker.sh
- constants.php
- docs/compatibility-guide.md
- docs/testing.md
- readme.txt
- wp-graphql.php
This PR adds WordPress 6.8 to the test matrix, and bumps the relevant headers and references
> [!IMPORTANT]
> This PR is based on #3360 which should be merged first.
>
> Relevant diff: https://github.com/wp-graphql/wp-graphql/pull/3361/commits/a07575ffb7324c251da944036c765bd20049ae9f
> chore: Test compatibility with WordPress 6.8

- composer.json
- composer.lock
- phpcs.xml.dist
This PR updates the Composer deps to their latest (semver) compatible versions.
Of note:
- `webonyx/graphql-php` v15.20.0 : https://github.com/webonyx/graphql-php/releases/tag/v15.20.0
- `slevomat/coding-standards` deprecated `SlevomatCodingStandard.TypeHints.UnionTypeHintFormat` which we weren't explicitly using in favor of `SlevomatCodingStandard.TypeHints.DNFTypeHintFormat` which we're already implicitly including, so the former is now excluded. Ref: https://github.com/slevomat/coding-standard/blob/34325312cbd9465a222564597e9f56e42750939c/SlevomatCodingStandard/Sniffs/TypeHints/UnionTypeHintFormatSniff.php#L74
-
Nope
(Are changesets a thing we need to be adding now?)
> chore: Update Composer deps

- src/Utils/Tracing.php
This PR fixes a code quality bug where the `do_graphql_request` was incorrectly being called via `add_filter()` instead of `add_action()`. 
As a result of this change, the `Tracing::init_trace()` has been changed from returning a `float` unused by the application to returning `void`.
This is _technically_ a breaking change, as that method is public, and the Tracing class is not marked `final`. However, there doesn't seem to be a way _in_ WPGraphQL to replace this version with an extended version (unlike some other filterable classes).
> [!IMPORTANT]
> ~This PR is based on #3368 which should be merged first.~
>
> ~Relevant diff for this PR is: https://github.com/wp-graphql/wp-graphql/commit/3f0de2398b75dcf63f7ff98ea0c677f3fa5d54a9~
> Rebased ✔️
Not directly, but if we consider this a …
> fix!: make `Tracing::init_trace()` void and call on `add_action()`

- .wp-env.json
- composer.lock
- tests/e2e/plugins/settings-page-spec/settings-page-spec.php
- tests/e2e/specs/settings-page.spec.js
- tests/e2e/utils.js
This PR fixes broken e2e tests for the WPGraphQL settings page that were caused by recent changes to the wp-env configuration format.
In PR (https://github.com/wp-graphql/wp-graphql/pull/3408/files), the `.wp-env.json` configuration was restructured to use the new wp-env format that separates development and test environments:
- Development environment: `localhost:8888` (custom plugin not loaded)
- Tests environment: `localhost:8889` (custom plugin loaded)
However, the e2e tests were still connecting to the development environment where the custom test plugin wasn't available.
1. **Fixed test environment URLs** (`tests/e2e/utils.js`):
- Updated `wpHomeUrl` and `wpAdminUrl` from `localhost:8888` to `localhost:8889`
- Updated `loginToWordPressAdmin()` to use the correct test environment
2. …
> fix: update failing e2e tests for graphiql
